assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/settings.js
edit/host.vue
models/network.harvesterhci.io.nodenetwork.js

https://github.com/harvester/harvester/issues/980

HARVESTER: fix: nodenetwork & clusternetwork change to no-namespace

---

components/form/NodeAffinity.vue
components/form/NodeScheduling.vue
config/product/explorer.js
detail/kubevirt.io.virtualmachine/index.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/vm.js

[https://github.com/harvester/harvester/issues/817](https://github.com/harvester/harvester/issues/817)

HARVESTER: add Node Scheduling to VM edit page

---

components/nav/Header.vue
layouts/default.vue
store/index.js

- https://github.com/harvester/harvester/issues/1094
- https://github.com/harvester/harvester/issues/1100

HARVESTER:fix:Incorrect Harvester version

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/form/NodeScheduling.vue

[https://github.com/harvester/harvester/issues/817](https://github.com/harvester/harvester/issues/817)

HARVESTER: update scheduling labels

---

edit/kubevirt.io.virtualmachine/index.vue
edit/volume.vue
mixins/vm.js
models/persistentvolumeclaim.js
pages/auth/setup.vue
utils/validators/setting.js

- https://github.com/harvester/harvester/issues/879
- https://github.com/harvester/harvester/issues/1095

HARVESTER: fix setup page vendor value & change PVC size & template bug

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/DetailTop.vue
models/node.js

[https://github.com/harvester/harvester/issues/817](https://github.com/harvester/harvester/issues/817)

HARVESTER: hide system labels by default

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/labels-annotations.js
detail/harvesterhci.io.virtualmachineimage.vue
edit/harvesterhci.io.virtualmachineimage.vue
models/harvesterhci.io.virtualmachineimage.js
utils/custom-validators.js
utils/validators/vm-image.js

https://github.com/harvester/harvester/issues/570

HARVESTER:feat: image upload

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/product/virtual.js
list/cloudTemplate.vue
list/namespace.vue
models/configmap.js

- https://github.com/harvester/harvester/issues/1130
- fix nav menu (namespace => namespaces && delete grouping)

HARVESTER: fix: error text

---

components/InputOrDisplay.vue
components/formatter/vmState.vue
components/nav/Header.vue
config/labels-annotations.js
config/product/virtual.js
config/types.js
detail/harvesterhci.io.virtualmachinebackup/basic.vue
detail/harvesterhci.io.virtualmachinebackup/index.vue
edit/harvesterhci.io.virtualmachinebackup.vue
edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/kubevirt.io.virtualmachine/CpuMemory.vue
edit/kubevirt.io.virtualmachine/volume/index.vue
edit/kubevirt.io.virtualmachine/volume/type/existing.vue
edit/kubevirt.io.virtualmachine/volume/type/vmImage.vue
edit/kubevirt.io.virtualmachine/volume/type/volume.vue
list/kubevirt.io.virtualmachine/index.vue
models/harvesterhci.io.virtualmachinebackup.js

- https://github.com/harvester/harvester/issues/1072
- some other issue

HARVESTER: support download kubectl & fix some issue

---

config/settings.js
detail/kubevirt.io.virtualmachine/tabs/details/disks.vue
edit/kubevirt.io.virtualmachine/index.vue
edit/kubevirt.io.virtualmachine/network/base.vue
edit/kubevirt.io.virtualmachine/volume/type/vmImage.vue
list/harvesterhci.io.setting.vue
models/harvesterhci.io.setting.js
pages/fail-whale.vue
utils/validators/vm.js

- https://github.com/harvester/harvester/issues/846
- filter harvester setting 
- fix singleHarvester return home page error
- fix create vm from image

HARVESTER: enhancement harvester setting & return home page

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/dialog/AddHotplugModal.vue
mixins/vm.js
models/kubevirt.io.virtualmachine.js

HARVESTER: support add hotplug volume

---

edit/host/index.vue

https://github.com/harvester/harvester/issues/1208

HARVESTER:fix:No disk shows up when plugging a new disk to add to host

---

config/product/virtual-manager.js
store/features.js

https://github.com/rancher/dashboard/issues/3465

Add harvester feature flag

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/dialog/harvester/MigrationDialog.vue
edit/harvesterhci.io.host/index.vue

- Users can update host labels now
[https://github.com/harvester/harvester/issues/1198](https://github.com/harvester/harvester/issues/1198)

HARVESTER: fix migration bugs

---

detail/harvesterhci.io.host/HarvesterHostBasic.vue

https://github.com/harvester/harvester/issues/1253

HARVESTER:fix:Host overview doesn't show actual available storage from longhorn

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
detail/kubevirt.io.virtualmachine/index.vue
list/harvesterhci.io.dashboard/index.vue
utils/grafana.js

- Add Cluster Metrics to harvester dashboard
- Dashboard page, Metrics -> VM Metrics
- VM detail page, Metrics -> VM Metrics

HARVESTER:fix:Add cluster monitoring metrics

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/dialog/harvester/AddHotplugModal.vue
components/dialog/harvester/BackupModal.vue
components/dialog/harvester/CloneTemplate.vue
components/dialog/harvester/ExportImageDialog.vue
models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/568

HARVESTER: Create image from volume

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
list/harvesterhci.io.management.cluster.vue

- https://github.com/rancher/dashboard/issues/4273
- https://github.com/rancher/dashboard/issues/3466

Fix harvester cluster manager issues

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/form/NodeAffinity.vue
components/form/NodeScheduling.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm.js

- https://github.com/harvester/harvester/issues/1234
- add Run Vm on specific node(s)

HARVESTER: change node scheduling

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
edit/harvesterhci.io.virtualmachineimage.vue
models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/1279
- https://github.com/harvester/harvester/issues/568

Harvester: show image sourceType in edit page & fix miss actions in volume list page

---

pages/c/_cluster/harvester/support/index.vue

HARVESTER:fix:Hide support bundle link if users have no permission for it

---

edit/harvesterhci.io.management.cluster.vue
models/harvesterhci.io.management.cluster.js

- Fix edit YAML jump to mgmt cluster page.
- Fix edit config => edit YAML, isSpoofted added to yaml.

HARVESTER:fix:Edit cluster yaml

---

components/ResourceTable.vue
components/form/NameNsDescription.vue
components/nav/NamespaceFilter.vue
config/labels-annotations.js
list/harvesterhci.io.volume.vue
list/namespace.vue
plugins/steve/resource-instance.js
store/index.js

https://github.com/harvester/harvester/issues/1001

HARVESTER: filter namespace in harvester cluster

---

edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue

https://github.com/harvester/harvester/issues/1232

HARVESTER: Fix display an incorrect image name (1232)

---

components/ResourceTable.vue
list/harvesterhci.io.host/index.vue
models/harvester/configmap.class.js

- https://github.com/rancher/dashboard/issues/4299

HARVESTER: fix standard user is missing access to multiple pages (4299)

---

components/PromptRemove.vue

https://github.com/harvester/harvester/issues/1301
Go to harvester UI will reset cluster store, we need findAll action dispatched by the product store.

HARVESTER:Fix delete cluster throw an error

---

components/formatter/HarvesterIpAddress.vue
components/nav/Header.vue
config/product/harvester.js
mixins/brand.js

- https://github.com/harvester/harvester/issues/1305
- https://github.com/harvester/harvester/issues/1331

HARVESTER: fix singleVirtualCluster icon

---

models/management.cattle.io.project.js
store/index.js

- https://github.com/harvester/harvester/issues/1002

HARVESTER: fix harvester namespace filter error

---

edit/harvesterhci.io.virtualmachinebackup.vue
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1313
- https://github.com/harvester/harvester/issues/1309

HARVESTER:Fix VM Backup can only be restored once

---

edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue

- https://github.com/harvester/harvester/issues/1372

HARVESTER: fix 1372

---

edit/network.harvesterhci.io.clusternetwork/vlan.vue

HARVESTER: add nics filter

---

config/product/harvester.js
layouts/default.vue

HARVESTER: Add locale

---

components/dialog/SupportBundle.vue
edit/harvesterhci.io.virtualmachineimage.vue
edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue
edit/kubevirt.io.virtualmachine/index.vue
plugins/steve/resource-instance.js

- https://github.com/harvester/harvester/issues/1415

HARVESTER: Fixed upload image & create multiple vm display error

---

edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
mixins/harvester-vm.js

- https://github.com/harvester/harvester/issues/1283

Fixed 1283

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/form/ResourceQuota/index.vue
components/formatter/HarvesterDiskState.vue
config/settings.js
edit/management.cattle.io.project.vue
edit/provisioning.cattle.io.cluster/rke2.vue
edit/service.vue
list/harvesterhci.io.virtualmachineimage.vue
models/harvester/harvesterhci.io.virtualmachineimage.js
store/harvester-common.js
utils/cluster.js

- https://github.com/harvester/harvester/issues/1435
- https://github.com/harvester/harvester/issues/1380
- https://github.com/harvester/harvester/issues/1449
- https://github.com/harvester/harvester/issues/1489

HARVESTER: Add harvester LB label auto-set

---

edit/harvesterhci.io.cloudtemplate.vue
edit/harvesterhci.io.virtualmachineimage.vue
edit/kubevirt.io.virtualmachine/index.vue
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1304

show Edit as Yaml button (#1304)

---

components/form/InputWithSelect.vue
edit/harvesterhci.io.virtualmachineimage.vue

- https://github.com/harvester/harvester/issues/1269

HARVESTER: Fix  cursor jumps to the end while editing image name

---

mixins/harvester-vm/impl.js
mixins/harvester-vm/index.js

- https://github.com/harvester/harvester/issues/1235

HARVESTER: Enhanced 1235

---

edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/DataTemplate.vue
edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue

- https://github.com/harvester/harvester/issues/1453

HARVESTER: Fixed list abnormal refresh #1453

---

components/dialog/harvester/MaintenanceDialog.vue
config/labels-annotations.js
mixins/harvester-vm/index.js
models/harvester/node.js

- https://github.com/harvester/harvester/issues/1350
- https://github.com/harvester/harvester/issues/1014

Harvester: add node maintenance status

---

mixins/create-edit-view/impl.js
models/harvester/management.cattle.io.setting.js

- https://github.com/harvester/harvester/issues/1489

HARVESTER: Fix edit Advanced Setting option `server-url` will redirect to inappropriate page.

---

components/dialog/harvester/MigrationDialog.vue
edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/kubevirt.io.virtualmachine/index.vue
list/kubevirt.io.virtualmachine.vue
mixins/harvester-vm/index.js
models/harvester/node.js

- https://github.com/harvester/harvester/issues/1504
- https://github.com/harvester/harvester/issues/1501
- https://github.com/harvester/harvester/issues/1512
- https://github.com/harvester/harvester/issues/1516

HARVESTER: fixed create multiple vm instance (1504) & (1501)

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
detail/harvesterhci.io.host/HarvesterHostNetwork.vue
detail/harvesterhci.io.host/index.vue

- https://github.com/harvester/harvester/issues/531

HARVESTER:Add host network detail tab

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/settings.js
edit/harvesterhci.io.setting/backup-target.vue
edit/harvesterhci.io.setting/http-proxy.vue
edit/harvesterhci.io.setting/overcommit-config.vue
mixins/harvester-vm/index.js
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1218
- https://github.com/harvester/harvester/issues/1260
- https://github.com/harvester/harvester/issues/1429
- https://github.com/harvester/harvester/issues/982

HARVESTER: add settings

---

list/harvesterhci.io.host/index.vue
mixins/harvester-vm/impl.js
models/harvester/persistentvolumeclaim.js
store/index.js

- https://github.com/harvester/harvester/issues/1520
- https://github.com/harvester/harvester/issues/1533

HARVESTER: incorrect title and favicon

---

components/ConsumptionGauge.vue
components/formatter/HarvesterCPUUsed.vue
components/formatter/HarvesterMemoryUsed.vue
list/harvesterhci.io.dashboard/index.vue
list/harvesterhci.io.host/index.vue
models/harvester/node.js

- https://github.com/harvester/harvester/issues/1376

HARVESTER: Change node cpu/memory used to reserved

---

models/harvester/harvesterhci.io.blockdevice.js

Fix disk shows no options on the host page.

HARVESTER: Fix disk options bug

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
edit/provisioning.cattle.io.cluster/rke2.vue
edit/service.vue
utils/cluster.js

This reverts commit 7ba7dfe5d47c6bb1ccfd3d398268f88899d70695.

Revert "HARVESTER: Add harvester LB label auto-set"

---

assets/translations/en-us.yaml
detail/harvesterhci.io.host/VirtualMachineInstance.vue
detail/kubevirt.io.virtualmachine/VirtualMachineTabs/VirtualMachineBasics.vue
list/kubevirt.io.virtualmachine.vue
mixins/harvester-vm/index.js
models/harvester/harvesterhci.io.virtualmachinetemplateversion.js
models/harvester/kubevirt.io.virtualmachine.js
pages/auth/login.vue

- https://github.com/harvester/harvester/issues/1534
- https://github.com/harvester/harvester/issues/1429
- https://github.com/harvester/harvester/issues/1550
Note: `memory.guest` is calculated by the backend

HARVESTER: fix vm unit display error

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/settings.js
edit/harvesterhci.io.setting/index.vue
edit/harvesterhci.io.setting/vip-pools.vue
list/harvesterhci.io.setting.vue
models/harvester/harvesterhci.io.virtualmachineimage.js

- https://github.com/harvester/harvester/issues/1458

Add vip cidr pool as setting

---

models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1565

HARVESTER: cancel limit cpu size

---

edit/harvesterhci.io.cloudtemplate.vue
edit/harvesterhci.io.virtualmachineimage.vue
edit/harvesterhci.io.volume.vue
edit/k8s.cni.cncf.io.networkattachmentdefinition.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/index.js

- https://github.com/harvester/harvester/issues/1304
- https://github.com/harvester/harvester/issues/1564

HARVESTER: support edit as yaml

---

edit/harvesterhci.io.virtualmachineimage.vue
edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/index.js

https://github.com/harvester/harvester/issues/1304

HARVESTER: fixed create vm & edit as yaml enhancement

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/formatter/BadgeStateFormatter.vue
config/labels-annotations.js
edit/k8s.cni.cncf.io.networkattachmentdefinition.vue
list/k8s.cni.cncf.io.networkattachmentdefinition.vue
models/k8s.cni.cncf.io.networkattachmentdefinition.js

HARVESTER: Add network route config

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/settings.js
edit/harvesterhci.io.setting/additional-ca.vue
edit/harvesterhci.io.setting/ssl-certificates.vue
edit/harvesterhci.io.setting/vm-force-deletion-policy.vue

- https://github.com/harvester/harvester/issues/1585
- https://github.com/harvester/harvester/issues/1360
- https://github.com/harvester/harvester/issues/761

HARVESTER:  add settings

---

components/formatter/HarvesterCPUUsed.vue
components/formatter/HarvesterMemoryUsed.vue
detail/harvesterhci.io.host/HarvesterHostBasic.vue
detail/harvesterhci.io.host/index.vue

- https://github.com/harvester/harvester/issues/1612

HARVESTER: Fix host detail cpu and memory used

---

edit/harvesterhci.io.host/index.vue

- https://github.com/harvester/harvester/issues/1608

HARVESTER: Fix disk options not filter

---

list/kubevirt.io.virtualmachine.vue
mixins/harvester-vm/index.js
models/harvester/kubevirt.io.virtualmachine.js

https://github.com/harvester/harvester/issues/1613

HARVESTER: fix vm memory

---

assets/translations/en-us.yaml
config/settings.js
edit/harvesterhci.io.setting/ssl-parameters.vue

- https://github.com/harvester/harvester/issues/1046

HARVESTER: Add ssl parameters

---

assets/translations/en-us.yaml

https://github.com/harvester/harvester/issues/1634

HARVESTER: fix text

---

components/nav/Header.vue

- https://github.com/harvester/harvester/issues/1409

HARVESTER: fix harvester change password

---

detail/harvesterhci.io.host/index.vue
edit/harvesterhci.io.host/index.vue
models/harvester/node.js

- https://github.com/harvester/harvester/issues/1623
- https://github.com/harvester/harvester/issues/1272

HARVESTER: Fix disk dropdown and host state color

---

models/harvester/harvesterhci.io.virtualmachinebackup.js
plugins/steve/resource-class.js

- https://github.com/harvester/harvester/issues/988

HARVESTER: Delect backup add params

---

edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
mixins/harvester-vm/index.js

- https://github.com/harvester/harvester/issues/1655
- https://github.com/harvester/harvester/issues/1660

HARVESTER: fix vm bug

---

assets/translations/en-us.yaml
pages/auth/setup.vue

- https://github.com/harvester/harvester/issues/1634

HARVESTER: fix 1634

---

assets/translations/en-us.yaml
edit/harvesterhci.io.setting/ssl-parameters.vue

- https://github.com/harvester/harvester/issues/1046

HARVESTER: Add TLS ciphers validate

---

edit/harvesterhci.io.setting/ssl-parameters.vue

- https://github.com/harvester/harvester/issues/1046

HARVESTER: Update ssl params validator && Add deprecated for ssl

---

assets/translations/zh-hans.yaml
edit/harvesterhci.io.setting/ssl-parameters.vue

- https://github.com/harvester/harvester/issues/1046

HARVESTER: Update ssl params validator

---

assets/translations/en-us.yaml
config/settings.js
edit/harvesterhci.io.setting/support-bundle-namespaces.vue

- https://github.com/harvester/harvester/pull/1675

HARVESTER: add support-namespace setting

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/ActionMenu.vue
components/Collapse.vue
components/HarvesterUpgradeProgressBarList.vue
components/nav/HarvesterUpgrade.vue
components/nav/Header.vue
config/labels-annotations.js
config/types.js
list/harvesterhci.io.dashboard/HarvesterUpgrade.vue
list/harvesterhci.io.setting.vue
models/harvester/harvesterhci.io.setting.js
models/harvester/harvesterhci.io.upgrade.js
models/harvester/harvesterhci.io.virtualmachineimage.js
pages/c/_cluster/harvester/airgapupgrade/index.vue
store/index.js

- https://github.com/harvester/harvester/issues/1022

Harvester upgrade

---

detail/harvesterhci.io.host/HarvesterHostDisk.vue
edit/harvesterhci.io.host/HarvesterDisk.vue
models/harvester/harvesterhci.io.blockdevice.js

- https://github.com/harvester/harvester/issues/1334

HARVESTER: Add provisionPhase

---

models/harvester/harvesterhci.io.setting.js
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1708
- https://github.com/harvester/harvester/issues/1719

HARVESTER: fix detach volume

---

assets/translations/en-us.yaml
config/settings.js
models/harvester/harvesterhci.io.setting.js

- https://github.com/harvester/harvester/issues/1721

HARVESTER: add auto-disk-provision-paths setting

---

assets/translations/en-us.yaml
edit/kubevirt.io.virtualmachine/index.vue

- https://github.com/harvester/harvester/issues/1701

HARVESTER: add helper text

---

components/form/NameNsDescription.vue
components/nav/NamespaceFilter.vue
config/settings.js
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
list/harvesterhci.io.dashboard/index.vue
list/harvesterhci.io.setting.vue

- https://github.com/harvester/harvester/issues/1724
- https://github.com/harvester/harvester/issues/1709
- https://github.com/harvester/harvester/issues/1713

fix 1709、1713、1724

---

assets/translations/en-us.yaml
components/nav/WindowManager/ContainerLogs.vue
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1784

HARVESTER: add view logs in vm

---

components/form/LabeledSelect.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
machine-config/harvester.vue
models/harvester/harvesterhci.io.virtualmachineimage.js

- https://github.com/harvester/harvester/issues/1663

HARVESTER: Add Image filter when create VM

---

edit/harvesterhci.io.setting/backup-target.vue
models/harvester/harvesterhci.io.setting.js
models/harvester/harvesterhci.io.virtualmachineimage.js
utils/validators/setting.js

- https://github.com/harvester/harvester/issues/1791

HARVESTER: fix image error message

---

components/formatter/HarvesterCPUUsed.vue
components/formatter/HarvesterMemoryUsed.vue
list/harvesterhci.io.dashboard/index.vue

- https://github.com/harvester/harvester/issues/1821

HARVESTER: Fix cpu and memory reserved when node is unavailable

---

assets/translations/en-us.yaml
components/NovncConsole.vue

- https://github.com/harvester/harvester/issues/1236

HARVESTER: Add vnc error message

---

components/formatter/HarvesterIpAddress.vue
utils/string.js

- https://github.com/harvester/harvester/issues/1746

HARVESTER: show all ipv4 address

---

components/form/ResourceTabs/index.vue
edit/harvesterhci.io.volume.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue
models/harvester/persistentvolumeclaim.js
plugins/steve/resource-class.js

- https://github.com/harvester/harvester/issues/1346

HARVESTER: volume enhancement

---

components/dialog/harvester/MigrationDialog.vue
config/labels-annotations.js
models/harvester/harvesterhci.io.blockdevice.js
models/harvester/node.js

- https://github.com/harvester/harvester/issues/1604
- https://github.com/harvester/harvester/issues/1755
**Change**
- Fix `kubevirt.io/schedulable` typo
- Add state filter for migration node list
- Fix disk can not be added

HARVESTER: Fix migration node list

---

components/form/SerialConsole/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/base.vue

- [https://github.com/harvester/harvester/issues/1756](https://github.com/harvester/harvester/issues/1756)
- [https://github.com/harvester/harvester/issues/1760](https://github.com/harvester/harvester/issues/1760)

HARVESTER: Make serial console window is height-adjustable and do not update macAddress immediately on VM page

---

list/harvesterhci.io.dashboard/index.vue

- https://github.com/harvester/harvester/issues/1840

HARVESTER: Add cluster used metrics

---

list/harvesterhci.io.setting.vue
pages/auth/login.vue
pages/auth/setup.vue

removed extra ID that wasn't used

added in selectors for automated login tests and settings tests

---

models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1650

fix restore state

---

mixins/harvester-vm/impl.js
mixins/harvester-vm/index.js

- https://github.com/harvester/harvester/issues/1833

HARVESTSER: change opensuse qga

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/settings.js
edit/harvesterhci.io.setting/index.vue
edit/harvesterhci.io.setting/support-bundle-image.vue

- https://github.com/harvester/harvester/issues/1727

HARVESTSER: add support-bundle-image in setting page

---

mixins/harvester-vm/index.js

- https://github.com/harvester/harvester/issues/1856
- https://github.com/harvester/harvester/issues/1871

HARVESTSER: fix qga overwritten

---

components/formatter/HarvesterCPUUsed.vue
components/formatter/HarvesterMemoryUsed.vue
components/formatter/HarvesterStorageUsed.vue
detail/harvesterhci.io.host/HarvesterHostBasic.vue
list/harvesterhci.io.dashboard/index.vue

- https://github.com/harvester/harvester/issues/1840
**Change**
- Add used metrics on the node detail page
- Add cluster storage reserved and node storage reserved metrics

HARVESTER: Add node detail used and storage reserved

---

components/formatter/HarvesterMigrationState.vue
detail/kubevirt.io.virtualmachine/VirtualMachineTabs/VirtualMachineBasics.vue
detail/kubevirt.io.virtualmachine/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
models/harvester/kubevirt.io.virtualmachine.js
models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/1346
1.  vm edit page  add volume state
2. vm detail page add volume state
3. vm detail page => event tab (Add events associated with pvc)
4.  Add pvc's recent events

HARVESTSER: pvc state enhancement

---

models/harvester/persistentvolumeclaim.js

https://github.com/harvester/harvester/issues/1346
- Adjusting resizing state priority

HARVESTSER: fix volume state

---

mixins/harvester-vm/impl.js
mixins/harvester-vm/index.js

- https://github.com/harvester/harvester/issues/1833

HARVESTSER: fix opensuse qga

---

edit/harvesterhci.io.virtualmachinebackup.vue

- https://github.com/harvester/harvester/issues/1027

HARVESTSER: restore supports restoring to the specified namespace

---

edit/harvesterhci.io.virtualmachinebackup.vue

- https://github.com/harvester/harvester/issues/1027

HARVESTSER: fix restore existing vm case

---

assets/translations/en-us.yaml
config/harvester-map.js
config/labels-annotations.js
config/settings.js
detail/harvesterhci.io.virtualmachinebackup/index.vue
edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/harvesterhci.io.volume.vue
edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/DataTemplate.vue
edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/base.vue
edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/container.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/impl.js
mixins/harvester-vm/index.js
models/harvester/harvesterhci.io.virtualmachineimage.js
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1824

HARVESTSER: fix scheduler multi vm

---

components/formatter/HarvesterIpAddress.vue
detail/harvesterhci.io.host/VirtualMachineInstance.vue

1. 
https://user-images.githubusercontent.com/24985926/154926743-d5c895fa-8943-4ee3-aa6f-038f213dc79a.mov
2.

HARVESTSER: fix style

---

assets/translations/en-us.yaml
components/ActionMenu.vue
components/Collapse.vue
components/HarvesterUpgradeProgressBarList.vue
components/nav/HarvesterUpgrade.vue
components/nav/Header.vue
config/labels-annotations.js
config/types.js
list/harvesterhci.io.dashboard/HarvesterUpgrade.vue
list/harvesterhci.io.setting.vue
models/harvester/harvesterhci.io.setting.js
models/harvester/harvesterhci.io.upgrade.js
models/harvester/harvesterhci.io.virtualmachineimage.js
pages/c/_cluster/harvester/airgapupgrade/index.vue
store/index.js

- https://github.com/harvester/harvester/issues/1852
- Add upgrade related version information
- When the upgrade is successful, the upgrade related messages will not disappear automatically， you need to click the `Dismiss it` button to close the window after a successful upgrade. (After clicking on it, the user will not see the information related to this upgrade again)

Upgrade enhancement

---

components/VMConsoleBar.vue
components/formatter/HarvesterVmState.vue
detail/kubevirt.io.virtualmachine/index.vue
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1925

HARVESTSER: fix vm state

---

models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1928

HARVESTSER: delete console.error

---

models/harvester/kubevirt.io.virtualmachine.js

- [https://github.com/harvester/harvester/issues/1702](https://github.com/harvester/harvester/issues/1702)

HARVESTER: restart/stop vm error message enhancement

---

models/harvester/harvesterhci.io.upgrade.js

`nodesUpgraded` => `NodesUpgraded`

HARVESTSER: fix typo

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/harvester-map.js
config/labels-annotations.js
detail/kubevirt.io.virtualmachine/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineAccessCredentials/AccessCredentialsUsers.vue
edit/kubevirt.io.virtualmachine/VirtualMachineAccessCredentials/index.vue
edit/kubevirt.io.virtualmachine/VirtualMachineAccessCredentials/type/basicAuth.vue
edit/kubevirt.io.virtualmachine/VirtualMachineAccessCredentials/type/sshkey.vue
edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/impl.js
mixins/harvester-vm/index.js
models/harvester/kubevirt.io.virtualmachine.js

- [https://github.com/harvester/harvester/issues/1538](https://github.com/harvester/harvester/issues/1538)
- Use random string to rename the modal of VirtualMachineSSHKey.vue

Implement VM Access Credentials

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/product/harvester.js
config/settings.js
config/types.js
edit/harvesterhci.io.managedchart/index.vue
edit/harvesterhci.io.managedchart/rancher-monitoring.vue
edit/harvesterhci.io.setting/index.vue
list/harvesterhci.io.setting.vue
models/harvester/management.cattle.io.managedchart.js

- [https://github.com/harvester/harvester/issues/1531](https://github.com/harvester/harvester/issues/1531)

HARVESTER: prometheus configuration

---

assets/translations/en-us.yaml
models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/1346

HARVESTSER: add cancelExpand to volume page

---

edit/kubevirt.io.virtualmachine/VirtualMachineAccessCredentials/AccessCredentialsUsers.vue
edit/kubevirt.io.virtualmachine/VirtualMachineAccessCredentials/type/sshkey.vue
edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue

- [https://github.com/harvester/harvester/issues/1961](https://github.com/harvester/harvester/issues/1961)
- add prop of searchable on SSHKEY, defaults to true.

HARVESTER: search is disable on accessCredentials

---

store/index.js

- https://github.com/harvester/harvester/issues/1962

HARVESTER: fix member role don"t find upgrade cr

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
models/harvester/kubevirt.io.virtualmachine.js

- [https://github.com/harvester/harvester/issues/574](https://github.com/harvester/harvester/issues/574)

HARVESTER: add softreboot action

---

models/harvester/kubevirt.io.virtualmachine.js

Hide this message when vm starts

HARVESTER: hide pod message

---

edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/kubevirt.io.virtualmachine/index.vue
models/harvester/harvesterhci.io.virtualmachinetemplate.js

- https://github.com/harvester/harvester/issues/1968

HARVESTER: fixed set defaultVerion

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
edit/kubevirt.io.virtualmachine/VirtualMachineAccessCredentials/AccessCredentialsUsers.vue

- [https://github.com/harvester/harvester/issues/1967](https://github.com/harvester/harvester/issues/1967)

HARVESTER: cover access credentials edge case

---

assets/translations/en-us.yaml
edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/impl.js
mixins/harvester-vm/index.js
models/harvester/harvesterhci.io.virtualmachinetemplateversion.js
models/harvester/kubevirt.io.virtualmachine.js

**Issue**
- https://github.com/harvester/harvester/issues/1767
**Change**
- Add a checkbox named "Booting in EFI mode", default value is false
- Check will add `spec?.template?.spec?.domain?.features?.smm?.enabled` and `spec?.template?.spec?.domain?.firmware?.bootloader?.efi?.secureBoot` to be true
**Verify Steps**
Test ubuntu will be easier than windows
For ubuntu:
1. Go to Create VM page, use iso template
2. Configure 4c8g, select ubuntu-desktop iso.(https://releases.ubuntu.com/20.04.4/ubuntu-20.04.4-desktop-amd64.iso)
3. Click the "Advanced options" tab, and check the "Booting in EFI mode" checkbox
4. Click the "Create" button
5. Waiting for VM ready, and then open VNC console
6. Install Ubuntu using the custom option
7. Setup UEFI System (refer to [6b: Manual …

HARVESTER: Add "Booting in EFI mode" Option for VM

---

edit/harvesterhci.io.managedchart/rancher-monitoring.vue
models/harvester/management.cattle.io.managedchart.js

[https://github.com/harvester/harvester/issues/1531](https://github.com/harvester/harvester/issues/1531)

HARVESTER: add Prometheus configuration validation

---

detail/kubevirt.io.virtualmachine/VirtualMachineTabs/VirtualMachineKeypairs.vue
edit/network.harvesterhci.io.clusternetwork/vlan.vue
models/harvester/harvesterhci.io.virtualmachinebackup.js

HARVESTER: add icon

---

assets/translations/en-us.yaml
config/labels-annotations.js
edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/index.js

- [https://github.com/harvester/harvester/issues/1730](https://github.com/harvester/harvester/issues/1730)

HARVESTER: add reservedMemory configuration

---

edit/harvesterhci.io.volume.vue
models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/1977

HARVESTER: delete metadata when clone volume

---

config/labels-annotations.js
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
mixins/harvester-vm/index.js
models/harvester/persistentvolumeclaim.js

- [https://github.com/harvester/harvester/issues/1695](https://github.com/harvester/harvester/issues/1695)
1. Create a VM that exceed the storage capacity, e.g. 100T
2. Volume tab on the VM detail page should display `Insufficient Storage`
3. The Volume column on Volume List Page should display `Insufficient Storage`

HARVESTER: display the Insufficient Storage message of pvc

---

mixins/harvester-vm/impl.js
mixins/harvester-vm/index.js

When creating a vm, using the following yaml as cloud-init, the page will report an error
```
#cloud-config
hostname: test1-pool1-82508d7f-lvqh4
package_update: true
packages:
- qemu-guest-agent
runcmd:
- - systemctl
- enable
- --now
- qemu-guest-agent
- sh /usr/local/custom_script/install.sh
set_hostname:
- test1-pool1-82508d7f-lvqh4
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDi8PnotHdPz01aJHy/29IkYWHUydh88dC6GKdot2Wyz9EyCUhx61wxbR7US+UX/0f9rjhNV4Oq1fIxf98uTOxxPE6xYqMgRMUdzLETLu1EeKsTuH+la41RjP5yStV4kIUcO3PTs0yVNP/MEBi2vXB0RRpfjSSqkTlhp3IStnSAYSxjkCL8lGj29HRdH1K/yUogaBNF6zjquTEHqYEWWWDWxdneSZ/2Ygaw9ldyGePEKI9Ngc6IJPJoVZGUaI24aEyGSRrwd41O+QDTnppxK+JoHBm948FcJuWGKxHvY2z8o7xTSWdIRzaMaRwwDH5VlANSSH1PqyVInmn+g47I7FgP
write_files:
- content: …
```

HARVESTER: fix vm cloudinit runcmd error

---

models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/1987

HARVESTER: fix vm paused state message tip

---

assets/translations/zh-hans.yaml

In Chinese mode  => vm advanced  options =>  user Data template => click select template (create a new userData template)

HARVESTER: fix error translation

---

assets/translations/zh-hans.yaml
mixins/harvester-vm/impl.js

https://github.com/rancher/dashboard/pull/5342

HARVESTER: fix comment

---

assets/translations/en-us.yaml
components/nav/HarvesterUpgrade.vue
models/harvester/harvesterhci.io.upgrade.js
plugins/steve/resource-class.js

- https://github.com/harvester/harvester/issues/1852

HARVESTER: upgrade enhancement

---

components/GrowlManager.vue

- https://github.com/harvester/harvester/issues/2117

HARVESTER: fix growl message style

---

assets/translations/en-us.yaml
config/settings.js

- https://github.com/harvester/harvester/issues/2091

HARVESTER: add release-download-url setting

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
components/GrowlManager.vue
config/harvester-map.js
edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/index.js
models/harvester/harvesterhci.io.virtualmachinetemplateversion.js
models/harvester/kubevirt.io.virtualmachine.js
models/harvester/kubevirt.io.virtualmachineinstance.js

- https://github.com/harvester/harvester/issues/2060

HARVESTER: use runStrategy replace running

---

components/nav/HarvesterUpgrade.vue

- https://github.com/harvester/harvester/issues/2145

HARVESTER: fix upgrade image display error

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
edit/harvesterhci.io.virtualmachinetemplateversion.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/impl.js
mixins/harvester-vm/index.js
models/harvester/harvesterhci.io.virtualmachinetemplateversion.js
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/2128

HARVESTER: fix efi

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/labels-annotations.js
models/harvester/node.js

- https://github.com/harvester/harvester/issues/1683

HARVESTER: node ip tip

---

edit/harvesterhci.io.host/index.vue
models/harvester/harvesterhci.io.blockdevice.js
models/harvester/node.js

**Link issue**
- https://github.com/harvester/harvester/issues/1970
- https://github.com/harvester/harvester/issues/1948
- https://github.com/harvester/harvester/issues/1976
**Change**
- Disable the last host can be deleted
- Disable partitioned disk can be added
- Use the block device name as the disk name

HARVESTER: Fix host and disk issues

---

components/form/KeyValue.vue
config/labels-annotations.js
edit/harvesterhci.io.virtualmachineimage.vue
edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
mixins/harvester-vm/index.js
models/harvester/harvesterhci.io.virtualmachineimage.js
pages/c/_cluster/harvester/airgapupgrade/index.vue
utils/custom-validators.js
utils/validators/vm-image.js

- https://github.com/harvester/harvester/issues/2057

HARVESTER: fix auto choose cd-rom issue

---

list/kubevirt.io.virtualmachine.vue

- https://github.com/harvester/harvester/issues/2020

HARVESTER: node sort

---

models/harvester/kubevirt.io.virtualmachine.js
models/harvester/kubevirt.io.virtualmachineinstance.js

- https://github.com/harvester/harvester/issues/2020

HARVESTER: sort fix

---

components/formatter/HarvesterIpAddress.vue
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/2154
Enhancement method： When vm stop, UI hide IP information

HARVESTER: hide ip when vm stop

---

edit/harvesterhci.io.virtualmachineimage.vue
models/harvester/harvesterhci.io.virtualmachineimage.js
utils/custom-validators.js
utils/validators/vm-image.js

- https://github.com/harvester/harvester/issues/2158#issuecomment-1101133032

HARVESTER: delete image label limitation

---

models/harvester/node.js

- https://github.com/harvester/harvester/issues/1683

HARVESTER: node page infinity render

---

edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/DataTemplate.vue
edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/index.js

- https://github.com/harvester/harvester/issues/2002

HARVESTER: qemu-guest-agent enhancement

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
config/product/harvester.js
edit/harvesterhci.io.managedchart/rancher-monitoring.vue
edit/harvesterhci.io.setting/index.vue
models/harvester/management.cattle.io.managedchart.js

- [https://github.com/harvester/harvester/issues/2075](https://github.com/harvester/harvester/issues/2075)
1. Go to Setting List
2. Go to Harvester Monitoring Edit page
3. Prometheus node exporter configuration works fine
4. Back to Setting List, json of Harvester Monitoring should be changed

HARVESTER: add prometheus-node-exporter configuration

---

detail/harvesterhci.io.host/index.vue
edit/harvesterhci.io.host/HarvesterDisk.vue
edit/harvesterhci.io.host/index.vue
models/harvester/harvesterhci.io.blockdevice.js

**Issues**
- https://github.com/harvester/harvester/issues/2149
- https://github.com/harvester/harvester/issues/1936
**Verify Steps**
1. Go to the host edit page
2. Click disks tabs and add a disk
3. Check the drop menu name
4. Select a disk and click.
5. Check the mount path
6. Click save and check the mount path of the request body
7. Check disk name of the edit page and detail page

HARVESTER: Show the device name of status && Mount point change

---

components/formatter/HarvesterIpAddress.vue
models/harvester/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/2067

HARVESTER: filter vm ip

---

components/VMConsoleBar.vue

- https://github.com/harvester/harvester/issues/2170

HARVESTER: fix page freeze

---

list/harvesterhci.io.dashboard/index.vue

Fix volume statistics, memory spelling error

HARVESTER: fix dashboard page bug

---

store/index.js

Fixes #
https://github.com/rancher/dashboard/pull/5319

fix fetch management.cattle.io.cluster race error

---

assets/translations/en-us.yaml
assets/translations/zh-hans.yaml
edit/kubevirt.io.virtualmachine/index.vue
mixins/harvester-vm/index.js
models/harvester/harvesterhci.io.virtualmachinetemplateversion.js
models/harvester/kubevirt.io.virtualmachine.js

change runStrategy:  `Manual` => `RerunOnFailure`
delete `start vm on creation` checkbox
Fixes # https://github.com/harvester/harvester/issues/2172

HARVESTER: change vm runStrategy

---

edit/harvesterhci.io.host/index.vue

Fixes #
- https://github.com/harvester/harvester/issues/2149
Make remove button is disabled on the detail page

Harvester: Fix disk detail config can be remove

---

edit/harvesterhci.io.setting/backup-target.vue

HARVESTER: fix link error

---

edit/harvesterhci.io.setting/overcommit-config.vue
models/harvester/kubevirt.io.virtualmachine.js

fix when creating a vm, the `Off` status will be displayed for a long time.   
Fixes #
- https://github.com/harvester/harvester/issues/2221

HARVESTER: Enhanced vm off state logic

---

models/harvester/harvesterhci.io.virtualmachinebackup.js

Fixes # 
- https://github.com/harvester/harvester/issues/2247

HARVESTER: fix error title

---

components/formatter/HarvesterVmState.vue

Fixes #  
- https://github.com/harvester/harvester/issues/2288

HARVESTER: multiCluster vlan tip enhancement

---

list/harvesterhci.io.setting.vue

Enhance the user experience of setting list search

HARVESTER: sort setting

---

components/GrafanaDashboard.vue

Fixes #
- https://github.com/harvester/harvester/issues/2150

HARVESTER: enhancement grafana reload

---

edit/harvesterhci.io.keypair.vue
edit/harvesterhci.io.virtualmachinebackup.vue
edit/harvesterhci.io.volume.vue
edit/kubevirt.io.virtualmachine/index.vue

Fixed the footer style of edit page.
old:
new: 
Fixes #

HARVESTER: fixed edit footer style

---

shell/edit/kubevirt.io.virtualmachine/VirtualMachineCpuMemory.vue

Fixes problems caused by modifications to the UnitInput component
https://github.com/rancher/dashboard/pull/6107
Fixes #

HARVESTER: fix unitIput component data sync

---

shell/list/namespace.vue
shell/pages/c/_cluster/_product/projectsnamespaces.vue
shell/store/index.js

Fixes #
- https://github.com/harvester/harvester/issues/2351

[backport v1.0.3] fix namespace filter

---

shell/components/formatter/HarvesterIpAddress.vue

Fixes # 
- https://github.com/harvester/harvester/issues/2032

HARVESTER: enhanced ip display

---

shell/components/formatter/HarvesterIpAddress.vue

Fixes # 
- https://github.com/harvester/harvester/issues/2350

[backport v1.0.3] HARVESTER: enhanced ip display

---

shell/components/formatter/HarvesterVmState.vue
shell/store/index.js

Fixes #
- https://github.com/harvester/harvester/issues/2288

HARVESTER: fix multi-cluster auth bug

---

shell/list/harvesterhci.io.virtualmachinetemplateversion.vue
shell/models/harvester/harvesterhci.io.virtualmachinetemplateversion.js

this is a backport pr https://github.com/harvester/dashboard/pull/330
Fixes #

[backport]delete defaultversion

---

shell/list/harvesterhci.io.virtualmachinetemplateversion.vue
shell/models/harvester/harvesterhci.io.virtualmachinetemplateversion.js

If it is the default version, the delete button is not displayed
Fixes #
- https://github.com/harvester/harvester/issues/2376

HARVESTER: disable delete  defaultVersion

---

shell/edit/harvesterhci.io.virtualmachinetemplateversion.vue

Fixes #
test step:
1. create vm template
2. modify template  (page crash)
3.

HARVESTER: fix vm template bug

---

shell/edit/harvesterhci.io.virtualmachinetemplateversion.vue

This is a backport pr https://github.com/harvester/dashboard/pull/329
Fixes #
test step:
1. create vm template
2. modify template  (page crash)

[backport]HARVESTER: fix vm template bug

---

shell/list/harvesterhci.io.host/index.vue

Per https://github.com/harvester/harvester/issues/1700#issuecomment-1144346302 show used gauge on node overview page
- https://github.com/harvester/harvester/issues/1700
- https://github.com/harvester/harvester/issues/2347

HARVESTER: Show used gauge on node overview page

---

shell/components/SortableTable/index.vue
shell/list/kubevirt.io.virtualmachine.vue

This is a backport pr https://github.com/harvester/dashboard/pull/335

Backport style

---

shell/store/index.js

Fixes #
- https://github.com/harvester/harvester/issues/2394

HARVESTER: fix access to api without permission

---

shell/store/index.js

This is backport issue https://github.com/harvester/harvester/issues/2395
Fixes #

[backport] auth bug

---

shell/models/harvester/kubevirt.io.virtualmachine.js
shell/models/harvester/persistentvolumeclaim.js

Fix the problem of error reported by clone vm and volume
Fixes #

HARVESTER: fix clone issue

---

shell/models/harvester/kubevirt.io.virtualmachine.js
shell/models/harvester/persistentvolumeclaim.js

This is a backport pr https://github.com/harvester/dashboard/pull/338
Fixes #

[backport]HARVESTER: fix clone issue

---

Dockerfile

node12 => node14

---

shell/edit/harvesterhci.io.host/index.vue
shell/models/harvester/node.js

Fixes editing host system labels will throw an error
- https://github.com/harvester/harvester/issues/2383
- Allow `topology.kubernetes.io/zone` and `topology.kubernetes.io/region` to show in UI
- Fix edit an exist system label will throw error
Host labels CRUD

[Backport] HARVESTER: Fix edit host system labels

---

shell/models/harvester/harvesterhci.io.virtualmachinetemplateversion.js

- https://github.com/harvester/harvester/issues/2357
1. Create a VM template
2. You can find out `evictionStrategy` in yaml

Harvester: Fix missing liveMigrate

---

shell/models/harvester/harvesterhci.io.virtualmachinetemplateversion.js

This is a backport PR: https://github.com/harvester/dashboard/pull/352
- https://github.com/harvester/harvester/issues/2414

[Backport]Harvester: Fix missing liveMigrate

---

shell/assets/translations/en-us.yaml
shell/assets/translations/zh-hans.yaml
shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
shell/mixins/harvester-vm/index.js
shell/utils/validators/vm.js

This is a backport PR: https://github.com/harvester/dashboard/pull/349
- https://github.com/harvester/harvester/issues/2421

[Backport]Harvester: Image volume can be empty in VM template

---

shell/edit/harvesterhci.io.setting/overcommit-config.vue

HARVESTER: change input event

---

shell/assets/translations/en-us.yaml
shell/assets/translations/zh-hans.yaml
shell/edit/kubevirt.io.virtualmachine/index.vue

- https://github.com/harvester/harvester/issues/2415
1. Create a VM
2. Go to VM edit page
3. Restart button below the form should be visible
4. Stop VM
5. Go to VM edit page
6. Start button below the form should be visible

Harvester: VM restart/start enhancement

---

shell/assets/translations/en-us.yaml
shell/assets/translations/zh-hans.yaml
shell/edit/kubevirt.io.virtualmachine/index.vue

This is a backport PR: https://github.com/harvester/dashboard/pull/358
- https://github.com/harvester/harvester/issues/2416

[Backport]Harvester: VM restart/start enhancement

---

shell/assets/translations/en-us.yaml
shell/components/GrowlManager.vue
shell/models/harvester/node.js
shell/plugins/steve/subscribe.js
shell/store/growl.js
shell/utils/socket.js

backport of https://github.com/harvester/dashboard/pull/348

[backport] websocket disconnect growl

---

shell/assets/translations/en-us.yaml
shell/components/form/NodeScheduling.vue
shell/components/nav/Header.vue
shell/edit/harvesterhci.io.virtualmachinetemplateversion.vue
shell/edit/kubevirt.io.virtualmachine/index.vue

Fixes VM template is not working with Node scheduling
- https://github.com/harvester/harvester/issues/2244
- Add node scheduling for template
- Add validate for node scheduling node name

HARVESTER: VM template is not working with Node scheduling

---

shell/assets/translations/en-us.yaml
shell/assets/translations/zh-hans.yaml
shell/components/FilterLabel.vue
shell/components/form/ArrayList.vue
shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
shell/list/harvesterhci.io.virtualmachineimage.vue
shell/machine-config/harvester.vue
shell/mixins/labeled-form-element.js
shell/utils/width.js

Fixes #
https://github.com/harvester/harvester/issues/2319
test step:
case 1: 
1. The image list page can be filtered by label
case 2:
2.  The image selection box on the vm creation page is searchable.
case 3:   multi-cluster
1.  The image selection box on the harvester node driver page is searchable.

HARVESTER: filter image label

---

shell/assets/translations/en-us.yaml
shell/components/form/NodeScheduling.vue
shell/components/nav/Header.vue
shell/edit/harvesterhci.io.virtualmachinetemplateversion.vue
shell/edit/kubevirt.io.virtualmachine/index.vue

Fixes VM template is not working with Node scheduling
- https://github.com/harvester/harvester/issues/2451
- Add node scheduling for template
- Add validate for node scheduling node name

[Backport] HARVESTER: VM template is not working with Node scheduling

---

shell/models/harvester/kubevirt.io.virtualmachineinstance.js

Fixes #
- https://github.com/harvester/harvester/issues/2465
test step
1. create a vm
2. stop this vm
3. You should see an intermediate state （ stopping）

HARVESTER: vm state enhancement

---

shell/models/harvester/kubevirt.io.virtualmachineinstance.js

Fixes #
- https://github.com/harvester/harvester/issues/2471
test step
1. create a vm
2. stop this vm
3. You should see an intermediate state （ stopping）

[backport v1.0.3] HARVESTER: vm state enhancement

---

shell/assets/translations/en-us.yaml
shell/assets/translations/zh-hans.yaml
shell/components/FilterLabel.vue
shell/components/form/ArrayList.vue
shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
shell/list/harvesterhci.io.virtualmachineimage.vue
shell/machine-config/harvester.vue
shell/mixins/labeled-form-element.ts
shell/utils/width.js

Fixes #
- https://github.com/harvester/harvester/issues/2319
- https://github.com/harvester/harvester/issues/2174
test step:
case 1: 
1. The image list page can be filtered by label
case 2:
2.  The image selection box on the vm creation page is searchable.
case 3:   multi-cluster
1.  The image selection box on the harvester node driver page is searchable.

HARVESTER: filter labels

---

shell/assets/translations/en-us.yaml
shell/components/FilterLabel.vue
shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
shell/list/harvesterhci.io.virtualmachineimage.vue

Remove unused code
- https://github.com/harvester/dashboard/pull/369

HARVESTER: Remove unused code

---

shell/models/harvester/kubevirt.io.virtualmachine.js

Fixes #
- https://github.com/harvester/harvester/issues/2471

HARVESTER: fix poweroff vm state

---

shell/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/DataTemplate.vue
shell/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue
shell/mixins/harvester-vm/index.js

Fixes #
- https://github.com/harvester/harvester/issues/2488

HARVESTER: Fix cloud-config undefined，enhancement window OS case

---

shell/components/formatter/HarvesterDiskState.vue
shell/detail/harvesterhci.io.host/HarvesterHostDisk.vue
shell/edit/harvesterhci.io.host/HarvesterDisk.vue
shell/mixins/harvester-disk.js
shell/models/harvester/node.js

Fixes Hosts page showing incorrect Disk State
- https://github.com/harvester/harvester/issues/2478
- API Changed
- Host edit/detail page
- Host list page

HARVESTER: Fix Hosts page showing incorrect Disk State

---

shell/list/harvesterhci.io.dashboard/index.vue

Fixes storage used on dashboard page
- https://github.com/harvester/harvester/issues/2478

HARVESTER: Fix storage used on dashboard page

---

shell/components/form/NodeAffinity.vue
shell/components/form/PodAffinity.vue
shell/machine-config/harvester.vue

- https://github.com/harvester/harvester/issues/2316

Harvester: add the configuration of node/pod scheduling on Harvester node driver(RKE2)

---

shell/components/form/NodeAffinity.vue
shell/components/form/PodAffinity.vue
shell/machine-config/harvester.vue

- https://github.com/harvester/harvester/issues/2384
This is a backport PR: https://github.com/harvester/dashboard/pull/381

[Backport]Harvester: add the configuration of node/pod scheduling on Harvester node driver(RKE2)

---

shell/assets/translations/en-us.yaml
shell/assets/translations/zh-hans.yaml
shell/components/form/NodeAffinity.vue
shell/components/form/PodAffinity.vue
shell/machine-config/harvester.vue

- https://github.com/harvester/harvester/issues/2316

Harvester: Harvester node driver with external credentials enhancement

---

shell/models/harvester/harvesterhci.io.virtualmachineimage.js

Fixes #
- https://github.com/harvester/harvester/issues/2562

HARVESTER: fix image clone miss label

---

shell/assets/translations/en-us.yaml
shell/components/dialog/harvester/ExportImageDialog.vue
shell/models/harvester/harvesterhci.io.virtualmachineimage.js
shell/utils/custom-validators.js
shell/utils/validators/vm-image.js

Fixes #
- https://github.com/harvester/harvester/issues/2563
test step:
1.   The name filled in the created image should match the definition of R1123  https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

HARVESTER: validate image displayName

---

shell/edit/harvesterhci.io.setting/index.vue
shell/edit/management.cattle.io.setting.vue

Fixes #
- https://github.com/harvester/harvester/issues/2569

HARVESTER: prevent submit

---

shell/edit/kubevirt.io.virtualmachine/index.vue

- https://github.com/harvester/harvester/issues/2577
1. Create VM template with `EFI booting mode` & `Node scheduling`
2. Use the template to create multiple VM instances
3. EFI mode and node scheduling should be included in each one

Harvester: fix override when saving multiple VMs

---

shell/assets/translations/en-us.yaml
shell/components/CruResource.vue
shell/components/ResourceDetail/Masthead.vue
shell/components/dialog/harvester/ExportImageDialog.vue
shell/edit/harvesterhci.io.setting/index.vue
shell/edit/management.cattle.io.setting.vue
shell/models/harvester/harvesterhci.io.virtualmachineimage.js
shell/plugins/i18n.js
shell/utils/custom-validators.js
shell/utils/validators/vm-image.js

Fixes #
- https://github.com/harvester/harvester/issues/2563#issuecomment-1196320939

HARVESTER: delete displayName RFC1123 validations

---

shell/edit/harvesterhci.io.virtualmachinetemplateversion.vue
shell/edit/kubevirt.io.virtualmachine/VirtualMachineReserved.vue
shell/edit/kubevirt.io.virtualmachine/index.vue
shell/mixins/harvester-vm/index.js

Fixes reserved memory edit issue
- https://github.com/harvester/harvester/issues/2589
~~When the VM page is updated, the unit input is also updated, which will show the last value instead of the value that is being delayed input.~~

Harvester: Fix reserved memory edit issue

---

shell/mixins/harvester-vm/index.js

Fixes #
- https://github.com/harvester/harvester/issues/2593

HARVESTER: fix template OSType not automatically filled

---

shell/components/form/PodAffinity.vue
shell/machine-config/harvester.vue

- https://github.com/harvester/harvester/issues/2567
- https://github.com/harvester/harvester/issues/2598

Harvester: typology field is inputable if get nodes failed

---

shell/list/harvesterhci.io.setting.vue

Fixes #
- https://github.com/harvester/dashboard/pull/314

[backport v1.0] HARVESTER: sort setting list

---

shell/components/form/PodAffinity.vue
shell/machine-config/harvester.vue

- https://github.com/harvester/harvester/issues/2598

Harvester: move harvester specific code out of PodAffinity

---

shell/assets/translations/en-us.yaml
shell/components/dialog/harvester/DeepCloneVmDialog.vue
shell/edit/kubevirt.io.virtualmachine/index.vue
shell/mixins/harvester-vm/index.js
shell/models/harvester/kubevirt.io.virtualmachine.js

Fixes #
- https://github.com/harvester/harvester/issues/569
Clicking on the `Clone` button will clone the data inside the vm, 
clicking on the `Clone template` button will only create a new vm via yaml and will not preserve the previous data.
step:
case 1: 
1. Create a vm named `test`
2. Login to the VM and add a file test.txt with content 123.
3. To clone this VM, the name is `test-deep-Clone`
4. Login to the `test-deep-Clone` VM and  the `test.txt` file should exist and contain 123.
case 2:
1.  Use `test-deep-clone` to clone a new VM that also contains test.txt
case 3:  
1. Click `Clone template` in the `test-deep-Clone` menu to create a new VM that does not contain the test.txt file
case 4:
1. Click `Generate Template` in the `test-deep-Clone` menu to Generate a Template that will be …

HARVESTER: add deep clone vm

---

shell/models/harvester/harvesterhci.io.setting.js

Fixes #
- https://github.com/harvester/harvester/issues/2510

HARVESTER: add cluster-registration-url message

---

shell/models/harvester/node.js

- https://github.com/harvester/harvester/issues/2628
1. prepare a harvester cluster with single node
2. Go to Host list
3. Click `cordon` action
4. You should get an error from webhook

Harvester: catch host cordon errors

---

shell/utils/validators/setting.js

- https://github.com/harvester/harvester/issues/2618#issuecomment-1220399785
Fixes #
- https://github.com/harvester/harvester/issues/2618

HARVESTER: set backupTarget s3 endpoint is optional

---

shell/edit/kubevirt.io.virtualmachine/index.vue
shell/mixins/harvester-vm/impl.js
shell/mixins/harvester-vm/index.js
shell/models/harvester/kubevirt.io.virtualmachine.js

Fixes #
- https://github.com/harvester/harvester/issues/2503
- https://github.com/harvester/harvester/issues/2584
case 1:
1.  https://github.com/harvester/harvester/issues/2584#issue-1319636738
case 2: 
1. templates, and backup-related features also need to be tested

HARVESTER: support save cloudInit as clear text

---

shell/components/formatter/HarvesterStorageUsed.vue
shell/detail/harvesterhci.io.host/HarvesterHostBasic.vue
shell/list/harvesterhci.io.dashboard/index.vue
shell/models/harvester/longhorn.io.node.js

Fixes storage allowScheduling issue
- https://github.com/harvester/harvester/issues/2622
- The schedulable should decide by `longhornNode.spec.allowScheduling` and `disk.allowScheduling`

HARVESTER: Fix storage allowScheduling issue

---

shell/assets/translations/en-us.yaml
shell/components/dialog/harvester/CloneVmDialog.vue
shell/models/harvester/kubevirt.io.virtualmachine.js

Fixes #
- https://github.com/harvester/harvester/issues/1374
In order to make it clear to the user that we provide two clone VM methods, we put the clone operation together and let the user choose
test step:
1.   click `Clone` button
2.  Select whether you want to clone the data in the pop-up mode box,
3. By default, this checkbox is checked to clone the data in the volume，Otherwise, just create a new VM with the same configuration.

HARVESTER: merge clone & cloneTemplate

---

shell/mixins/harvester-vm/index.js

Fixes # 
- https://github.com/harvester/harvester/issues/2584

HARVESTER: fix use two type to save cloudInit

---

shell/models/harvester/harvesterhci.io.virtualmachineimage.js

Allowing users to download backing images
- https://github.com/harvester/harvester/issues/1436
- Add download action

HARVESTER: Allowing users to download backing images

---

.drone.yml
shell/scripts/build-pkg.sh
shell/scripts/drone-build-pkg.sh

add harvester plugin drone CI

---

pkg/harvester/models/namespace.js

Fix extend namespace class

---

pkg/harvester/config/settings.js
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

add `ui-plugin-index` setting
Fixes #
- https://github.com/harvester/harvester/issues/2654

HARVESTER: add ui-plugin-index in setting page

---

pkg/harvester/components/FilterLabel.vue

Fixes #
- https://github.com/harvester/harvester/issues/2319#issuecomment-1246421473

HARVESTER: fix image filter

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue

Fixes # 
- https://github.com/harvester/harvester/issues/2631
- https://github.com/harvester/tests/issues/466

HARVESTER: add backup healthy check

---

pkg/harvester/config/harvester-map.js
pkg/harvester/config/harvester.js
pkg/harvester/config/table-headers.js
pkg/harvester/dialog/PvcCloneDialog.vue
pkg/harvester/dialog/RestoreSnapshotDialog.vue
pkg/harvester/dialog/SnapshotDialog.vue
pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/edit/harvesterhci.io.volumesnapshot.vue
pkg/harvester/formatters/RelatedVolumeSnapshotCounts.vue
pkg/harvester/formatters/SnapshotTargetVolume.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/list/harvesterhci.io.volumesnapshot.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js
pkg/harvester/models/harvester/snapshot.storage.k8s.io.volumesnapshot.js
pkg/harvester/types.ts

- https://github.com/harvester/harvester/issues/2296
- https://github.com/harvester/harvester/issues/2294
- https://github.com/harvester/harvester/issues/2293

Harvester: Implement Snapshot

---

pkg/harvester/config/harvester.js
pkg/harvester/detail/harvesterhci.io.vmsnapshot/index.vue
pkg/harvester/dialog/HarvesterVMSnapshotDialog.vue
pkg/harvester/edit/harvesterhci.io.vmsnapshot.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/list/harvesterhci.io.vmsnapshot.vue
pkg/harvester/models/harvesterhci.io.virtualmachinebackup.js
pkg/harvester/models/kubevirt.io.virtualmachine.js
pkg/harvester/types.ts

- https://github.com/harvester/harvester/issues/553
take snapshot
snapshot actions menu
restore new vm
restore existing vm

Harvester: Implement VM Snapshot

---

pkg/harvester/dialog/RestoreSnapshotDialog.vue
pkg/harvester/edit/harvesterhci.io.volumesnapshot.vue

HARVESTER: fix reference path error

---

.drone.yml
pkg/harvester/package.json
shell/scripts/drone-build-pkg.sh

HARVESTER: add tag-ci

---

pkg/harvester/edit/harvesterhci.io.volume.vue

- https://github.com/harvester/harvester/issues/2296

Harvester: add filter of volume snapshot on volume page

---

pkg/harvester/config/harvester.js
pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/detail/harvesterhci.io.virtualmachineimage/Storage.vue
pkg/harvester/detail/harvesterhci.io.virtualmachineimage/index.vue
pkg/harvester/dialog/HarvesterExportImageDialog.vue
pkg/harvester/dialog/RestoreSnapshotDialog.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterDisk.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io.vue
pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue
pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
pkg/harvester/formatters/SnapshotTargetVolume.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.storage.vue
pkg/harvester/list/harvesterhci.io.volumesnapshot.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvester/persistentvolumeclaim.js
pkg/harvester/models/harvester/snapshot.storage.k8s.io.volumesnapshot.js
pkg/harvester/models/harvester/storage.k8s.io.storageclass.js
pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
pkg/harvester/types.ts
pkg/harvester/validators/vm.js
shell/assets/translations/en-us.yaml
shell/components/form/LabeledSelect.vue
shell/config/labels-annotations.js
shell/models/harvesterhci.io.management.cluster.js

Support Storage Tiering
- https://github.com/harvester/harvester/issues/2147
- Add Storage class list / edit / detail pages
- Add storage class selector for create volume / create image / create VM -> new volume / export image from volume / restore from snapshot
- Add host tag and disk tag for node edit page
[Storage Class list page]
[Create volume]
[Host and disk tags]

HARVESTER: Storage Tiering

---

pkg/harvester/detail/harvesterhci.io.host/HarvesterKsmtuned.vue
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterKsmtuned.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/types.ts

Fixes #
- https://github.com/harvester/harvester/issues/2302

HARVESTER: add ksmtuned

---

pkg/harvester/dialog/ConfirmRelatedToRemoveDialog.vue

- https://github.com/harvester/harvester/issues/2791

Harvester: remove namespace correctly

---

pkg/harvester/config/harvester.js
pkg/harvester/detail/harvesterhci.io.host/HarvesterHostBasic.vue
pkg/harvester/detail/harvesterhci.io.host/VirtualMachineInstance.vue
pkg/harvester/detail/harvesterhci.io.host/VlanStatus/LinkStatus.vue
pkg/harvester/detail/harvesterhci.io.host/VlanStatus/index.vue
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/detail/network.harvesterhci.io.vlanconfig.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/edit/network.harvesterhci.io.vlanconfig/NodeSelector.vue
pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
pkg/harvester/formatters/HarvesterVmState.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/mixins/harvester-disk.js
pkg/harvester/models/harvester/node.js
pkg/harvester/models/network.harvesterhci.io.vlanconfig.js
pkg/harvester/types.ts
shell/assets/translations/en-us.yaml
shell/components/form/ArrayList.vue
shell/config/labels-annotations.js
shell/models/k8s.cni.cncf.io.networkattachmentdefinition.js

Support VLAN enhancement
- https://github.com/harvester/harvester/issues/2236
- Add network config pages, for now only support VLAN
- Show VLAN status on the node detail page
[Create network config]
[Network config detail]
[Host detail page]

Vlan Enhancement

---

pkg/harvester/components/settings/containerd-registry.vue
pkg/harvester/config/settings.js
pkg/harvester/edit/harvesterhci.io.setting.vue
pkg/harvester/l10n/en-us.yaml

Fixes #
- https://github.com/harvester/harvester/issues/2176

HARVESTER: add rke2 setting

---

pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
pkg/harvester/l10n/en-us.yaml
shell/assets/translations/en-us.yaml

Fix VLAN PR comment
- https://github.com/harvester/dashboard/pull/429

HARVESTER: Fix VLAN PR comment

---

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue

Fix mtu and miimon is not  number
- https://github.com/harvester/harvester/issues/2805
- use `v-model.number`

HARVESTER: Fix mtu and miimon is not  number

---

pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
pkg/harvester/l10n/en-us.yaml

- Improve create new cluster network UX
- Fix host tags not display
- Add placeholder
https://user-images.githubusercontent.com/18737885/191654538-93145453-c116-44d5-bb95-b3fb36b73902.mov

HARVESTER: Improve create new cluster network UX && Fix host tags

---

pkg/harvester/config/settings.js
pkg/harvester/edit/harvesterhci.io.setting.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

The configuration `harvester-monitoring` shouldn't be visible in harvester setting page

Harvester: remove harvester-monitoring on setting pages

---

pkg/harvester/l10n/en-us.yaml

HARVESTER: change text

---

pkg/harvester/mixins/harvester-vm/index.js

Fixes #
- https://github.com/harvester/harvester/issues/2584

HARVESTER: enhancement cloudInit

---

pkg/harvester/config/harvester.js
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/edit/network.harvesterhci.io.vlanconfig/NodeSelector.vue
pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvester/k8s.cni.cncf.io.networkattachmentdefinition.js
shell/assets/translations/en-us.yaml
shell/config/labels-annotations.js

- Fix VLAN can not view detail
- Nav menu change network and backup
- Remove cluster network save logic
- Fix storage missed on host detail page
- Node selector all update
- https://github.com/harvester/harvester/issues/2815

HARVESTER: Fix VLAN can not view detail

---

pkg/harvester/config/harvester.js
shell/components/ResourceTable.vue

Fixes #
- https://github.com/harvester/harvester/issues/2816

HARVESTER: fix projectNamespace group

---

pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterDisk.vue

- Fix Host storage can not see disk status
- https://github.com/harvester/harvester/issues/2822

HARVESTER: Fix Host storage can not see disk status

---

pkg/harvester/list/harvesterhci.io.host.vue

- https://github.com/harvester/harvester/issues/2806

Harvester: console button should be disable if there is no console url

---

pkg/harvester/config/harvester.js
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.logging.clusterflow.vue
pkg/harvester/list/harvesterhci.io.logging.clusteroutput.vue
pkg/harvester/list/harvesterhci.io.logging.flow.vue
pkg/harvester/list/harvesterhci.io.logging.output.vue
shell/edit/logging-flow/Match.vue
shell/edit/logging-flow/index.vue

- https://github.com/harvester/harvester/issues/2750
- https://github.com/harvester/harvester/issues/2817

Harvester: GUI will work properly if crd missed.

---

pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue
pkg/harvester/detail/harvesterhci.io.host/index.vue

HARVESTER: change node tag style

---

shell/assets/styles/global/_select.scss
shell/components/form/LabeledSelect.vue

HARVESTER: fix select style

---

pkg/harvester/list/network.harvesterhci.io.clusternetwork.vue

Fixes groupPreference issue
- When the groupPreference is namespace, the group filter is wrong
[Error]

HARVESTER: Fix groupPreference issue

---

pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue
pkg/harvester/detail/harvesterhci.io.host/index.vue

HARVESTER: hiddle tag when tag is empty

---

pkg/harvester/config/harvester.js
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/network.harvesterhci.io.clusternetwork.vue

Remove Cluster network group option
- https://github.com/harvester/harvester/issues/2841

HARVESTER: Remove Cluster network group option

---

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue

Fix Network Config Creation Issues JSON Unmarshalling
- https://github.com/harvester/harvester/issues/2886

HARVESTER: Fix Network Config Creation Issues JSON Unmarshalling

---

shell/assets/styles/global/_select.scss

Fixes # 
- https://github.com/harvester/harvester/issues/2888

Fix select css

---

pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

HARVESTER: fix typo

---

.github/workflows/test.yaml

remove e2e CI from harvester

---

pkg/harvester/dialog/VolumeCloneDialog.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/2855
1. Create a Volume
2. Go to Volume list page
3. Toggle action menu
4. Click Clone action
5. Clone dialog should be visible
6. The checkbox of `Clone data` should be checked
7. Input name
8. You'll get a cloned Volume
9. Back to step 5
10. Uncheck the checkbox
11. Page will go to Volume create page and fields are filled consistent values

Harvester: Integrate volume clone dialogs

---

pkg/harvester/l10n/en-us.yaml

Fixes #
change `mgmt` description

HARVESTER: change mgmt description

---

shell/models/storage.k8s.io.storageclass.js

Fixes #
- https://github.com/harvester/harvester/issues/2863

HARVESTER: fix set defaultStorage race case

---

pkg/harvester/components/settings/containerd-registry.vue

Fixes #
- https://github.com/harvester/harvester/issues/2874
. 
`IMPORTANT`:  `Auth` values are not returned to the frontend after the user saves them
step:
1. add Mirrors， and fill all required field, 
2. Add config, fill in the `Registry FDQN or IP` field only.
3. save

HARVESTER: fix container-registry setting

---

pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/models/harvesterhci.io.setting.js

Fixes #
If the backuptarge value is empty, the connection status should not be tested on the backup list page。

Backup message enhancement

---

pkg/harvester/dialog/RestartVMDialog.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue

Fixes #
- https://github.com/harvester/harvester/issues/2869
1. Create a vm.
2. Wait for the status of vm switching to running.
3. Edit VM & Click Save
4. The restart warning dialog should be visible
5. Clicking outside of dialog or ESC won't close dialog.
6. Click Save -> The VM will be saved.
7. Click Save & Restart -> The VM will be Saved and then it will be restarted.

Harvester: enhance double check of VM's resource modification

---

pkg/harvester/dialog/MessageBox.vue
pkg/harvester/edit/harvesterhci.io.setting.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
shell/assets/translations/en-us.yaml
shell/assets/translations/zh-hans.yaml

Fixes #
- https://github.com/harvester/harvester/issues/2650#issuecomment-1263318493

HARVESTER: enhancement cluster-registration-url setting

---

pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
shell/models/storage.k8s.io.storageclass.js

Fixes Edit Storage Class Config `Allow Volume Expansion` and `Description`
- https://github.com/harvester/harvester/issues/2921
- https://github.com/harvester/harvester/issues/2926
- https://github.com/harvester/harvester/issues/2928
- `Description` can be edit
- `Allow Volume Expansion` can not be edit
- Delete the default annotation when clone storage class

HARVESTER: Storage bug fix

---

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue

Fixes #
Local uploads of images also need to support automatic matching of `harvesterhci.io/os-type` and `harvesterhci.io/image-type`

HARVESTER: enhancement image

---

pkg/harvester/config/harvester.js
pkg/harvester/edit/harvesterhci.io.addon/index.vue
pkg/harvester/edit/harvesterhci.io.addon/pcidevices-controller.vue
pkg/harvester/edit/harvesterhci.io.addon/vm-import-controller.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/devices.harvesterhci.io.pcidevice.vue
pkg/harvester/list/harvesterhci.io.addon.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvesterhci.io.addon.js
pkg/harvester/types.ts
shell/components/formatter/Translate.vue

Fixes #
- https://github.com/harvester/harvester/issues/2845
- https://github.com/harvester/harvester/issues/2913
test step:
1.  You can turn on and off vm-import and pci's addon in the UI
2. If pci addon is disabled, the PCI device list page only displays a message that jumps to the addon setting page.
3. If addon is enabled, then you should see the corresponding deployment in the harvester-system namespace

HARVESTER: Add addon

---

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue

Fix nic filter errors
Total should always equal with selected nodes length

HARVESTER: Fix nic filter errors

---

pkg/harvester/components/settings/storage-network.vue
pkg/harvester/config/labels-annotations.js
pkg/harvester/config/settings.js
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/models/harvesterhci.io.setting.js

Fixes #
- https://github.com/harvester/harvester/issues/1055

HARVESTER: add storage-network setting

---

pkg/harvester/list/harvesterhci.io.dashboard.vue

Fixes #
- https://github.com/harvester/harvester/issues/2952

HARVESTER: fix network count

---

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/NodeSelector.vue
pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
pkg/harvester/l10n/en-us.yaml

Fixes Reset the NIC input when the NIC does not exist on the selected nodes
- https://github.com/harvester/harvester/issues/2942

HARVESTER: Reset the NIC input when the NIC does not exist on the selected nodes

---

pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io.vue
pkg/harvester/l10n/en-us.yaml

Fix node/disk selector no-options text
- https://github.com/harvester/harvester/issues/2965

HARVESTER: Fix node/disk selector no-options text

---

pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/formatters/NetworkRouteConnectivity.vue
pkg/harvester/list/harvesterhci.io.networkattachmentdefinition.vue
shell/config/labels-annotations.js
shell/models/k8s.cni.cncf.io.networkattachmentdefinition.js

- add UntaggedNetwork type
Fixes #
- https://github.com/harvester/harvester/issues/1618

HARVESTER: add untaggedNetwork type

---

pkg/harvester/l10n/en-us.yaml

Fixes #
- https://github.com/harvester/harvester/issues/1055#issuecomment-1284817187

HARVESTER: add storage-netwokr warning message

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/devices.harvesterhci.io.pcidevice.vue

Fixes #
- https://github.com/harvester/harvester/issues/2994

HARVESTER: fix PCI page RBAC

---

pkg/harvester/mixins/harvester-vm/impl.js
pkg/harvester/mixins/harvester-vm/index.js

If `#cloud-config` is not include in userData, it will be added automatically when `Install guest agent` is checked
Fixes #
- https://github.com/harvester/harvester/issues/2932

HARVESTER: fix miss cloud-config comment

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/CompatibilityMatrix.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/devices.harvesterhci.io.pcidevice.vue

Fixes https://github.com/harvester/harvester/issues/2974 https://github.com/harvester/harvester/issues/2975
* show already-selected PCI devices in VM edit
* disable selecting devices when every instance of the device is in use by other vms

Fix PCI Devices on VM edit; Disable selecting unavailable devices

---

pkg/harvester/config/harvester.js
pkg/harvester/config/settings.js
pkg/harvester/list/harvesterhci.io.storage.vue
shell/models/storage.k8s.io.storageclass.js

Fixes #
- Hide storage create if can not create
- Hide action when can not update
- Allow Rancher to edit ui-source and ui-index that belongs to Harvester.
- https://github.com/harvester/harvester/issues/2993
- https://github.com/harvester/harvester/issues/2996

HARVESTER: Bug fixed

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

HARVESTER: Update Chinese translation

HARVESTER: Update Chinese translation

---

pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/3004

Harvester: only include the snapshots of volume on volume list

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/dialog/EnablePassthrough.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/DeviceList.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.addon.vue
pkg/harvester/models/devices.harvesterhci.io.pcidevice.js
pkg/harvester/models/harvesterhci.io.addon.js

Fixes #
- https://github.com/harvester/harvester/issues/3003#event-7636849452

HARVESTER: enhance enable  pci passthrough button

---

pkg/harvester/l10n/en-us.yaml

HARVESTER: add text space

---

pkg/harvester/list/harvesterhci.io.volume.vue

Fixes #
- https://github.com/harvester/harvester/issues/3020

HARVESTER: fix cluster-member not schema

---

pkg/harvester/package.json

HARVESTER: v1.1.0-rc3 => v1.1.0

---

pkg/harvester/components/HarvesterUpgradeHeader.vue

Fixes #
- https://github.com/harvester/harvester/issues/3056

HARVESTER: fix upgrade UI style

---

pkg/harvester/components/HarvesterUpgradeHeader.vue

Fixes #
- https://github.com/harvester/dashboard/pull/495

[backport v1.1.1] fix upgrade UI style

---

.drone.yml
pkg/harvester/package.json
shell/scripts/drone-build-pkg.sh

fix plugin latest CI

---

pkg/harvester/components/settings/vip-pools.vue
pkg/harvester/l10n/en-us.yaml

Allow input ip ranges in vip-pool setting
- https://github.com/harvester/harvester/issues/3100

HARVESTER: Allow input ip ranges in vip-pool setting

---

pkg/harvester/components/settings/vip-pools.vue
pkg/harvester/l10n/en-us.yaml

Back port of https://github.com/harvester/dashboard/pull/497
- https://github.com/harvester/harvester/issues/3100

[V1.1] HARVESTER: Allow input ip ranges in vip-pool setting

---

shell/pages/prefs.vue

Fixes #
backport pr: https://github.com/harvester/dashboard/pull/503

[backup v1.1] fix typo

---

pkg/harvester/components/settings/backup-target.vue
pkg/harvester/config/settings.js
pkg/harvester/edit/harvesterhci.io.setting.vue
pkg/harvester/models/harvesterhci.io.setting.js
pkg/harvester/validators/setting.js

Fixes #
- https://github.com/harvester/harvester/issues/2986

[backport v1.1]set backup-target default value

---

pkg/harvester/components/settings/backup-target.vue
pkg/harvester/config/settings.js
pkg/harvester/edit/harvesterhci.io.setting.vue
pkg/harvester/models/harvesterhci.io.setting.js
pkg/harvester/validators/setting.js

Fixes #
- https://github.com/harvester/harvester/issues/2986

set backup-target default value

---

pkg/harvester/edit/harvesterhci.io.storage/index.vue

Fixes #
- https://github.com/harvester/harvester/issues/3125

HARVESTER: fix create storageclasses error

---

shell/scripts/drone-build-pkg.sh

Fixes #
- https://github.com/harvester/harvester/issues/3145
Now we will build the following 3 types of harvester-plugin address
1.  master-head:   https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js
2. release:   https://releases.rancher.com/harvester-ui/plugin/harvester-${tag-version}/harvester-${tag-version}.umd.min.js
e.g: https://releases.rancher.com/harvester-ui/plugin/harvester-v1.0.1-rc10/harvester-v1.0.1-rc10.umd.min.js
3.  branch-head:    https://releases.rancher.com/harvester-ui/plugin/harvester-${branch-name}/harvester-${branch-name}.umd.min.js
e.g:  https://releases.rancher.com/harvester-ui/plugin/harvester-release-harvester-v1.1/harvester-release-harvester-v1.1.umd.min.js

HARVESTER: fix harvester plugin rc version

---

shell/scripts/drone-build-pkg.sh

This is a backport pr https://github.com/harvester/dashboard/pull/508
Fixes #

[backport] HARVESTER: fix harvester plugin rc version

---

shell/components/form/Password.vue

Fix password can be edit in detail page

HARVESTER: Fix password can be edit in detail page

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

Fixes #
This is a backport pr https://github.com/harvester/dashboard/pull/510

[backport] Backport network name

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/formatters/HarvesterVolumeState.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvester/persistentvolumeclaim.js
pkg/harvester/validators/index.js
pkg/harvester/validators/vm.js
pkg/harvester/validators/volume.js
shell/config/labels-annotations.js

- https://github.com/harvester/harvester/issues/1695

Harvester: display the error message of insufficient storage volume

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/formatters/HarvesterVolumeState.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvester/persistentvolumeclaim.js
pkg/harvester/validators/index.js
pkg/harvester/validators/vm.js
pkg/harvester/validators/volume.js
shell/config/labels-annotations.js

Original PR: https://github.com/harvester/dashboard/pull/512
- https://github.com/harvester/harvester/issues/1695

[Backport] Harvester: display the error message of insufficient storage volume.

---

pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue

HARVESTER: fix resource path

---

pkg/harvester/pages/c/_cluster/support/index.vue
shell/components/nav/Group.vue

Fixes #
- Alignment Menu
- Fixed font color changing to white when clicking Download KubeConfig,

HARVESTER: enhance menu style

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/pages/c/_cluster/support/index.vue

Original PR: https://github.com/harvester/dashboard/pull/519
- https://github.com/harvester/harvester/issues/2765

[Backport] HARVESTER: add embedded ui of rancher and longhorn ui to support page

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/formatters/HarvesterVolumeState.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js
shell/components/ResourceDetail/Masthead.vue

- https://github.com/harvester/harvester/issues/1695

HARVESTER: add external links to detail/masthead

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/formatters/HarvesterVolumeState.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js
shell/components/ResourceDetail/Masthead.vue

Original PR: https://github.com/harvester/dashboard/pull/523
- https://github.com/harvester/harvester/issues/1695

[Backport] HARVESTER: add external links to detail/masthead

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvester/persistentvolumeclaim.js
shell/components/ResourceDetail/Masthead.vue

- https://github.com/harvester/harvester/issues/3178

HARVESTER: add tooltips for resource external link

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvester/persistentvolumeclaim.js
shell/components/ResourceDetail/Masthead.vue

Original PR: https://github.com/harvester/dashboard/pull/525
- https://github.com/harvester/harvester/issues/3178

[Backport] HARVESTER: add tooltips for resource external link

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

HARVESTER: change placeholder

---

shell/components/CruResourceFooter.vue
shell/components/form/SecretSelector.vue

- https://github.com/harvester/harvester/issues/3184

HARVESTER: find secrets in the accurate store

---

shell/components/CruResourceFooter.vue
shell/components/form/SecretSelector.vue

Original PR: https://github.com/harvester/dashboard/pull/529
- https://github.com/harvester/harvester/issues/3184

[Backport] HARVESTER: find secrets in the accurate store.

---

pkg/harvester/pages/c/_cluster/support/index.vue

Fixes # 
- https://github.com/harvester/harvester/issues/3197

HARVESTER: fix docs link

---

pkg/harvester/pages/c/_cluster/support/index.vue

This is a backport pr:  https://github.com/harvester/dashboard/pull/532
Fixes #

[backport] HARVESTER: fix docs link

---

pkg/harvester/l10n/en-us.yaml
shell/assets/translations/en-us.yaml

Fixes #
- https://github.com/harvester/harvester/issues/3220

HARVESTER: fix i10 error

---

pkg/harvester/l10n/en-us.yaml
shell/assets/translations/en-us.yaml

this is a backport pr: https://github.com/harvester/dashboard/pull/536
Fixes #

[backport] HARVESTER: fix i10 error

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/kubevirt.io.virtualmachine.js

- https://github.com/harvester/harvester/issues/3231

HARVESTER: make the tips of deleting vm accurate

---

.github/pull_request_template.md

When submitting pr, add some necessary checks.
~Fixes #~
~### Occurred changes and/or fixed issues~
~### Technical notes summary~
~### Areas or cases that should be tested~
~### Areas which could experience regressions~
~### Screenshot/Video~

HARVESTER: add pr checklist

---

pkg/harvester/tsconfig.json
pkg/harvester/vue.config.js
shell/pkg/vue.config.js

Workaround: Fix build-pkg error

---

pkg/harvester/models/kubevirt.io.virtualmachine.js

- [] Yes, the relevant RBAC changes are at:~
Fixes #
The `viewLog` action will hide when VM doesn't have pods, e.g. VM is stop
- https://github.com/harvester/harvester/issues/2919

Harvester: Enhance VM viewLogs action

---

README.md

HARVESTER: change README

---

pkg/harvester/config/harvester.js
pkg/harvester/detail/harvesterhci.io.secret.vue
pkg/harvester/edit/harvesterhci.io.secret.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.secret.vue
pkg/harvester/models/harvester/secret.js
pkg/harvester/types.ts

- https://github.com/harvester/harvester/issues/3190
1. Secret should be created/modified/deleted successfully.
2. Go to create a secret.
3. Go to logging output page, the secret just created should be visible in the secret dropdown list of the output.
4. Go to create a secret in the `cattle-logging-system` namespace.
5. Go to clusterOutput page, the secret just created should be visible in the secret dropdown list of the clusterOutput.

HARVESTER: Integrate Secret pages

---

shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue

- https://github.com/harvester/harvester/issues/2798
1. Go to create an alertmanager config.
2. Go to create a receiver with empty name.
3. Should display the error.

HARVESTER: prevent creating receiver with empty name

---

pkg/harvester/models/kubevirt.io.virtualmachine.js

Fixes #
Fix VM view logs action
- https://github.com/harvester/harvester/issues/2919

HARVESTER: Fix VM viewLogs action

---

pkg/harvester/dialog/RestartVMDialog.vue

- https://github.com/harvester/harvester/issues/2915
1. Go to create a vm.
2. Go to edit vm.
3. Footer actions should not be clickable.

HARVESTER: increase z-index of restart modal

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/utils/regular.js
pkg/harvester/utils/vm.js
pkg/harvester/validators/vm.js

Fixes #
- https://github.com/harvester/harvester/issues/2922
- https://github.com/harvester/harvester/issues/2571

HARVESTER: polish message

---

pkg/harvester/detail/harvesterhci.io.host/VirtualMachineInstance.vue

- https://github.com/harvester/harvester/issues/2710
1. Go to Instances on Host detail page.
2. Click cpu/memory sorting actions.
3. Sorting works fine.

HARVESTER: Implement vm sorting on host detail page

---

pkg/harvester/components/DiskTags.vue
pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterDisk.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml

- Host/disk tags use components the same as longhorn UI
- Fix added Disk That Doesn't Have Disk Tag(s) Doesn't Display Storage Information On detail page.
- https://github.com/harvester/harvester/issues/2837
- https://github.com/harvester/harvester/issues/2990
- https://github.com/harvester/harvester/issues/3242
- https://github.com/harvester/harvester/issues/2682

HARVESTER: Fix disk issues

---

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue

- https://github.com/harvester/harvester/issues/2807
1. Go to create an image via download url
2. Go to image detail page
3. Click config button
4. URL should be visible
1. Go to upload an image
2. Go to image detail page
3. Click config button
4. File Name should be visible

HARVESTER: display image url on the image edit page.

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/detail/harvesterhci.io.host/HarvesterHostBasic.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvester/node.js

HARVESTER: close kvm

---

pkg/harvester/models/harvester/persistentvolumeclaim.js

fix array error

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/DataTemplate.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue

Fixes #
- https://github.com/harvester/harvester/issues/2934

Fix cloud-init empty when click cancel button

---

pkg/harvester/formatters/HarvesterIpAddress.vue
pkg/harvester/formatters/HarvesterMigrationState.vue
pkg/harvester/formatters/HarvesterNodeName.vue
pkg/harvester/list/harvesterhci.io.cloudtemplate.vue
pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/list/harvesterhci.io.logging.clusterflow.vue
pkg/harvester/list/harvesterhci.io.logging.clusteroutput.vue
pkg/harvester/list/harvesterhci.io.logging.flow.vue
pkg/harvester/list/harvesterhci.io.logging.output.vue
pkg/harvester/list/harvesterhci.io.monitoring.alertmanagerconfig.vue
pkg/harvester/list/harvesterhci.io.secret.vue
pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/list/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/list/harvesterhci.io.vmsnapshot.vue
pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/list/harvesterhci.io.volumesnapshot.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue
pkg/harvester/mixins/harvester-vm/impl.js
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvester.js
pkg/harvester/models/kubevirt.io.virtualmachine.js
shell/components/ResourceDetail/index.vue

PR in rancher/dashboard: https://github.com/rancher/dashboard/pull/7857
- https://github.com/harvester/harvester/issues/2184
1. Go to `<Your IP>/c/local/explorer`
2. Lists of harvester resources should work fine.

HARVESTER: use dynamic store to fetch resources

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/pages/c/_cluster/support/index.vue
shell/components/ResourceDetail/Masthead.vue

Sync with upstream commit https://github.com/rancher/dashboard/commit/93fd50d8076206b6cbe1da567d09aa9df1619eb9#
Change `DEV` to `PLUGIN_DEVELOPER`

HARVESTER: Sync with 'View in API' preference is not obvious

---

pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io.vue

Fixes #
- https://github.com/harvester/harvester/issues/3348

HARVESTER: Fix diskTag is undefined

---

shell/components/ResourceDetail/Masthead.vue

Harvester: Fix detail page external link

---

pkg/harvester/dialog/HarvesterMigrationDialog.vue
pkg/harvester/formatters/HarvesterIpAddress.vue
pkg/harvester/formatters/HarvesterNodeName.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue
pkg/harvester/models/kubevirt.io.virtualmachine.js

Each execution of `this.$store.getters['currentProduct'].instore` costs about 0.6ms，  But both the list page and the detail page have a lot of loops executing this code， so it takes a lot of time
Fixes #

HARVESTER: fix performance

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/validators/volume.js

Fix could not find i18 field。
Fixes #

HARVESTER: fix message

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue

Fix the volume setting missing from configured and running VM
~#### PR Checklist~
- https://github.com/harvester/harvester/issues/3362
The previous requirement was to set the volume to `null` when editing a VM after the image corresponding to a volume has been deleted and to ask the user to reselect the image.
Now it is not possible to delete a mirror that is in use, so the original checksum can be removed and the issue [3362](https://github.com/harvester/harvester/issues/3362) can be fixed.

HARVESTER: Fix volume setting missing from configured and running VM

---

shell/components/ResourceTable.vue

Fixes #
- https://github.com/rancher/dashboard/issues/8094

HARVESTER: enhancement shortcut in ResourceTable

---

shell/assets/translations/en-us.yaml
shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue

- https://github.com/harvester/harvester/issues/2798

HARVESTER: use form validation for duplicated receiver names

---

pkg/harvester/store/harvester-store/actions.ts

Fix compatibility with Rancher v2.6.x
- [] Yes, the relevant RBAC changes are at:~
- [] Yes, the relevant PR is at:~
- [] Yes, the backend owner is:~
Fixes #

HARVESTER: Fix compatibility with Rancher v2.6.x

---

shell/components/SortableTable/index.vue
shell/list/fleet.cattle.io.bundle.vue
shell/list/fleet.cattle.io.cluster.vue
shell/list/fleet.cattle.io.clusterregistrationtoken.vue
shell/list/fleet.cattle.io.gitrepo.vue
shell/list/logging.banzaicloud.io.clusterflow.vue
shell/list/logging.banzaicloud.io.flow.vue
shell/list/monitoring.coreos.com.alertmanagerconfig.vue
shell/list/node.vue
shell/list/persistentvolume.vue
shell/list/persistentvolumeclaim.vue
shell/list/provisioning.cattle.io.cluster.vue
shell/list/service.vue
shell/list/workload.vue
shell/mixins/resource-fetch-namespaced.js
shell/mixins/resource-fetch.js
shell/plugins/dashboard-store/actions.js
shell/plugins/dashboard-store/mutations.js

- ~[ ] Yes, the relevant PR is at~:
- https://github.com/harvester/harvester/issues/3438
Cherry-Pick from https://github.com/rancher/dashboard/pull/7904

Manual Refresh Performance Option(Picked from upstream)

---

pkg/harvester/config/harvester.js
pkg/harvester/models/namespace.js
pkg/harvester/store/harvester-common.js
pkg/harvester/store/harvester-store/actions.ts
pkg/harvester/store/harvester-store/getters.ts
shell/components/ExplorerProjectsNamespaces.vue
shell/components/form/NameNsDescription.vue
shell/components/nav/NamespaceFilter.vue
shell/store/index.js

Fixes #
- single cluster
- multi cluster

HARVESTER: polish namespace

---

pkg/harvester/components/settings/support-bundle-namespaces.vue
shell/assets/styles/global/_select.scss

Fixes #
- https://github.com/harvester/harvester/issues/3456
before:
Now:

fix labelselect style

---

pkg/harvester/config/harvester.js
pkg/harvester/dialog/HarvesterVlanConfigMigrateDialog.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/list/network.harvesterhci.io.clusternetwork.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvester/k8s.cni.cncf.io.networkattachmentdefinition.js
pkg/harvester/models/network.harvesterhci.io.clusternetwork.js
pkg/harvester/models/network.harvesterhci.io.vlanconfig.js
shell/models/k8s.cni.cncf.io.networkattachmentdefinition.js

Fixes #
- https://github.com/harvester/harvester/issues/3372
- https://github.com/harvester/harvester/issues/3440
- Migrate network configuration to another cluster network
- Support update network
- Add the ready status for the network
- It's not allowed to use the unready network

HARVESTER: Support updating VM networks and vlanconfigs

---

pkg/harvester/models/harvester/namespace.js
shell/components/ExplorerProjectsNamespaces.vue
shell/models/namespace.js

Fixes Cannot edit Harvester namespace
The upstream PR is https://github.com/rancher/dashboard/pull/8127
- https://github.com/harvester/harvester/issues/3435
- Edit location has a dependency on the detail location, so add a `hideDetailLocation` without changing the detail location

HARVESTER: Fix Cannot edit Harvester namespace

---

pkg/harvester/components/UpgradeInfo.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue

For users without permission to access node, we should not display node information.
before:
after: 
case 2: 
The upstream changed the style of the Banner component, causing some styling issues
before: 
after: 
Fixes #

HARVESTER: hide node col

---

pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/formatters/HarvesterDiskState.vue
pkg/harvester/models/harvester/node.js

Add block device error message as disk state tooltip
Fixes #
- https://github.com/harvester/harvester/issues/2682

HARVESTER: Add block device error message as disk state tootip

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/validators/vm.js

Fixes #
- https://github.com/harvester/harvester/issues/2810

HARVESTER: support resize volume

---

pkg/harvester/dialog/HarvesterCloneTemplate.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js

Fixes #
- https://github.com/harvester/harvester/issues/571

HARVESTER: enhancement template (with data)

---

pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js

This is a backport pr: https://github.com/harvester/dashboard/pull/586
Fixes #
- https://github.com/harvester/harvester/issues/3493

[backport] HARVESTER: Compatibility template status not ready condition

---

pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js

Fixes #
- https://github.com/harvester/harvester/issues/3493

HARVESTER: Compatibility template status not ready condition

---

pkg/harvester/validators/vm.js

Fixes #
- https://github.com/harvester/harvester/issues/3492

HARVESTER: set name length max 63

---

pkg/harvester/validators/vm.js

This is backport pr: https://github.com/harvester/dashboard/pull/589
Fixes #
- https://github.com/harvester/harvester/issues/3492

[backport] HARVESTER: set name length max 63

---

pkg/harvester/list/network.harvesterhci.io.clusternetwork.vue
pkg/harvester/models/network.harvesterhci.io.vlanconfig.js

Backport of https://github.com/harvester/dashboard/pull/591

[Backport 1.1] HARVESTER: Fix VlanConfig state display active but actual is "Not Ready"

---

pkg/harvester/components/settings/storage-network.vue
pkg/harvester/l10n/en-us.yaml

Fixes #
- https://github.com/harvester/harvester/issues/3478

HARVESTER: enhancement storage-network (add exclude list)

---

pkg/harvester/components/settings/storage-network.vue
pkg/harvester/l10n/en-us.yaml

This is a backport pr: https://github.com/harvester/dashboard/pull/593
Fixes #

[backport v1.1] HARVESTER: enhancement storage-network (add exclude list)

---

pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/store/harvester-common.js

Fixes #
- https://github.com/harvester/harvester/issues/3510

HARVESTER: FIX  backup-targe test connection in multi cluster

---

pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/store/harvester-common.js

Fixes #
- https://github.com/harvester/harvester/issues/3510

[backport] HARVESTER: FIX  backup-targe test connection in multi cluster

---

pkg/harvester/config/harvester.js

Fixes #
- https://github.com/harvester/harvester/issues/3190#issuecomment-1439224003
You can create Secrets in `cattle-logging-system` namespace.
1. Create a Secret in `cattle-logging-system`.
2. Go to Cluster Output page.
3. You can choose the secret just created in the dropdown.

[Backport]HARVESTER: cattle-logging-system is enabled on Secrets create page

---

pkg/harvester/config/harvester.js

Fixes #
- https://github.com/harvester/harvester/issues/3190#issuecomment-1439224003
You can create Secrets in `cattle-logging-system` namespace.
1. Create a Secret in `cattle-logging-system`.
2. Go to Cluster Output page.
3. You can choose the secret just created in the dropdown.

HARVESTER: cattle-logging-system is enabled on Secrets create page

---

pkg/harvester/components/settings/storage-network.vue
pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/models/network.harvesterhci.io.clusternetwork.js
pkg/harvester/models/network.harvesterhci.io.vlanconfig.js
pkg/harvester/models/network.harvesterhci.io.vlanstatus.js

Backport of https://github.com/harvester/dashboard/pull/599
- https://github.com/harvester/harvester/issues/3488

[Backport 1.1]HARVESTER: Fix vlan status issue

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/base.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/index.vue

This is a backport pr: https://github.com/harvester/dashboard/pull/605
Fixes #

[Backport v1.1] enhancement vm network UX

---

shell/components/form/NameNsDescription.vue

Fixes #
- https://github.com/harvester/harvester/issues/3533

HARVESTER: fix filternamespace is null

---

shell/components/form/NameNsDescription.vue

This is a backport pr:  https://github.com/harvester/dashboard/pull/608
Fixes #

[Backport v1.1] HARVESTER: fix filternamespace is null

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/CompatibilityMatrix.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/index.vue
pkg/harvester/l10n/en-us.yaml

- https://github.com/harvester/harvester/issues/3146
1. Go to VM create page
2. Switch to PCI devices tab
3. Select device from dropdown
4. You can only choose devices are belonged the same node
5. You can not select the device owned by other VMs
6. Matrix should display the PCI claim name of devices

HARVESTER: PCI device UI changes

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/CompatibilityMatrix.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/index.vue
pkg/harvester/l10n/en-us.yaml

Original PR: https://github.com/harvester/dashboard/pull/595

[Backport]HARVESTER: PCI device UI changes

---

shell/components/ExplorerMembers.vue

This is a backport pr: https://github.com/harvester/dashboard/pull/614
Fixes #

[Backport v1.1.2] fix i18

---

shell/components/ExplorerMembers.vue

HARVESTER: fix clusterMember i18

---

pkg/harvester/components/settings/storage-network.vue

This is a backport pr: https://github.com/harvester/dashboard/pull/621
Fixes #

[Backport v1.1.2] HARVESTER: delete empty array (storage-network)

---

pkg/harvester/components/settings/storage-network.vue

Fixes #
- https://github.com/harvester/harvester/issues/3478#issuecomment-1443139300

HARVESTER: delete empty array (storage-network)

---

pkg/harvester/models/clusterroletemplatebinding.js
shell/components/ExplorerMembers.vue

Original PR: https://github.com/harvester/dashboard/pull/619

HARVESTER: supply missing model in harvester plugin

---

shell/utils/grafana.js
shell/utils/monitoring.js

Fixes #
- https://github.com/harvester/harvester/issues/3537

fix not visible grafana 

---

shell/utils/grafana.js
shell/utils/monitoring.js

This is a backport pr: https://github.com/harvester/dashboard/pull/623
Fixes #

[Backport v1.1.2] fix not visible grafana

---

pkg/harvester/dialog/HarvesterMaintenanceDialog.vue

Fixes #
- https://github.com/harvester/harvester/issues/2723#issuecomment-1432868440

HARVESTER: enhancement maintenance

---

pkg/harvester/dialog/HarvesterMaintenanceDialog.vue

This is a backport pr: https://github.com/harvester/dashboard/pull/596
Fixes #

[Backport v1.1] enhancement maintenance

---

shell/edit/logging-flow/index.vue

Original PR: https://github.com/harvester/dashboard/pull/611

[Backport]HARVESTER: constrain to display text at one line in vue-select.

---

shell/edit/logging-flow/index.vue

- https://github.com/harvester/harvester/issues/3527

HARVESTER: constrain to display text at one line in vue-select.

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

This is a backport pr:  https://github.com/harvester/dashboard/pull/627
Fixes #

[Backport v1.1.2] fix vm network link

---

pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io.vue

Backport of https://github.com/harvester/dashboard/pull/630

[Backport v1.1.2]HARVESTER: Fix storage class clone issue

---

pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io.vue

Fix storage class clone issue
- https://github.com/harvester/harvester/issues/3560

HARVESTER: Fix storage class clone issue

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/mixins/harvester-vm/index.js

This is a backport pr: https://github.com/harvester/dashboard/pull/625
Fixes #

[Backport v1.1.2] template fix

---

pkg/harvester/components/DiskTags.vue

Allow click enter keyboard to add tags

HARVESTER: Add disk tag enhancement

---

pkg/harvester/components/DiskTags.vue

Backport of https://github.com/harvester/dashboard/pull/632

[Backport V1.1.2] HARVESTER: Add disk tag enhancement

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

- Add monitoring and logging translation
Fixes #

HARVESTER: add monitoring i18

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

- Add monitoring and log translation
Fixes #

[Backport v1.1.2] i18

---

pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterDisk.vue
pkg/harvester/l10n/en-us.yaml

HARVESTER: Update i18n on disk page

---

pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterDisk.vue
pkg/harvester/l10n/en-us.yaml

Backport of https://github.com/harvester/dashboard/pull/640

[Backport v1.1.2] Update i18n disk bak

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/impl.js
pkg/harvester/mixins/harvester-vm/index.js

Fixes #
- https://github.com/harvester/harvester/issues/2910

HARVESTER: support TPM

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue

Fix VM ssh key style
- https://github.com/harvester/harvester/issues/3583

HARVESTER: Fix VM ssh key style

---

pkg/harvester/components/HarvesterUpgrade.vue
pkg/harvester/components/HarvesterUpgradeHeader.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/models/clusterroletemplatebinding1.js
pkg/harvester/models/harvesterhci.io.upgradelog.js
pkg/harvester/types.ts
shell/plugins/dashboard-store/resource-class.js

~- Is this a multi-tenancy feature/bug?~
Fixes #
- https://github.com/harvester/harvester/issues/1926

[Backport v1.1.2] HARVESTER: enhancement upgrade log download

---

pkg/harvester/components/FilterLabel.vue

This is a backport pr: https://github.com/harvester/dashboard/pull/617
Fixes #
before:
afeter:

[Backport v1.1.2] HARVESTER: fix filterLabel style

---

pkg/harvester/pages/c/_cluster/airgapupgrade/index.vue

HARVESTER: support airgap upgrade enable logging

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/pages/c/_cluster/support/index.vue

Add learn more on support page

Harvester: Add learn more on support page

---

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue

Fixes #
- https://github.com/harvester/harvester/issues/3662

HARVESTER: fix create multi vm validate

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/models/harvester.js
pkg/harvester/pages/c/_cluster/support/index.vue
shell/components/ExplorerProjectsNamespaces.vue
shell/components/ResourceDetail/Masthead.vue
shell/plugins/dashboard-store/resource-class.js

Fix v2.6.10 compatibility
- https://github.com/harvester/harvester/issues/3658
**Test Plan**
- Case 1
Check setting list page
- Case 2
Check Project/Namespace page
- Case 3
Check Volume Detail page
- Case 4
Check VM volume tab
- Case 5
Check upgrade-checker-url setting
- Case 6
Test in v2.6.9 - v2.6.11, v2.7.0 - v2.7-head

Harvester: Fix v2.6.10 compatibility

---

pkg/harvester/components/HarvesterUpgrade.vue
pkg/harvester/pages/c/_cluster/airgapupgrade/index.vue

UI shouldn't present "Enable Logging" checkbox before v1.1.2
- https://github.com/harvester/harvester/issues/3656

HARVESTER: UI shouldn't present "Enable Logging" checkbox before v1.1.2

---

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue

Fixes #
- https://github.com/harvester/harvester/issues/3601

HARVESTER: Add node filter in nics computed property

---

pkg/harvester/store/harvester-store/actions.ts

Fix isMultiCluster is false
- https://github.com/harvester/harvester/issues/3658

HARVESTER: Fix isMultiCluster is false

---

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

Fix i10n missing
- https://github.com/harvester/harvester/issues/3716

HARVESTER: Fix i10n missing

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/models/harvester/k8s.cni.cncf.io.networkattachmentdefinition.js

Fix i10n missing tooltip
- https://github.com/harvester/harvester/issues/3716

HARVESTER: Fix i10n missing tooltip

---

pkg/harvester/models/network.harvesterhci.io.vlanconfig.js

Fixes #
- https://github.com/harvester/harvester/issues/3723

Harvester: fix vlan state

---

pkg/harvester/components/settings/csi-driver-config.vue
pkg/harvester/config/settings.js
pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/edit/harvesterhci.io.storage/provisioners/custom.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/types.ts

Fixes #
- https://github.com/harvester/harvester/issues/2405

support external storage class

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

Fix PCI devices won't show up after upgrade in edit VM
Fix PCI devices won't show up after upgrade in edit VM
- https://github.com/harvester/harvester/issues/3759
```
hostDevices:
- deviceName: nvidia.com/TU104GL_TESLA_T4
name: TU104GL_TESLA_T41
- deviceName: nvidia.com/TU104GL_TESLA_T4
name: TU104GL_TESLA_T42
```

HARVESTER: Fix PCI devices won't show up after upgrade in edit VM

---

pkg/harvester/config/harvester.js
pkg/harvester/dialog/EnableSriovDevice.vue
pkg/harvester/formatters/SriovNodeName.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/devices.harvesterhci.io.sriovnetworkdevice.vue
pkg/harvester/models/devices.harvesterhci.io.sriovnetworkdevice.js
pkg/harvester/types.ts

- https://github.com/harvester/harvester/issues/2763

HARVESTER: Implement SR-IOV

---

pkg/harvester-manager/models/harvesterhci.io.management.cluster.js
pkg/harvester/list/harvesterhci.io.dashboard.vue
pkg/harvester/models/clusterroletemplatebinding.js
pkg/harvester/store/harvester-store/getters.ts
shell/components/ClusterProviderIcon.vue
shell/components/nav/Header.vue
shell/components/nav/TopLevelMenu.vue
shell/config/product/explorer.js
shell/layouts/default.vue
shell/list/fleet.cattle.io.cluster.vue
shell/list/management.cattle.io.feature.vue
shell/list/provisioning.cattle.io.cluster.vue
shell/middleware/authenticated.js
shell/models/catalog.cattle.io.app.js
shell/models/management.cattle.io.cluster.js
shell/models/management.cattle.io.feature.js
shell/models/provisioning.cattle.io.cluster.js
shell/models/service.js
shell/pages/c/_cluster/explorer/index.vue
shell/pages/c/_cluster/explorer/tools/index.vue
shell/pages/home.vue
shell/store/index.js

HEP: 
- https://github.com/harvester/harvester/pull/3673/commits/3ef06db85974b1b5779aba9ac3ed5a836aeb4d6e
Fixes #
- https://github.com/harvester/harvester/issues/2679

Harvester: add bare-metal container and mcm support

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/detail/harvesterhci.io.host/HarvesterHostBasic.vue
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/dialog/HarvesterPowerDialog.vue
pkg/harvester/edit/harvesterhci.io.addon/harvester-seeder.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterSeeder.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/models/harvester/node.js
pkg/harvester/models/metal.harvesterhci.io.inventory.js
pkg/harvester/types.ts

Seeder embedded
- https://github.com/harvester/harvester/issues/2318
* Enable Seeder addon integration
* Define valid inventory and secrets for node
* Wait for additional node labels to be propagated on the node.
* Wait for additional hardware events to be generated for the node.
* Perform node power actions via Harvester UI.

Seeder embedded

---

pkg/harvester/config/settings.js

Harvester: add rancher-manager-support setting

---

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
pkg/harvester/l10n/en-us.yaml

Add miimon tooltip
- https://github.com/harvester/harvester/issues/3744

HARVESTER: Add miimon tooltip

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue

Fix when cloning a VM, an alert message appears on the Volume tab page
- https://github.com/harvester/harvester/issues/3798

HARVESTER: Fix when cloning a VM, an alert message appears on the Volume tab page

---

pkg/harvester/utils/promise.js

Many times, when we use the `allHashSettled` function, If an API issue occurs, such as a lack of permission, the page will crash if there is no additional check implemented to handle such cases. However, we do not want this issue to cause the program to crash.
Fixes #

add allSettled func

---

pkg/harvester/dialog/HarvesterMigrationDialog.vue

- https://github.com/harvester/harvester/issues/3032

HARVESTER: use findMigratableNodes action to filter reachable nodes

---

pkg/harvester/components/settings/csi-driver-config.vue
pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.volume.vue

- https://github.com/harvester/harvester/issues/3686
1. Go to manage Storage Class
2. Switch to Allowed Topologies tab
3. You can manage the Allowed Topologies

HARVESTER: storage class polish

---

pkg/harvester/models/harvester/management.cattle.io.setting.js
shell/models/management.cattle.io.setting.js

HARVESTER: fix setting edit route

---

pkg/harvester-manager/machine-config/harvester.vue
pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue
pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js
pkg/harvester/models/kubevirt.io.virtualmachine.js
shell/assets/translations/en-us.yaml
shell/components/form/PodAffinity.vue

Add pod affinity on VM/VM template config page
_Create VM_
1. Go to Create VM
2. Add node/pod affinity
3. Save
4. Configuration of node/pod affinity should be found in yaml
5. Go to Edit VM
6. Configuration of node/pod affinity should be accurate on UI
7. Modify the configuration of node/pod affinity
8. Save
9. Repeat step 4
_Create VM from template_
1. Go to Create VM Template
2. Add node/pod affinity
3. Save
4. Go to Edit VM Template
5. Configuration of node/pod affinity should be accurate on UI
6. Modify the configuration of node/pod affinity
7. Save
8. Go to Create VM
9. Use template what you just created
10. Save
11. Configuration of node/pod affinity should be found in yaml
- https://github.com/harvester/harvester/issues/2491
- https://github.com/harvester/harvester/issues/2317

Harvester: Add pod affinity to VM config page

---

pkg/harvester/config/harvester.js
pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/types.ts

HARVESTER: remove logic code about managedchart

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/pages/c/_cluster/support/index.vue
shell/assets/translations/en-us.yaml
shell/components/nav/TopLevelMenu.vue
shell/list/management.cattle.io.feature.vue
shell/models/management.cattle.io.feature.js
shell/pages/c/_cluster/explorer/tools/index.vue

Fix mcm mode bug

---

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue

Fix NICs that do not match the rules are still displayed after changing the node selector
- https://github.com/harvester/harvester/issues/3525

HARVESTER: Fix NICs that do not match the rules are still displayed after changing the node selector

---

pkg/harvester/formatters/HarvesterCPUUsed.vue
pkg/harvester/formatters/HarvesterMemoryUsed.vue
pkg/harvester/formatters/HarvesterStorageUsed.vue
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.host.vue
shell/components/CopyToClipboardText.vue

Fixes #
- https://github.com/harvester/harvester/issues/3607

HARVESTER: fix host style

---

shell/assets/translations/en-us.yaml
shell/edit/logging.banzaicloud.io.output/providers/opensearch.vue

Hi @w13915984028 ! Please take a look at the screenshot below.
There is some UI changes:
1. expose `suppress_type_name` named as `Suppress Type Name`.
2. `suppress_type_name` will be true by default
If you have any concern, please let me know, thank you! cc @WuJun2016  @guangbochen 
- https://github.com/harvester/harvester/issues/3589
1. suppress_type_name should be true by default.
2. both of cluster output/ output should expose suppress_type_name.
3. suppress_type_name cluster output/output can be switched to false.

HARVESTER: expose suppress_type_name for opensearch provider

---

pkg/harvester/edit/harvesterhci.io.volume.vue

Enhance the image list on the Volume page
- https://github.com/harvester/harvester/issues/3801

HARVESTER: Enhance the image list on the Volume page

---

pkg/harvester/edit/harvesterhci.io.host/index.vue

Avoid "Operation cannot be fulfilled on nodes" error
- https://github.com/harvester/harvester/issues/2887
- https://github.com/harvester/harvester/issues/3849
- https://github.com/harvester/harvester/issues/3853

HARVESTER: Avoid "Operation cannot be fulfilled on nodes" error

---

pkg/harvester-manager/models/harvesterhci.io.management.cluster.js
pkg/harvester/components/SettingList.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.setting.vue

Category Harvester setting
- https://github.com/harvester/harvester/issues/3796

HARVESTER: Category Harvester setting

---

pkg/harvester/models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/3831

HARVESTER: except not ready volume

---

pkg/harvester/edit/harvesterhci.io.logging.clusterflow.vue
pkg/harvester/edit/harvesterhci.io.logging.clusteroutput.vue
pkg/harvester/edit/harvesterhci.io.secret.vue

- https://github.com/harvester/harvester/issues/3517
1. Go to create Secret/ Logging Cluster Flow/ Logging Cluster Output in `cattle-logging-system` namespace
2. Go to Volume create page
3. The preset namespace should not be `cattle-logging-system`

HARVESTER: revert namespace to default manually

---

pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.dashboard.vue
pkg/harvester/models/harvester/node.js
pkg/harvester/models/longhorn.io.node.js

Show disk count in dashboard overview
- https://github.com/harvester/harvester/issues/3455

HARVESTER: Show disk count in dashboard overview

---

pkg/harvester/detail/kubevirt.io.virtualmachine/VirtualMachineTabs/VirtualMachineBasics.vue
pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue

When the VM stops, we should display appropriate information.
Fixes #

HARVESTER: enhancement information display

---

pkg/harvester/components/HarvesterUpgrade.vue
pkg/harvester/l10n/en-us.yaml

Fixes #
- https://github.com/harvester/harvester/issues/3551

HARVESTER: enhancement upgrade checkbox

---

pkg/harvester/formatters/HarvesterIpAddress.vue
pkg/harvester/list/harvesterhci.io.virtualmachinetemplateversion.vue
shell/components/CopyToClipboardText.vue

HARVESTER: fix UX style

---

shell/assets/translations/en-us.yaml
shell/edit/logging.banzaicloud.io.output/providers/elasticsearch.vue
shell/edit/logging.banzaicloud.io.output/providers/opensearch.vue

Upstream PR: https://github.com/rancher/dashboard/pull/8788
- https://github.com/harvester/harvester/issues/3589
Hi @w13915984028 ! Could you please take a look at changes demanded by https://github.com/rancher/dashboard/pull/8788#discussion_r1186399209?
- We need also to add `suppress_type_name` for `elasticsearch`
- We need to add help text for `suppress_type_name`
Help text will be:
- `Suppress type names by default to be compatiable with log server.You should enable it for Elasticsearch >= 8.0.0`
- `Suppress type names by default to be compatiable with log server.You should enable it for OpenSearch …

HARVESTER: expose suppress_type_name for elasticsearch provider

---

pkg/harvester/config/harvester.js
pkg/harvester/edit/harvesterhci.io.addon/rancher-monitoring.vue
pkg/harvester/l10n/en-us.yaml

- https://github.com/harvester/harvester/issues/3921
Update the translations of monitoring & logging addons

HARVESTER: polish monitoring translations

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.dashboard.vue
pkg/harvester/list/harvesterhci.io.monitoring.alertmanagerconfig.vue

More details in upstream PR: https://github.com/rancher/dashboard/pull/8875
- https://github.com/harvester/harvester/issues/3887
1. the grafana chart was not visible after refreshing the page
2. Enhanced the text information display

HARVESTER: polish Grafana metrics on dashboard

---

pkg/harvester/components/settings/default-vm-termination-grace-period-seconds.vue
pkg/harvester/config/settings.js
pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineReserved.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

Add force stop
- https://github.com/harvester/harvester/issues/2466
- Add default-vm-termination-grace-period-seconds
- Add termination-grace-period-seconds on VM advanced tab
- Add VM action: "Force Stop"

HARVESTER: add force stop

---

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue

- https://github.com/harvester/harvester/issues/3890

HARVESTER: Restrict the countdown arrow.

---

shell/utils/grafana.js

- https://github.com/harvester/harvester/issues/3887
Correct the url of grafana metrics.
1. Go to Dashboard page, exhibition of grafana metrics should be correctly.

HARVESTER: amend grafana metrics url

---

shell/utils/__tests__/grafana.test.ts

Fix test ci failed
~- Is this a multi-tenancy feature/bug?~
Fixes #

HARVESTER: fix test ci

---

pkg/harvester-manager/config/harvester-manager.js
shell/assets/translations/en-us.yaml
shell/components/formatter/ClusterProvider.vue
shell/components/nav/TopLevelMenu.vue
shell/pages/c/_cluster/explorer/index.vue
shell/pages/home.vue
shell/utils/cluster.js

According to the design requirements of rancher team, we need to modify some menu styles and adjust the design。
Fixes #
before: 
now:

HARVESTER: change mcm UI design

---

shell/pages/auth/setup.vue

- Is this a multi-tenancy feature/bug? -https://github.com/rancher/dashboard/pull/8934
Fix Harvester login can update server url
- https://github.com/harvester/harvester/issues/3886

HARVESTER: Fix Harvester login can update server url

---

pkg/harvester/l10n/en-us.yaml

- https://github.com/harvester/harvester/issues/3921

HARVESTER: amend the addon translations

---

pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/formatters/HarvesterHost.vue
pkg/harvester/formatters/HarvesterVolumeState.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvester/persistentvolumeclaim.js

- https://github.com/harvester/harvester/issues/2856
- We will display more details from longhorn on harvester volume detail page.
- You can see the rebuilding status of volume on the volume list page.
Rebuilding status on volume page
1. Go to preference page, enable `Extension developer features`
3. Go to create vm with 2 volumes
4. Direct to longhorn volume detail page
5. Go to Support page, open `Embeded Rancher UI` on the new browser tab
6. Go to search type `instance` and then go to instance manager list
7. Delete related instance manager
8. Back to harvester volume page
9. It's expected to see …

HARVESTER: additional longhorn information

---

pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue

When we create the volume, the user should not enter decimals, which makes no sense to the user。
-~ Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
Fixes #

HARVESTER: Restrict volume to integers only

---

pkg/harvester/components/HarvesterUpgrade.vue
pkg/harvester/components/HarvesterUpgradeHeader.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvesterhci.io.upgradelog.js

Fixes #
- https://github.com/harvester/harvester/issues/3655
1. When the log download fails, users can see the reason for the failure.

HARVESTER: upgrade log enhancemnet

---

pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue

Fixes #
- https://github.com/harvester/harvester/issues/3992
If the user has the rancher-monitoring addon enabled, the user should see the VM Metrics normally when they go to the vm details page, if not, the VM Metrics will be hidden.
1. install a harvester (``v1.2.0-master`)
2. create a `Image`
3. create a `VM`
4. go to VM detail page
5. The page should display normally  （If the user has the rancher-monitoring addon enabled, the user should see the VM Metrics normally when they go to the vm details page, if not, the VM Metrics will be hidden.）
1. Import the harvester cluster into the rancher.
2. From …

HARVESTER: fix vm detail metrics error

---

pkg/harvester/store/harvester-store/actions.ts

Fixes The saved preference will be reset after the page is refreshed
- https://github.com/harvester/harvester/issues/3958
```js
const asUserPreference = opt.asUserPreference !== false;
// undefined !== false => const asUserPreference = true
```

HARVESTER: The saved preference will be reset after the page is refreshed

---

pkg/harvester/edit/harvesterhci.io.setting.vue

When the rancher-manage-support setting is modified, the TopLevelMenu should be shown or hidden automatically.
Fixes #

HARVESTER: auto show topLevelMenu

---

pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue
pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/index.js

Fix Rancher v2.7.3 with Harvester v1.2.0-rc1 "VM Scheduling" translation error
- https://github.com/harvester/harvester/issues/4011
- Move translation to harvster plugin

HARVESTER: Fix Rancher v2.7.3 with Harvester v1.2.0-rc1 "VM Scheduling" translation error

---

pkg/harvester/config/harvester-map.js
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml

Show a banner on the Out-of-band Access tab of the Host page when seeder addon disabled.
- https://github.com/harvester/harvester/issues/3988
- harvester-seeder does not exist: `Addon "harvester-seeder" is not exist, please check if it is installed.`
- user have not access to addon list: `Please contact system admin to enable the Out-of-Band Access first.`
- harvester-seeder is disabled: `Addon "harvester-seeder" is disabled now, click here to enable it.`

HARVESTER: Show a banner on the Out-of-band Access tab of the Host page when seeder addon disabled.

---

pkg/harvester/package.json

HARVESTER: change plugin version

---

pkg/harvester/detail/harvesterhci.io.vmsnapshot/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineCpuMemory.vue
pkg/harvester/store/harvester-store/getters.ts

HARVESTER: fix style

---

pkg/harvester/mixins/harvester-vm/index.js

The name of the vm ends with -, e.g. `test-`, there may be a problem with the generated label。
Fixes #

HARVESTER: fix create multiple instance

---

pkg/harvester/edit/harvesterhci.io.virtualmachinebackup.vue

We should filter namespace
Fixes #

HARVESTER: fix backups namespace

---

shell/plugins/steve/web-worker.steve-sub-worker.js

HARVESTER: fix lint

---

pkg/harvester-manager/l10n/en-us.yaml
pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue
pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/index.js

- https://github.com/harvester/harvester/issues/2317

HARVESTER: vm scheduling polish

---

pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/index.vue

Fix edit LB yaml lack of status
- Refactor by using `yamlModifiers`

HARVESTER: Fix edit LB yaml lack of status

---

pkg/harvester/edit/loadbalancer.harvesterhci.io.ippool/PriorityRow.vue

Fix guest cluster option wrong display
- https://github.com/harvester/harvester/issues/1762#issuecomment-1586755810
- Add none option like the project
- Fix guest cluster did not filter by project

HARVESTER: Fix guest cluster option wrong display

---

pkg/harvester/models/harvester/namespace.js

filter fleet-default namespace
Fixes #

HARVESTER: filter fleet-default namespace

---

pkg/harvester/components/settings/ntp-servers.vue
pkg/harvester/config/labels-annotations.js
pkg/harvester/config/settings.js
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvesterhci.io.setting.js
pkg/harvester/validators/index.js
pkg/harvester/validators/setting.js

- https://github.com/harvester/harvester/issues/3133
- The synchronising information of Ntp servers will be displayed on detail page of Host now.
- You can configure Ntp servers addresses on Setting page
1. Go to configure Ntp servers settings
2. Ntp servers addresses should be IPV4 format or Host format, if you enter wrong type, UI will prevent the updating process.
1. Go to the detail page of Host
2. Warning messages should displayed if Ntp servers synchronize failed.

HARVESTER: implement ntp sync status

---

shell/components/GrafanaDashboard.vue

- https://github.com/harvester/harvester/issues/4087

HARVESTER: keep the param referer on the newly opened grafana page.

---

pkg/harvester/edit/harvesterhci.io.setting.vue
shell/layouts/default.vue

Fixes #
1. <img width="1722" alt="image" src="https://github.com/harvester/dashboard/assets/24985926/0ed00336-0a58-4682-8f81-8ad848f73ed3">
When the user returns to the list page, it should return to the page it came in
2. fix menu align

HARVESTER: enhancement return hash route

---

pkg/harvester/list/harvesterhci.io.host.vue

Cluster members should not see the disk state

HARVESTER: cluster member should not see disk state

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/formatters/HarvesterVmState.vue
pkg/harvester/models/kubevirt.io.virtualmachine.js

Allow dismiss VM insufficient resource quota

HARVESTER: Allow dismiss VM insufficient resource quota

---

pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterKsmtuned.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue

Fix cluster-member user without permission
Fixes #

HARVESTER: fix ksmtuned RBAC

---

pkg/harvester/config/labels-annotations.js

Fixes #
- https://github.com/harvester/harvester/issues/3133

HARVESTER: update the annotation key of ntp server

---

pkg/harvester/formatters/HarvesterVmState.vue

The moment the vm is created, an error message appears, which we don't want, because there is no error in the vm at this time
Fixes #

HARVESTER: fix vm warning message

---

pkg/harvester/components/FilterBySriov.vue
pkg/harvester/config/labels-annotations.js
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/DeviceList.vue
pkg/harvester/formatters/HarvesterVFsNum.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/devices.harvesterhci.io.sriovnetworkdevice.vue

- Are backend engineers aware of UI changes?~
- https://github.com/harvester/harvester/issues/4146
1. Go to Enable SR-IOV devices.
2. Go to PCI devices list page.
3. You are able to filter the devices by parent SR-IOV.

HARVESTER: add query params for pcidevices list

---

pkg/harvester/l10n/en-us.yaml

Fixes #
- https://github.com/harvester/harvester/issues/3524

HARVESTER: remove pci-experimental

---

pkg/harvester/validators/vm.js

Fixes #
- https://github.com/harvester/harvester/issues/3948

HARVESTER: fix volume validation rule

---

pkg/harvester/detail/harvesterhci.io.host/HarvesterSeeder.vue
pkg/harvester/edit/harvesterhci.io.host/HarvesterSeeder.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/formatters/StateWithPopover.vue
pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/models/harvester/node.js
pkg/harvester/models/metal.harvesterhci.io.inventory.js

HARVESTER: Fix seeder can not edit and Add seeder error message display

---

pkg/harvester/edit/harvesterhci.io.addon/rancher-vcluster.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.addon.vue
pkg/harvester/models/harvesterhci.io.addon.js

HARVESTER: add vcluster addon

---

shell/components/form/PodAffinity.vue

https://github.com/harvester/harvester/issues/2317#issuecomment-1617940290
https://github.com/harvester/harvester/issues/2317#issuecomment-1617940290

HARVESTER: only change priority by select component

---

pkg/harvester/edit/harvesterhci.io.addon/rancher-vcluster.vue

enhancement rancher vcluster

---

shell/pages/c/_cluster/apps/charts/index.vue

Fixes #
- https://github.com/harvester/harvester/issues/4199

fix version undefine

---

pkg/harvester/models/harvesterhci.io.addon.js

- https://github.com/harvester/harvester/issues/4067

HARVESTER: revert addon status changes

---

shell/initialize/index.js
shell/utils/favicon.js

fix favicon

---

pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml
shell/components/MessageLink.vue

Fix the display of the disk twice when adding the disk
- https://github.com/harvester/harvester/issues/4198
- https://github.com/harvester/harvester/issues/3988#issuecomment-1625505532
- Filter by `status.state`
- Fix Seeder banner
- Add harvester-seeder addon description

HARVESTER: Fix the display of the disk twice when adding the disk

---

pkg/harvester/config/settings.js
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
shell/store/index.js

remove `rancher-manager-support` setting , We support mcm via `rancher-vcluster` addon
Fixes #

remove rancher-manager-support setting

---

pkg/harvester/l10n/en-us.yaml
shell/components/ResourceTable.vue

1. pci does not support namespace group
3. Some translations need to be moved to harvester i18n file.
Fixes #

fix remove PCI device namespace group

---

pkg/harvester/models/harvesterhci.io.addon.js

We want to improve the exhibitions of addon's status.
- https://github.com/harvester/harvester/issues/4067
- https://github.com/harvester/harvester/issues/4108
1. Swtich enabling/disabling status of addon quickly should be failed and you should see the error message on the top-right corner.
2. When enabling/disabling/updating if you edit the configurations of addon and then save, save should be failed and the error message should be also displayed.

HARVESTER: apply addon changes

---

pkg/harvester/models/metal.harvesterhci.io.inventory.js

Add validation for invalid polling Interval
- https://github.com/harvester/harvester/issues/2318#issuecomment-1643221750

HARVESTER: Add validation for invalid polling Interval

---

pkg/harvester/components/settings/http-proxy.vue
pkg/harvester/l10n/en-us.yaml

http-proxy setting add tip

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvesterhci.io.addon.js

- https://github.com/harvester/harvester/issues/4108

HARVESTER: improve addon error message

---

pkg/harvester/l10n/en-us.yaml

Updating the rancher-monitoring description slightly via the text.
Curious, if this will flow better when reading - when comparing it to the original/current-text.
Very open to thoughts, iterating on this PR, etc.
Fixes #
Description update - wondering if updated description will flow better?
Description update - wondering if updated description will flow better?
N/A
N/A, already validated text/description change
N/A

doc: Update rancher-monitoring Description

---

pkg/harvester/edit/harvesterhci.io.addon/rancher-monitoring.vue

Fixes #
- https://github.com/harvester/harvester/issues/4299

fix issue 4299

---

pkg/harvester/models/devices.harvesterhci.io.pcidevice.js
pkg/harvester/models/devices.harvesterhci.io.sriovnetworkdevice.js

Fixes #
- https://github.com/harvester/harvester/issues/4319
1. Mouse to select any row of resources
2. press the Enter key (if the resource has a detail page, then it should go to the detail page correctly, otherwise nothing will be done)

HARVESTER: disable enter key

---

pkg/harvester/list/harvesterhci.io.volumesnapshot.vue

Although namespace is now displayed correctly, the parameter `namespace=false` should not be passed in the component.
Fixes #

fix volumesnapshot no namespace

---

pkg/harvester/l10n/en-us.yaml

change storage-network text

---

pkg/harvester/formatters/HarvesterListener.vue

HARVESTER: change lb address to copy

---

pkg/harvester/edit/harvesterhci.io.host/index.vue

seeder addon should not show Update Successfully when field validation fail
- https://github.com/harvester/harvester/issues/4302

HARVESTER: seeder addon should not show Update Successfully when field validation fail

---

pkg/harvester/pages/c/_cluster/support/index.vue

This reverts commit e7a963e9efaadb8b6e5b94d28e4a18d6121ca41a.
Fixes #

Revert "HARVESTER: show rancher & longhorn link"

---

pkg/harvester/formatters/HarvesterVmState.vue

Fixes #
- https://github.com/harvester/harvester/issues/4394

Fix vm message is undefined

---

pkg/harvester/edit/harvesterhci.io.addon/rancher-vcluster.vue
pkg/harvester/models/harvesterhci.io.addon.js

Fixes #
- https://github.com/harvester/harvester/issues/2679#issuecomment-1669838427

enhancement vcluster form

---

pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml

Fix fail to enable Out-of-Band Access on host
- https://github.com/harvester/harvester/issues/4387

HARVESTER: Fix seeder

---

scripts/ci

remove test:ci

---

.drone.yml

fix build-pkg

---

shell/pages/prefs.vue

This is multi cluster feature, we need delete it.
Fixes #

delete unuse preferences

---

pkg/harvester/components/settings/storage-network.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

enhancement storage-network tip

---

pkg/harvester/components/settings/storage-network.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

This is a backport pr: https://github.com/harvester/dashboard
Fixes #

Backup storage network tip

---

pkg/harvester/formatters/HarvesterBackupTargetValidation.vue

Fixes #
- https://github.com/harvester/harvester/issues/4483

fix backuptarget is empty

---

pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue

In multiple clusters, the health check of backuptarget does not work。  （admin user / cluster-project user）
Fixes #

fix multi cluster backupTarget healthz check

---

pkg/harvester/models/harvester/secret.js

When using harvester clusters, users should not be redirected to other pages on the details page.
Fixes #

disable secret detail page jump to other page

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

fix rancher-integration link

---

pkg/harvester/l10n/en-us.yaml

Fixes https://github.com/harvester/harvester/issues/4673

Fix NTP servers labels in settings page

---

pkg/harvester/components/novnc/NovncConsoleItem.vue

Fixes https://github.com/harvester/harvester/issues/4535

Fix multi-key shortcuts in vm console view

---

pkg/harvester/formatters/HarvesterBackupProgressBar.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue
pkg/harvester/models/harvesterhci.io.virtualmachinebackup.js
pkg/harvester/models/kubevirt.io.virtualmachine.js
shell/assets/translations/en-us.yaml

Fixes https://github.com/harvester/harvester/issues/4102
It adds a progress bar to display information about VMs backup/restore process:
- `VM Backups` tab: it shows the status of new backups; a tooltip shows the progress of VM volumes backups.
- For completed backups, the progress bar is replaced by a 'Completed' label.
- `Virtual Machines` tab: it shows the status of restored VMs; a tooltip shows the progress of VM volumes restores.
- For restored VMs, the progress bar is replaced by a 'Completed' label.
- For not restored VMS, a dash character is displayed.
VM Backups and Virtual Machines page
VM …

Add Progress bar for Backups/Restore actions

---

pkg/harvester/components/FilterBySriov.vue
pkg/harvester/config/harvester-map.js
pkg/harvester/config/harvester.js
pkg/harvester/config/labels-annotations.js
pkg/harvester/dialog/EnablePassthrough.vue
pkg/harvester/dialog/EnableVGpuDevice.vue
pkg/harvester/edit/harvesterhci.io.addon/nvidia-driver-toolkit.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/DeviceList.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVGpuDevices/VGpuDeviceList.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVGpuDevices/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/formatters/HarvesterVFAddress.vue
pkg/harvester/formatters/HarvesterVFsNum.vue
pkg/harvester/formatters/HarvesterVGpuDevices.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/devices.harvesterhci.io.pcidevice.vue
pkg/harvester/list/devices.harvesterhci.io.sriovgpudevice.vue
pkg/harvester/list/devices.harvesterhci.io.sriovnetworkdevice.vue
pkg/harvester/list/devices.harvesterhci.io.vgpudevice.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/devices.harvesterhci.io.pcidevice.js
pkg/harvester/models/devices.harvesterhci.io.sriovgpudevice.js
pkg/harvester/models/devices.harvesterhci.io.sriovnetworkdevice.js
pkg/harvester/models/devices.harvesterhci.io.vgpudevice.js
pkg/harvester/models/harvesterhci.io.addon.js
pkg/harvester/types.ts
shell/components/ResourceTable.vue

Fixes https://github.com/harvester/harvester/issues/2764
It adds new UI elements to handle the vGpus devices and attach them to Virtual Machines:
- `nvidia-driver-toolkit` addons: it is required to handle vGpus and add them to new VMs.
- new tab vGPU Devices
- new tab SR-IOV GPU Devices
- new vGpu setting in VMs form
- new tab vGPU Devices
- new tab SR-IOV GPU Devices
- VM create/edit form
- SR-IOV Network Devices tab
- PCI Devices tab
- VM create/edit form
nvidia-driver-toolkit + description
nvidia-driver-toolkit edit page
SR-IOV GPU Devices tab
vGPU Devices tab, nvidia/pci addons disabled
vGPU Devices …

vGpuDevices

---

shell/edit/management.cattle.io.project.vue

Fixes https://github.com/harvester/harvester/issues/4981

Use Rancher Resource quotas when not standalone mode

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/detail/harvesterhci.io.host/HarvesterHostBasic.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvester/node.js

Fixes https://github.com/harvester/harvester/issues/4840
Etcd nodes changes:
- Hosts list, Status: Cordoned -> Active
- Host details, Role -> Computed Node -> Etcd Node
Status
Role label

Define `etcd` (witness) nodes labels and status

---

pkg/harvester/models/kubevirt.io.virtualmachine.js

Fixes https://github.com/harvester/harvester/issues/4982

Add `Unschedulable` state to VM model

---

pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
pkg/harvester/store/harvester-common.js

Fixes https://github.com/harvester/harvester/issues/5014
In case of Http errors during image uploads, the UI shows the error in images table.

Show image upload errors

---

pkg/harvester/config/settings.js
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

Fixe issue in this comment https://github.com/harvester/harvester/issues/4922#issuecomment-1918087739
Add `support-bundle-expiration` filed in setting page.

feat: add support-bundle-expiration

---

pkg/harvester/list/harvesterhci.io.dashboard.vue
pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/list/harvesterhci.io.storage.vue
pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue
pkg/harvester/list/network.harvesterhci.io.clusternetwork.vue

Fixes https://github.com/harvester/harvester/issues/4989
It fixes columns width and layout of main tables.
Commits may be squashed after the review.
Dashboard -> Events tab
before
after
Hosts
before
after
Advanced -> Storage Classes
before
after
Volumes
before
after
Virtual Machines
before 
after
Networks -> Cluster Networks/Configs , button overlap
before
after

Adjust columns width

---

pkg/harvester/config/types.js
pkg/harvester/dialog/HarvesterVMSnapshotDialog.vue
pkg/harvester/edit/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/edit/harvesterhci.io.vmsnapshot.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/list/harvesterhci.io.vmsnapshot.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue
pkg/harvester/models/harvesterhci.io.virtualmachinebackup.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

Fixes https://github.com/harvester/harvester/issues/5024

Add restore label and remove progress bar when restoring VM snapshots

---

pkg/harvester/config/settings.js
pkg/harvester/config/types.js
pkg/harvester/dialog/HarvesterVMSnapshotDialog.vue
pkg/harvester/edit/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/edit/harvesterhci.io.vmsnapshot.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml
pkg/harvester/list/harvesterhci.io.dashboard.vue
pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/list/harvesterhci.io.storage.vue
pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/list/harvesterhci.io.vmsnapshot.vue
pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue
pkg/harvester/list/network.harvesterhci.io.clusternetwork.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js
pkg/harvester/models/harvesterhci.io.virtualmachinebackup.js
pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
pkg/harvester/models/kubevirt.io.virtualmachine.js
pkg/harvester/store/harvester-common.js

PR backports commits from master into release-harvester-v1.3.0
Fixes #

backport changes for rc2

---

package.json

Let eslint try to fix several lint issues. Run it via `yarn fix`.

Add `fix` script target

---

README.md

Currently, there are some misunderstandings in README about running for development, so I added some detail about it.
But, I'm not sure **standalone mode** and **integration mode** is good enough or not, please help me to check this naming.
Fixes #

fix: development readme

---

pkg/harvester/edit/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/l10n/en-us.yaml

Fixes https://github.com/harvester/harvester/issues/5205
Adding a new field to keep the Mac Address from old VM backup.
Restore/Create new
Restore/Replace Existent

Add KeepMacAddress checkbox to Backup restore page

---

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue

Fixes https://github.com/harvester/harvester/issues/5005

Change `pc` machine-type

---

pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/models/harvester/node.js

Resolves https://github.com/harvester/harvester/issues/5258
- We are changing the behavior of Host's delete action by removing the CAPI machines only; It should trigger the node deletion in the backend then.
- Added a custom prompt to safe confirm the Host to be deleted.
- in case of `capiMachine` is null for the Node, then it deletes the node itself (current behavior).
- Hosts page -> delete actions (menu and bulk)
Confirmation dialog
Capi machines delete

Remove Capi Machines when deleting Hosts

---

pkg/harvester/mixins/harvester-vm/impl.js

Resolves https://github.com/harvester/harvester/issues/5264

Handle VMs without volumes

---

pkg/harvester/dialog/EnablePassthrough.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/DeviceList.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/index.vue
pkg/harvester/list/devices.harvesterhci.io.pcidevice.vue
pkg/harvester/models/devices.harvesterhci.io.pcidevice.js
shell/components/ResourceTable.vue

Resolves https://github.com/harvester/harvester/issues/5061

[backport] Make inputRows reactive in IPC devices

---

pkg/harvester/models/kubevirt.io.virtualmachine.js

Resolves https://github.com/harvester/harvester/issues/5284

[backport] Add Unschedulable state to VM model

---

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue

Removing overseeded comments, see https://github.com/harvester/dashboard/pull/970#pullrequestreview-1925144736

Clean up comments

---

pkg/harvester/edit/harvesterhci.io.keypair.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue

Fixes https://github.com/harvester/harvester/issues/5342
The `FileSelector` added one more newline char, we could just trim it. 
https://github.com/harvester/dashboard/assets/6960289/8a25aa56-d573-45c8-b340-c3c483cbe56e

fix: trim the public key content

---

pkg/harvester/formatters/HarvesterMigrationState.vue

Related issue: https://github.com/harvester/harvester/issues/5526
Adding some safe checks to avoid undefined errors when `HarvesterMigrationState` component is loaded by Harvester - embedded mode.
- Virtual Machines table
Before:

Revisit `HarvesterMigrationState` component

---

pkg/harvester/edit/harvesterhci.io.keypair.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue

https://github.com/harvester/harvester/issues/5342
Currently, it only parses string which contains `@`, but the request also means we should parse string which doesn't contain `@` from file or pasted string.
https://github.com/harvester/dashboard/assets/6960289/0981e0cf-c130-4ae1-84bc-016eaff1c420

fix: parsing ssh pub stirng

---

pkg/harvester/list/devices.harvesterhci.io.vgpudevice.vue

Fix the missing vGPU Devices title in Advanced ->  vGPU Devices page.
Fixes # https://github.com/harvester/harvester/issues/5604
**before**
**after**

Add the missing vGPU Devices title in page

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue

Related issue: https://github.com/harvester/harvester/issues/5419
It adds namespace creation in `VirtualMachineSSHKey` component, for both pages:
- Create Virtual Machines
- Create Virtual Machines templates

Create namespace when adding new SSH keys to Virtual Machines

---

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue

Blocked by https://github.com/harvester/dashboard/pull/1012
The label fields should be disabled in Config view

Add mode input to labels fields

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/dialog/RestoreSnapshotDialog.vue

1. install env: https://github.com/harvester/harvester/issues/2405#issuecomment-1549634520
2. Create a volume with non-default storageClass
3. Use volume to generate snapshots
4. Restore the volume using a snapshot
Fixes #
- https://github.com/harvester/harvester/issues/3949

filter storageClass by provisioner

---

pkg/harvester/components/settings/auto-rotate-rke2-certs.vue
pkg/harvester/config/settings.js
pkg/harvester/l10n/en-us.yaml

Related issue: https://github.com/harvester/harvester/issues/5176
Related issue: https://github.com/harvester/harvester/issues/5176
Adding a new setting
Settings page
Show setting details
Edit page

Add new `auto-rotate-rke2-certs` setting

---

pkg/harvester/detail/network.harvesterhci.io.vlanconfig.vue
pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue

Related Issue: https://github.com/harvester/harvester/issues/4197
Adding sorting functionality to:
- Hosts table
- Virtual Machines table

Sort by Host Ip / I Address

---

shell/assets/styles/base/_variables.scss
shell/components/nav/NamespaceFilter.vue

Related issue https://github.com/harvester/harvester/issues/5663
We introduced a regression to LabeledSelect in https://github.com/harvester/dashboard/pull/956 globally
This change will partially revert the z-index changes in 956 and keep working the namespace filter layout.
- To check if bugFixing in https://github.com/harvester/harvester/issues/5155 is still valid
- Test the vGPU filter

Adjust dropdown elements z-index globally

---

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue

Related issue https://github.com/harvester/harvester/issues/5887
Resolved by passing the errors from EditImage component to the CruResource to by displayed on top

Show up errors from cru-resource component when editing images

---

pkg/harvester/components/VMConsoleBar.vue

The console window will be resized to the screen dimensions - 200px. 
Related Issue  https://github.com/harvester/harvester/issues/2467

Adapt console window to the screen

---

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue

Related Issue https://github.com/harvester/harvester/issues/5378

Trim URL field

---

pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/l10n/en-us.yaml

Related Issue https://github.com/harvester/harvester/issues/6067
Before
After
Available NPT server name
Empty NPT server name

Remove empty code formatted label from Host  NTP warning label

---

pkg/harvester/list/kubevirt.io.virtualmachine.vue

Related Issue https://github.com/harvester/harvester/issues/5795

VM Restore column label

---

pkg/harvester/components/HarvesterUpgrade.vue
pkg/harvester/models/harvesterhci.io.upgrade.js

Related Issue https://github.com/harvester/harvester/issues/6144

Hide Upgrade button when upgrade is in progress

---

pkg/harvester/dialog/HarvesterMaintenanceDialog.vue
pkg/harvester/l10n/en-us.yaml

Related Issue https://github.com/harvester/harvester/issues/4888

Improve the UX of non-migratable VMs in node maintenance mode

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/l10n/zh-hans.yaml

Updated links pointing to old 1.1 and 1.2 release documentation.
Just links on lables
None

Fixed links to documents from old Harvester versions

---

pkg/harvester/dialog/HarvesterMigrationDialog.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/kubevirt.io.virtualmachine.js

Related Issue https://github.com/harvester/harvester/issues/6591
It filters the nodes only if VM has Cpu pinning enabled.

Fix Node list in VMs Migrate dialog

---

pkg/harvester/l10n/en-us.yaml

https://github.com/harvester/harvester/issues/6057

l10N: add the harvester-csi-driver-lvm description

---

pkg/harvester/dialog/HarvesterQuotaDialog.vue

Add `edit` mode

---

pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v1.vue
pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v2.vue
pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.volume.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js

Related Issue https://github.com/harvester/harvester/issues/6685
- Removing 'Export to Image' action for Longhorn V2 volumes.
- Disable 'Size' inputBox for Longhorn V2 volumes in edit mode and add a warning banner - both Volumes and Virtual Machines page.
- Disable 'Volume Encryption' section in Storage Class create page.
- TBD if we want to clean up removed disks from history.
Volume edit
VM's Volume edit

Host local storage support, enhancements

---

pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
pkg/harvester/list/kubevirt.io.virtualmachine.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js
pkg/harvester/models/harvester/storage.k8s.io.storageclass.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

Related Issue https://github.com/harvester/harvester/issues/6685

Remove "Take Snapshot" action for Longhorn V2 Storage Classes

---

pkg/harvester/models/harvester/persistentvolumeclaim.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

- LVM CSI driver support clone operation, so we add it capability back
Related Issue # https://github.com/harvester/harvester/issues/6762

feat: add clone capability back for LVM volume

---

pkg/harvester/components/SettingList.vue
pkg/harvester/config/settings.js
pkg/harvester/l10n/en-us.yaml

Related Issue https://github.com/harvester/harvester/issues/5274
This is due to the V2 engine not yet being feature complete.

feat: Change LH V2 enablement from Preview to Experimental

---

pkg/harvester/l10n/en-us.yaml

Related Issue https://github.com/harvester/harvester/issues/6901

Update upgrade steps link

---

pkg/harvester/dialog/HarvesterSupportBundle.vue

Remove typo

---

README.md
shell/pages/auth/setup.vue

Minor fixes

---

pkg/harvester/edit/harvesterhci.io.logging.output.vue

- https://github.com/harvester/harvester/issues/3877
- https://github.com/harvester/harvester/issues/7063
Create output
https://github.com/user-attachments/assets/7f970348-e06f-4ee9-b50a-57409b9e4f73
Edit output
https://github.com/user-attachments/assets/051b3685-73ee-4dff-9070-07d4f7287e36

Filter provider spec in output / cluster output pages

---

README.md

Add important note in README.md. 

Add important note in README.md

---

.github/workflows/test.yaml
shell/creators/pkg/files/.github/workflows/build-extension.yml

Fix CI error from https://github.com/harvester/dashboard/pull/1272.

update actions/upload-artifact to v4

---

pkg/harvester/components/settings/backup-target.vue
pkg/harvester/l10n/en-us.yaml

Port the PR change harvester/dashboard
https://github.com/harvester/harvester-ui-extension/pull/166
https://github.com/harvester/harvester/issues/7694

Add refreshIntervalInSeconds in backup target edit page
