harvester/dashboard

config/types.js, list/harvesterhci.io.dashboard/index.vue, pages/prefs.vue
https://github.com/harvester/harvester/issues/1147
- Hide landing option and helm chart option on pref page.
- Fix dashboard metrics is incorrect
=> HARVESTER:fix:dashboard metrics is incorrect

edit/host/index.vue
https://github.com/harvester/harvester/issues/1208
`addedToNodeCondition` is false when the disk has not been added to the node.
=> HARVESTER:fix:No disk shows up when plugging a new disk to add to host

assets/styles/themes/_light.scss, assets/translations/en-us.yaml, components/ResourceDetail/Masthead.vue, components/ResourceDetail/index.vue, components/nav/TopLevelMenu.vue, config/product/harvester-manager.js, config/product/harvester.js, edit/harvesterhci.io.cloudtemplate.vue, edit/harvesterhci.io.host/index.vue, edit/harvesterhci.io.keypair.vue, edit/harvesterhci.io.setting/backup-target.vue, edit/harvesterhci.io.virtualmachinetemplateversion.vue, edit/harvesterhci.io.volume.vue, edit/kubevirt.io.virtualmachine/VirtualMachineCpuMemory.vue, edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/base.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/container.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue, edit/kubevirt.io.virtualmachine/index.vue, edit/management.cattle.io.fleetworkspace.vue, list/harvesterhci.io.dashboard/HarvesterUpgrade.vue, list/harvesterhci.io.management.cluster.vue, models/harvester/configmap.js, models/harvester/node.js, models/harvester/persistentvolumeclaim.js, store/type-map.js
- Fixed some low hanging fruit (side nav width, icon sizing, component names)
- Fixed SSR issues when working with virtualType showMenuFun
- Only show `Virtualisation Management` link if user has access to provisioning clusters AND the harvester feature flag is enabled
- Fixed a couple of Dashboard 'todo's regarding how virtualType resources are used
- Fixed warning on build
- Add a tech preview notice as per https://github.com/rancher/dashboard/issues/4028
- Fix issue where cluster's `Manage` button was disabled if the cluster wasn't up yet (user could not see reg command)
See each commit messages for more detail
I hope the code looks good, but it really needs another test mostly when in single cluster mode
=> Tweak a number of items from Dashboard review

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, detail/harvesterhci.io.host/HarvesterHostDisk.vue, detail/harvesterhci.io.host/index.vue, edit/harvesterhci.io.host/HarvesterDisk.vue, edit/harvesterhci.io.host/index.vue
https://github.com/harvester/harvester/issues/1240
https://github.com/harvester/harvester/issues/1237
- Add `spec.fileSystem.forceFormatted`, If `status.deviceStatus.fileSystem.lastFormattedAt` exsits or path can not edit, disabel selection.
- If a disk has not yet been mounted and did not have a mount path, generate a unique random path with prefix /var/lib/harvester/extra-disks/ and pre-fill it. E.g. /var/lib/harvester/extra-disks/deadbeef123
=> Harvester:fix:Additional disk is not visible unless manually formatted

assets/translations/zh-hans.yaml, detail/harvesterhci.io.host/HarvesterHostDisk.vue, edit/harvesterhci.io.host/HarvesterDisk.vue, edit/harvesterhci.io.host/index.vue
default value of spec.forceFormatted:
- if status.deviceStatus.fileSystem exists ->  false  (since it has a filesystem, user can provision it directly without formatting)
- otherwise,
- if status.deviceStatus.partitioned == false -> true (User should format it before provisioning)
- if status.deviceStatus.partitioned == true -> false (User should provision its partitions instead)
=> HARVESTER:Add host disk force formatted params

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, edit/harvesterhci.io.host/HarvesterDisk.vue, edit/harvesterhci.io.host/index.vue
- either block device or partition's status.deviceStatus.fileSystem.type  exist -> false, other must be true
- fileSystem type must equal to ext4 or XFS (as longhorn only support those two types, otherwise it should be default to true of force-formatted
- Add notification after user modified the host configs https://github.com/harvester/harvester/issues/1284
=> HARVESTER:fix:Add notification after user modified the host configs

edit/harvesterhci.io.host/HarvesterDisk.vue
When UI set forceFormatted to true and not allowed user modified, "yes" should not be disabled.
=> HARVESTER:UX enhancement

components/ButtonDropdown.vue, edit/harvesterhci.io.host/index.vue, models/harvester/harvesterhci.io.blockdevice.js
https://github.com/harvester/harvester/issues/1282#issuecomment-930879383
- Group disk.
- Disable add disk when child partition is provisioned.
Change `|--` to `-`:
=> HARVESTER: Add disk grouped

edit/harvesterhci.io.host/index.vue
- https://github.com/harvester/harvester/issues/1608
[No disk selected]
[Parent disk(sdc) selected]
[Child disk(sdc1) selected]
[All child disks(sdc1 and sdc2) selected]
=> HARVESTER: Fix parent/child disk selected issue

detail/harvesterhci.io.host/HarvesterHostBasic.vue, detail/harvesterhci.io.host/index.vue, edit/harvesterhci.io.host/index.vue, list/harvesterhci.io.dashboard/index.vue, list/harvesterhci.io.host/index.vue
- [https://github.com/harvester/harvester/issues/1841](https://github.com/harvester/harvester/issues/1841)
- HCI.NODE_NETWORK _network tab on Host page_
- HCI.BLOCK_DEVICE _disk tab on Host page_
- METRIC.NODE _capacity section on Dashboard page_
=> HARVESTER: Hide capacity & disks & networks for member roles

assets/translations/en-us.yaml, edit/harvesterhci.io.host/HarvesterDisk.vue, edit/harvesterhci.io.host/index.vue
**Link issue**
- https://github.com/harvester/harvester/issues/1839
**Change**
According to [issue comment](https://github.com/harvester/harvester/issues/1839#issuecomment-1049516424)
- Only show block device which type is disk
- When the disk is formatted and the system exists, the format option is disabled, and show a banner to info the user what the system is and can be formatted manually.
**Verify Steps**
A disk without format: 
1. Add a new disk
2. Check formate option. Option should be force format.
A disk is formated and the filesystem exits
1. Add a new disk
2. remove the disk
3. Add the disk again
4. Check the banner
A disk is formated manually
1. Format disk. e.g. `mkfs.ext4 /dev/nvme0n1`
2. Add the disk
3. Check the format option
**Additional Context**
=> HARVESTSER: Support add a disk insteadof a partition

edit/kubevirt.io.virtualmachine/index.vue, mixins/harvester-vm/index.js
- [https://github.com/harvester/harvester/issues/1989](https://github.com/harvester/harvester/issues/1989)
1. Create VM `A`
2. Add Access Credentials to VM `A`, use credentials could access VM `A`.
3. Generate VM Template from VM `A`.
4. Lanuch new VM `B` from the VM Template, VM B should not have the credentials.
_we intend to implement the enhancement in 1.0.2 that VMs created by VM templates include credentials_
5. Clone VM `A`, should clone successfully and credentials should be saved in new Secret.
6. Go to VM Create Page
7. Use template to create VM `C`, should create successfully.
8. Add Access Credentials to `B`, should add successfully.
9. Add Access Credentials to `C`, should add successfully.
10. Remove Access Credentials of `B`, should remove successfully.
11. Remove Access …
=> HARVESTER: VM created by VM Template will use new secret

edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/base.vue
Hardware part is not supported now, related tracking issue https://github.com/harvester/harvester/issues/992，
After discussion, the frontend temporarily removed the `sriov` configuration
=> HARVESTER: remove sriov type

components/ResourceDetail/Masthead.vue, config/product/harvester.js, store/type-map.js
https://github.com/harvester/harvester/issues/1978 
This PR hides the 'config' view for backups. The ResourceDetail Masthead renders the 'Detail' and 'Config' buttons when the resource has components defined in `/view` and `/edit` respectively: this is not appropriate for `harvesterhci.io.virtualmachinebackup` because the `/edit/harvesterhci.io.virtualmachinebackup` component is for the creation of `harvesterhci.io.virtualmachinerestore` resources. Initially I thought to restructure the backup/restore components to align with the assumptions made in ResourceDetail and type-map but it required _many_ changes just to hide a button so I think this approach of making type-map and ResourceDetail more configurable is better.
=> HARVESTER: hide view config for backup

components/VMConsoleBar.vue
- [https://github.com/harvester/harvester/issues/1938](https://github.com/harvester/harvester/issues/1938)
1. Create VM A
2. The console bar of VM A would only be disabled when VM A is stopped.
3. open VNC console / Serial console on any phase of VM, UI should work fine.
=> HARVESTER: VM console only disabled when VM is stopped

store/index.js
https://github.com/harvester/harvester/issues/2001
On initial load in cluster explorer, project/namespace filtering is loaded from user preferences in `loadCluster` [here](https://github.com/harvester/dashboard/blob/master/store/index.js#L708-L715) - `loadVirtual` was missing this.
=> HARVESTER: fix project/ns filter on page reload

shell/list/namespace.vue, shell/pages/c/_cluster/_product/projectsnamespaces.vue, shell/store/index.js
test step:
1. In a single cluster, the data displayed on the namespace page should be consistent with the namespace filter data on all edit pages
2. In multiple clusters, the data displayed on the 'Projects/Namespaces' page should also be consistent with the namespace data used elsewhere.  (Note that the projects/Namespace page in the development environment shows all namespaces)
Fixes #
- https://github.com/harvester/harvester/issues/2116
=> Fix multiple cluster namespace filter

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue, shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, shell/mixins/harvester-vm/index.js, shell/utils/validators/vm.js
- https://github.com/harvester/harvester/issues/2212
1. Go to VM template page
2. Create a new version from the build-in templates or create a new template
3. One of the VM volumes should be `Image Volume` and it should be empty
4. Save
5. Repeat step 2 or Go to create a VM
6. Can select a image for the Image Volume
1. Create a new VM
2. Add a container Volume and you can drag it to the first(rootdisk)
3. Create successfully
1. Create a VM template with a image
2. Remove this image
4. Go to VM template edit page
5. Throw error
6. Go to VM create page and use this template
7. Throw error
=> Harvester: Image volume can be empty in VM template

shell/assets/translations/en-us.yaml, shell/components/GrowlManager.vue, shell/models/harvester/node.js, shell/plugins/steve/subscribe.js, shell/store/growl.js, shell/utils/socket.js
https://github.com/harvester/harvester/issues/2186
This PR adds growl notifications when a websocket disconnects and attempts to reconnect. Disconnect growls are sent when an `onclose` websocket event is received and the associated socket wrapper is configured to automatically attempt to reconnect. When a socket reconnects the notification is closed.
https://user-images.githubusercontent.com/42977925/175362950-23fe3ac6-8a89-42be-b6a3-0e959a22679a.mov
=> websocket disconnect growl

shell/config/labels-annotations.js, shell/detail/harvesterhci.io.host/HarvesterHostBasic.vue, shell/list/harvesterhci.io.dashboard/index.vue, shell/list/harvesterhci.io.host/index.vue, shell/models/harvester/node.js
Fixes Cluster member and cluster owner see inconsistent statistics
- https://github.com/harvester/harvester/issues/2310
- Hide the storage gauge if the user has no auth request Longhorn API
- Node Reserved value obtain from node annotation, Cluster reserved is the total of node reserved.
This PR will release to `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`, and it requires the latest Harvester version.
Case 1:
1. Login with admin/cluster member on rancher
- Check the Dashboard CPU, memory, and storage
- Check the Host list/detail CPU, memory, and storage
Case 2:
1. Login with admin on Harvester
- Check the Dashboard CPU, memory, and storage
- Check the Host list/detail CPU, memory, and storage
=> HARVESTER: Cluster member and cluster owner see inconsistent statistics

shell/config/labels-annotations.js, shell/detail/harvesterhci.io.host/HarvesterHostBasic.vue, shell/list/harvesterhci.io.dashboard/index.vue, shell/list/harvesterhci.io.host/index.vue, shell/models/harvester/node.js
Fixes Cluster members and cluster owners see inconsistent statistics
- https://github.com/harvester/harvester/issues/2386
- Hide the storage gauge if the user has no auth request Longhorn API
- Node Reserved value obtain from node annotation, Cluster reserved is the total of node reserved.
This PR will release to `https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html`, and it requires the latest Harvester version.
Case 1:
1. Login with admin/cluster member on rancher
- Check the Dashboard CPU, memory, and storage
- Check the Host list/detail CPU, memory, and storage
Case 2:
1. Login with admin on Harvester
- Check the Dashboard CPU, memory, and storage
- Check the Host list/detail CPU, memory, and storage
=> [Backport V1.0] HARVESTER: Cluster member and cluster owner see inconsistent statistics

shell/edit/harvesterhci.io.host/HarvesterDisk.vue, shell/edit/harvesterhci.io.host/index.vue
Fixes unable to add addition disks on Host
- https://github.com/harvester/harvester/issues/2551
- Allow the disk with partitions option can be select
- Force formatted is required for the disk with a partitions
=> HARVESTER: Fix unable to add addition disks on Host

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/components/dialog/harvester/ConfirmRelatedToRemoveDialog.vue, shell/models/harvester/namespace.js
- https://github.com/harvester/harvester/issues/2591
1. Go to Projects/Namespaces page
2. Remove one or more namespaces
3. The warning tips `Deleting the Namespace(s) will remove all the resources on this particular Namespace(s) and this is not revertable, are you sure you want to continue deleting XXX` should be visible on the dialog
=> Harvester: display more info on deleting namespace dialog

shell/components/CruResourceFooter.vue
Fixes [#2843 ](https://github.com/harvester/harvester/issues/2843)
Update `CruResourceFooter`: this component should never appear underneath others.
=> fix curresource footer so it is never behind form elements

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/DeviceList.vue, pkg/harvester/models/devices.harvesterhci.io.pcidevice.js
Fixes #https://github.com/harvester/harvester/issues/2925
* pci device name in table is no longer clickable
* view as yaml, edit yaml, clone, and delete actions are disabled for pci devices
=> disable view/edit as yaml, clone, and delete actions for pci devices

pkg/harvester/l10n/en-us.yaml, pkg/harvester/l10n/zh-hans.yaml, shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/components/HarvesterServiceAddOnConfig.vue, shell/components/form/WorkloadPorts.vue, shell/edit/service.vue
Fixes #https://github.com/harvester/harvester/issues/2929 in conjunction with:
https://github.com/rancher/dashboard/pull/7187 (2.6.9)
https://github.com/rancher/dashboard/pull/7189 (master)
https://github.com/rancher/dashboard/pull/7190 (2.6.9)
https://github.com/rancher/dashboard/pull/7191 (master)
There are four PRs because I forgot to move the zh-hans translation strings. 
The  service add-on config UI and WorkloadPorts ipam option are available in clusters provisioned on an imported harvester cluster: since these components may be loaded without a harvester plugin having been loaded, the translation strings must stay in `shell`
=> Port harvester service translations

pkg/harvester/l10n/en-us.yaml, pkg/harvester/pages/c/_cluster/support/index.vue
- https://github.com/harvester/harvester/issues/2765
1. Go to support page
2. Both of rancher link and longhorn link will not be visible.
3. Go to user preference page
4. Enable DEV mode
5. Back to support page
6. Both of rancher link and longhorn link will be visible.
7. Click links will open a new tab with rancher/longhorn embedded UI.
=> HARVESTER: add embedded ui of rancher and longhorn ui to support page

pkg/harvester/list/harvesterhci.io.volume.vue, pkg/harvester/models/harvester/persistentvolumeclaim.js
Add longhorn volume ready property
- https://github.com/harvester/harvester/issues/3026
The ready property is imported from https://github.com/longhorn/longhorn-manager/blob/master/api/model.go#L1151
Most of the time the state will show `Degraded`, only the PV annotation did not have `longhorn.io/volume-scheduling-error` the state will shows `Not Ready`.
=> HARVESTER: Add longhorn volume ready property

pkg/harvester/edit/harvesterhci.io.monitoring.alertmanagerconfig/index.vue, shell/assets/translations/en-us.yaml, shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
- https://github.com/harvester/harvester/issues/2798
1. Route tab will only be visible on `AlertmanagerConfig` edit page.
2. Duplicate name of receiver is invalid, can not be created.
=> HARVESTER: duplicate receiver name is invalid now

pkg/harvester/dialog/HarvesterMaintenanceDialog.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/l10n/zh-hans.yaml
Fixes #
- https://github.com/harvester/harvester/issues/2723
1.  https://github.com/harvester/harvester/issues/2723#issuecomment-1430666922
~1. create a Storage Class, change `Number Of Replicas` = 1
2. Upload an image, select the default storageClass
3. Upload an image, select the storageClass you created
4. Use these two images to create a vm respectivel。
5. View the node where the volume of the single vm is located
6.  Set the node to maintenance，  You should see an error prompt
7. If `Force` is checked，the vm should enter the stop state and the node will enter the `Cordon` mode
=> HARVESTER: node maintenance enhancement

shell/components/ExplorerMembers.vue
Cluster members adding project members creates two of the same, so hide it in v1.1.2 and consider letting go of it in v1.2.0
=> HARVESTER: Hide project member

pkg/harvester/list/network.harvesterhci.io.clusternetwork.vue, pkg/harvester/models/network.harvesterhci.io.vlanconfig.js
Fixes VlanConfig state display active but actual is "Not Ready"
- https://github.com/harvester/harvester/issues/3488
=> HARVESTER: Fix VlanConfig state display active but actual is "Not Ready"

pkg/harvester/components/settings/storage-network.vue, pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue, pkg/harvester/models/network.harvesterhci.io.clusternetwork.js, pkg/harvester/models/network.harvesterhci.io.vlanconfig.js, pkg/harvester/models/network.harvesterhci.io.vlanstatus.js
Fix VLAN status issue
- https://github.com/harvester/harvester/issues/3488
- The VLAN status should filter by VLAN config and the selected node name
- Cluster network in storage-network setting also disabled it when its conditions are not ready
=> HARVESTER: Fix vlan status issue

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/base.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/index.vue
Fixes #
- https://github.com/harvester/harvester/issues/3518
When creating or editing a new network, you can switch between networks, but a saved network can only switch between networks of the same type.
When adding a new network, you can switch from `management` type to `vlan` type. When editing an existing network, you can only select the same type of network.
=> HARVESTER: enhancement vm network UX

pkg/harvester/config/settings.js
Fix unable to click the "Use the default value setting" of cluster-registration-url
- https://github.com/harvester/harvester/issues/3505
=> HARVESTER: Fix unable to click the "Use the default value setting" of cluster-registration-url

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/DeviceList.vue, pkg/harvester/formatters/HarvesterVFAddress.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/list/devices.harvesterhci.io.sriovnetworkdevice.vue
Fixes #
https://github.com/harvester/harvester/issues/2763
1. ~`Number Of Virtual Functions` are links now, the page will go to pci device list directly if you click them. And the list should only display the devices belonged this sr-iov.~ (won't implement now)
2. `Virtual Functions Addresses` are also links now, the page will go to pci device list directly if you click them. And there is only one record.
1. Go to SR-IOV list page.
2. Enable one of the SR-IOV devices, set virtual functions as 10.
3. You should be able to click `Show More` to show all vfs addresses.
4. You should be able to redirect to …
=> HARVESTER: add query params for pcidevices list

pkg/harvester/dialog/EnableSriovDevice.vue
* toss out anything less than or equal to zero for the SR-IOV device virtual function addresses
* avoid making an API call out to the endpoint, reducing network chatter
Resolves: github.com/harvester/harvester/issues/3977
Fixes #
=> fix: Toss Out Invalid Amount On VFs For SR-IOV

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue, shell/components/form/UnitInput.vue
Fixes We can set negative integer value to Termination Grace Period field and write into VM yaml
- https://github.com/harvester/harvester/issues/3946
Add positive for UnitInput component
=> HARVESTER: We can set negative integer value to Termination Grace Period field and write into VM yaml

pkg/harvester/config/labels-annotations.js, pkg/harvester/formatters/HarvesterVmState.vue, pkg/harvester/models/kubevirt.io.virtualmachine.js
Add the insufficient resource to vm annotation
- https://github.com/harvester/harvester/issues/3944
Verify Steps:
1. Set over-commit CPU and memory to 100%
2. Create a project with 2000m cpu
3. Create a namespace with 2000m cpu
4. Create 10 VMs with 2cpu and 4Gi
5. Check the error message in VM list
=> HARVESTER: Add the insufficient resource to vm annotation

pkg/harvester/edit/harvesterhci.io.host/HarvesterDisk.vue, pkg/harvester/edit/harvesterhci.io.host/index.vue, pkg/harvester/formatters/HarvesterDiskState.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/models/harvesterhci.io.blockdevice.js
Should give a chance to force format or fsck for the corrupted additional disks
- https://github.com/harvester/harvester/issues/4016
- Allow force format when the disk is corrupted
- Add a banner when the disk is formatting
- Fix disk state
1. Add a disk(e.g. /dev/sda) and then remove it by UI
2. Make the disk corrupted (`dd if=/dev/zero of=/dev/sda bs=512k count=1 oflag=sync`)
3. Add the disk again
=> HARVESTER: Should give a chance to force format or fsck for the corrupted additional disks

pkg/harvester/components/novnc/NovncConsoleCustomKeys.vue, pkg/harvester/components/novnc/NovncConsoleWrapper.vue, pkg/harvester/l10n/en-us.yaml
- https://github.com/harvester/harvester/issues/3989
upstream PR:
https://github.com/rancher/dashboard/pull/9151
1. Go to rancher cluster and then import existing harvester cluster with different roles(like project owner/member and cluster owner/member
2. Use different roles to login and create themselves vm
3. Go to open web vnc window
4. Manage themselves custom shortcut keys
5. The custom shortcut keys is working correctly.
=> HARVESTER: refactor vnc shortcut keys

pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/HealthCheck.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/l10n/zh-hans.yaml
- Fix Load Balancer creation with Health Check creates data-type unmarshalling error
- Change IP pool network label
- https://github.com/harvester/harvester/issues/4135
- https://github.com/harvester/harvester/issues/1458#issuecomment-1608063654
=> HARVESTER: Fix Load Balancer creation with Health Check creates data-type unmarshalling error

pkg/harvester/config/harvester.js, pkg/harvester/l10n/en-us.yaml, pkg/harvester/l10n/zh-hans.yaml
The cluster type remains the same as before, we will remove `rancher-mamage-support` from the setting, and the back end will create an external rancher through `addon` to import the harvester cluster.
Fixes #
=> HARVESTER: fix project-namespace display

shell/components/form/PodAffinity.vue
Update match expressions manually.
**Related upstream PR**
- https://github.com/rancher/dashboard/pull/9238/files
- https://github.com/harvester/harvester/issues/2317#issuecomment-1607255344
=> HARVESTER: fix podAffinity can not update match expressions

pkg/harvester/mixins/harvester-vm/impl.js, pkg/harvester/mixins/harvester-vm/index.js
When only `Booting in EFI mode` is selected, we do not need to pass the `smm` parameter.
Fixes #
- https://github.com/harvester/harvester/issues/4145
=> HARVESTER: fix efi checked

shell/components/form/NameNsDescription.vue
rancher v2.7.4 does not have the allowedNamespaces method, which requires compatibility with `2.7.4` import harvester `v1.2.0`
Fixes #
=> HARVESTER: fix not find allNamespaces in v2.7.4

pkg/harvester/detail/harvesterhci.io.host/HarvesterSeeder.vue, pkg/harvester/edit/harvesterhci.io.host/HarvesterSeeder.vue, pkg/harvester/edit/loadbalancer.harvesterhci.io.ippool/Selector.vue, pkg/harvester/edit/loadbalancer.harvesterhci.io.ippool/index.vue, pkg/harvester/models/loadbalancer.harvesterhci.io.ippool.js, pkg/harvester/models/metal.harvesterhci.io.inventory.js
Fixes #
- Polish seeder state.message 
- Fix the IP pool selector is null
- Fix IP pool edit as YAML without `status`
- https://github.com/harvester/harvester/issues/1458#issuecomment-1617693777
- Update seeder state for API change
- Fix UI render when IP pool selector is null
Seeder Test Plan
- Enable out-of-band Access with an invalid address or secret 
- Check the banner in the host list/edit/detail page
IP pool test plan
- Create an IP pool
- Edit YAML and delete the `selector`
- Check IP pool create/edit
=> HARVESTER: Polish seeder state.message && Fix IP pool selector is null

pkg/harvester/models/harvesterhci.io.addon.js
We want to improve the exhibitions of addon's status.
- https://github.com/harvester/harvester/issues/4067
1. Swtich enabling/disabling status of addon quickly should be failed and you should see the error message on the top-right corner.
2. When enabling/disabling/updating if you edit the configurations of addon and then save, save should be failed and the error message should be also displayed.
=> HARVESTER: improve exhibition of addon's status

pkg/harvester/models/harvesterhci.io.addon.js
- https://github.com/harvester/harvester/issues/4306
=> HARVESTER: replace Failed with OperationFailed

pkg/harvester/edit/harvesterhci.io.addon/index.vue, pkg/harvester/edit/harvesterhci.io.addon/rancher-vcluster.vue, pkg/harvester/models/harvesterhci.io.addon.js
https://github.com/harvester/harvester/issues/2679#issuecomment-1661999312
Add the vcluster addon check.
1. When the user clicks on Enable from the list page, if the hostname is empty, we should jump to the edit page
Fixes #
=> enhancement vcluster addon

pkg/harvester/components/SettingList.vue
https://github.com/harvester/dashboard/assets/24985926/7faa6d20-99be-43f8-8a7d-450b9ac6dd82
setting page hide and show buttons are not clickable。
reproduce step:
1. Configure backup-target, click Save
2. Click on any show or hide button on the setting page.
Fixes #
When the websocket is updated, the `settings` object and the `categorySettings` object are completely unrelated, so changing the value of `this.settings` will not affect the value of categorySettings.
=> fix toggle button can't click

pkg/harvester/models/harvester/persistentvolumeclaim.js
Fix Harvester issue of volume status not-ready.
Fixes #
https://github.com/harvester/harvester/issues/5020
=> Fix volume status Not-Ready

pkg/harvester/edit/management.cattle.io.project.vue
When Harvester UI is loaded as a plugin in Rancher Manager, it loads the Project's component from Rancher `shell` instead of Harvester `shell` library.
This is a work around to load the project's edit page from Harvester package where the Resource Quotas has been fixed.
As a follow up we will need to fix the Projects edit page in Rancher manager `shell` to make it sure that it loads the correct plugins components.
Fixes https://github.com/harvester/harvester/issues/4981
Projects edit/create in embedded Harvester UI.
=> Add Harvester projects edit page

pkg/harvester/edit/harvesterhci.io.addon/nvidia-driver-toolkit.vue, pkg/harvester/l10n/en-us.yaml
Fixes https://github.com/harvester/harvester/issues/5112
it adds fields to specify the nvidia addon settings, when enabling.
Spec fields are hidden when user switch to 'disable' and values are reset.
`nvidia-driver-toolkit` addon edit / view page
Edit 
View
=> Handle `nvidia-toolkit-driver` addon spec

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js, pkg/harvester/validators/hash.js, pkg/harvester/validators/index.js
- Add validator at model level (legacy) because the whole page is not using form field validators.
Fixes https://github.com/harvester/harvester/issues/5141
=> Allow adding `Checksum` when creating a new image from URL

pkg/harvester/edit/harvesterhci.io.addon/rancher-monitoring.vue
Fixes https://github.com/harvester/harvester/issues/5217
It adds the `orgId=1` query param to the Addon page -> Grafana link.
=> Add `orgId` to Grafana link

pkg/harvester/formatters/HarvesterBackupProgressBar.vue, pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue, pkg/harvester/models/harvesterhci.io.virtualmachinebackup.js
Harvester should show progress info only for backups containing those info, (created in >= `v1.3.0`).
Resolves https://github.com/harvester/harvester/issues/5068/
Relevant change:
```
percentage: this.status?.progress === undefined && !this.status?.readyToUse ? 0 : this.status?.progress,
```
Cases:
- `status.progress` is undefined and `status?.readyToUse` is false: It means that new backup has not received the progress info yet but it will do; the progress bar should show `0`
- `status.progress` is undefined and `status?.readyToUse` is true: It is a backup created in v1.2.x; It should show dash character …
=> Hide progress bars for VM Backup Created before v1.3

pkg/harvester/models/kubevirt.io.virtualmachine.js
This pr fix click view logs option on vm dashbaord can't display log entry issue.
related to https://github.com/harvester/harvester/issues/5266
[Screencast from 2024-03-04 11-11-29.webm](https://github.com/harvester/dashboard/assets/4344302/a744a176-7b95-40c1-86cd-1670d65f08f7)
=> Fix click view logs option on vm dashboard can't display log entry

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue, pkg/harvester/mixins/harvester-vm/impl.js, pkg/harvester/mixins/harvester-vm/index.js, pkg/harvester/models/kubevirt.io.virtualmachine.js, pkg/harvester/utils/vm.js, pkg/harvester/validators/vm.js
Resolves https://github.com/harvester/harvester/issues/5264
Volumes array can be null in several places, causing an error when accessing the VM's edit and view pages.
- It returns empty array in case of volumes annotations are empty.
- Code refactoring to parse volumes annotations in one place - `parseVolumeClaimTemplates`.
Virtual Machine's main views:
- edit
- create
- view
=> Volumes list refactoring in VM model

pkg/harvester/edit/harvesterhci.io.addon/rancher-monitoring.vue
Related issue https://github.com/harvester/harvester/issues/5217
Removing `orgId` from Grafana link as not required in Harvester v1.3.0
=> Revert orgId from Grafana link

README.md, pkg/harvester/store/harvester-store/actions.ts, shell/store/index.js
Open the related issue in `harvester` repo.
This is a porting of `shell` code changes from `rancher/dashboard` code base to preserver the compatibility in embedded mode with Rancher UI `v2.9-head`.
Related issue https://github.com/rancher/dashboard/issues/10647
The `getters` paramter has been added to `updateNamespaces` in the shell package, in Rancher code base.
The `updateNamespaces` function from Rancher store's shell, where `getters` is required, is overlapping the one in Harvester shell when using it in embedded mode.
The `getters` param is always null in Harvester store, since it is not pushing the …
=> Add getters argument to `updateNamespaces` store function

pkg/harvester/edit/harvesterhci.io.addon/rancher-monitoring.vue
Fixes #
With the new PR https://github.com/harvester/harvester-installer/pull/681 to bump `rancher-monitoring` in Harvester v1.2.2, the embedded Rancher was also bumped to v2.8.2.
The current UI will have such error:
After remove `/?orgId=1` from the link, it works.
```
<a data-v-778364ee="" data-v-590b7fec="" href="/k8s/clusters/local/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1" target="_blank" rel="noopener nofollow"> ...
```
=> [release-v1.2] Remove orgId param in grafana link

pkg/harvester/components/novnc/NovncConsole.vue, shell/assets/translations/en-us.yaml
Related Issue: https://github.com/harvester/harvester/issues/2242
Currently, after disconnecting, our vnc doesn't automatically connect. Users need to refresh page to connect it again.
I checked the [official demo of noVNC](https://novnc.com/noVNC/vnc.html) about how to reconnect , you could check [source code](https://novnc.com/noVNC/app/ui.js). It reconnects the vnc after disconnecting event happens. So I use similar way to do reconnecting.
${\color{red}\text{I just added a very simple sentence to tell users VNC is reconnecting, please let me know if there is a better prompt}}$
About how to reproduce …
=> feat: reconnect after disconnecting

pkg/harvester/edit/harvesterhci.io.volume.vue, pkg/harvester/mixins/harvester-vm/index.js, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Related issue https://github.com/harvester/harvester/issues/5551
Populating volumeClaimTemplates with vmimage.status.storageClassName intead of `"longhorn-${imageId}"`
=> Using vmimage.status.storageClassName to fill volumeClaimTemplates

pkg/harvester/edit/harvesterhci.io.volume.vue, pkg/harvester/mixins/harvester-vm/index.js, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Related issue https://github.com/harvester/harvester/issues/5586
=> Using vmimage.status.storageClassName to fill volumeClaimTemplates (backport #986) 

pkg/harvester/components/novnc/NovncConsole.vue, shell/assets/translations/en-us.yaml
Related Issue: https://github.com/harvester/harvester/issues/2242
Currently, after disconnecting, our vnc doesn't automatically connect. Users need to refresh page to connect it again.
I checked the [official demo of noVNC](https://novnc.com/noVNC/vnc.html) about how to reconnect , you could check [source code](https://novnc.com/noVNC/app/ui.js). It reconnects the vnc after disconnecting event happens. So I use similar way to do reconnecting.
${\color{red}\text{I just added a very simple sentence to tell users VNC is reconnecting, please let me know if there is a better prompt}}$
About how to reproduce …
=> feat: reconnect after disconnecting (manual backport #984)

pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/HealthCheck.vue, pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/Listeners.vue, pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/index.vue, pkg/harvester/l10n/en-us.yaml
Related issue https://github.com/harvester/harvester/issues/5444
The `listeners.backendPort` is used instead of `listeners.port`, when selecting the port in Health Check tab.
- Changing the port data source
- Fixing an issue in Health Check tab: when disabling the Health Box, old fields remain filled in the Load Balancer object (and YAML).
- Adding a warning message to notice the users when a backend port in Listeners tab is used in Heath Check.
Backend port 5000
Port options in Health Check tab
Warning message in Listeners when port 5000 is select in Health Box
=> Get `backendPort` as options in Health Check in Load Balance

pkg/harvester/components/novnc/NovncConsoleCustomKeys.vue
The div.action justify-context should use `flex-end` to suppress below warning
**Before**
**After**
Checked on latest version of 
- Chrome  ✅ 
- Edge ✅ 
- Firefox ✅
=> Avoid yarn dev warning caused by nonvnc console custom key action style

pkg/harvester/models/devices.harvesterhci.io.vgpudevice.js
Related issue https://github.com/harvester/harvester/issues/5293
`this.$store.dispatch('growl/fromError'...`  is wrong, it should be just `this.$dispatch(...`, so it wasn't display the API errors; It will also need to restore the `spec` values in case of errors.
- vGPU Devices page
=> Change the vGPU model to show backend errors properly

pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js, pkg/harvester/models/kubevirt.io.virtualmachine.js
Related issue https://github.com/harvester/harvester/issues/5495
=> Change default eviction strategy to LiveMigrateIfPossible

pkg/harvester/detail/kubevirt.io.virtualmachine/VirtualMachineTabs/VirtualMachineBasics.vue
Fix too long vm name to overlap the console button
Fixes # https://github.com/harvester/harvester/issues/5730
The console button in the VM details page overlaps other elements in the right column if VM name is too long.
Since the VM name max width is 63 chars. This PR just moves the console button to the top right corner.
**After fix**
=> fix: too long vm name to overlap the console button

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue, shell/assets/translations/en-us.yaml, shell/components/form/KeyValue.vue
In Images -> Create -> Labels, follow the tooltip Paste `lines of key=value` or `key:value` into any key field for easy bulk entry and try to paste key=value lines, but not convert to lables automatically.
Fixes # https://github.com/harvester/harvester/issues/4206
KeyValue.vue natively have **onPaste logic** l to convert multi-lines into key:value map.
But have error logic to support `:` separator.
Check this change also fix
- Virtual Machine -> Create ✅ 
- Network -> Load Balancer -> Create  ✅ 
- Image -> Create ✅
e.g. paste in key field
```
user-firstname=Andy Lee 
user-lastname=aaa
user-id:123
```
=> fix: onPaste separator logic in KeyValue.vue

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue
Remove `Select a Template` option from user data and network data template dropdown.
Fixes # https://github.com/harvester/harvester/issues/4243
=> Remove Select a Template from user data and network template option

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
According to the issue discussion [q35 is alias for always the latest pc-q35-version supported by version of qemu](https://github.com/harvester/harvester/issues/5437#issuecomment-2103748513).  
Remove `pc-q35` machine type option on GUI.
**Steps to reproduce the behavior:**
1. Navigate to `VM create page` -> `Advance options`
2. Create VM vm1 with machine type `pc-q35`
Note. this change needs to backport to 
- release-harvester-v1.3
- release-harvester-v1.2
Fixes # https://github.com/harvester/harvester/issues/5437
=> Remove pc-q35 machine type option

pkg/harvester/dialog/EnableVGpuDevice.vue
Related issue https://github.com/harvester/harvester/issues/5775
It disables the save button if vGpu type is empty.
1- Navigate to vGPU Devices
2- Select a vGPU with missing vGPU type
3- Click Enable
4- The save button should be disabled
vGPU devices tab
=> Disable Save button when vGPU type is empty

pkg/harvester/validators/vm.js, pkg/harvester/validators/volume.js
Fix inconsisteny error msg in create volume page
**Steps to reproduce the behavior:**
1. Go to Volume -> Create
2. Assign the volume name and leave the Size field empty.
3. Click on Create button
Fixes # [[BUG] Volume - create page, validation errors inconsistency](https://github.com/harvester/harvester/issues/5733)
=> Correct inconsisteny error message in create volume page

pkg/harvester/l10n/en-us.yaml
The checkbox text is not starting with an upper case. This PR is fixing that issue.
1. Select the `Clone` action menu on any existing VM.
2. In the displayed dialog, the `Clone volume data` text of the checkbox must start with an upper case character.
=> Start the checkbox text in capital letters

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue, pkg/harvester/models/network.harvesterhci.io.vlanconfig.js
Per discussed with @Vicente-Cheng , we should filter out `witness node` when creating cluster rnetwork config.
Fixes #
[[BUG] Unable to select NIC to create network config when cluster contains witness node](https://github.com/harvester/harvester/issues/5325)
**1 default + 1 witness node**
**2 default  + 1 witness node**
=> Filter out witness node when creating cluster network config

.github/pull_request_template.md
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
Remove keyword to prevent PR from being linked to `Development` section of issue automatically.
=> chore: remove PR description keyword to link issue Development

pkg/harvester/config/settings.js, pkg/harvester/l10n/en-us.yaml, pkg/harvester/l10n/zh-hans.yaml
Rancher 2.8.x introduced a new setting for kubeconfig ttl. The default value for the setting is 30 days. As a result admin kubeconfig generated from Harvester expires in 30 days since this leverages the embedded rancher.
This PR provides the UI part for https://github.com/harvester/harvester/pull/5896
https://github.com/harvester/harvester/issues/5977
=> Expose kubeconfig ttl setting in Harvester

pkg/harvester/edit/harvesterhci.io.host/index.vue
Since witness node doesn't have CRD `nodes.longhorn.io`.  [longhornNode()](https://github.com/a110605/harvester-dashboard/blob/5ac7d8e4b061ba69b304703fbfc5f01e0f842154/pkg/harvester/edit/harvesterhci.io.host/index.vue#L213) got `undefined`. Skip  saveLonghornNode if longhornNodes is undefined to avoid error.
https://github.com/harvester/harvester/issues/5326
**harvester-node-1 is witness node.**
=> Fix undefined save error when editing witness node labels

pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
When users choose the third node selector, if input non matched rule, we should show zero match.
Since we remove witness node from [previous PR](https://github.com/harvester/dashboard/pull/1031), if user input rule 
```
kubernetes.io/hostname : harvester-node-1
```
we should show zero match.
We should also NOT show any match node if user input non-existed kubernete.io/hostname
https://github.com/harvester/harvester/issues/5325
After fix
=> Fix non-matched rule show matched nodes in create cluster network page

pkg/harvester/config/harvester-map.js, pkg/harvester/config/labels-annotations.js, pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/mixins/harvester-vm/index.js, shell/config/labels-annotations.js
Related Issue https://github.com/harvester/harvester/issues/5888
- `Instance Labels` and `Advanced Options` tabs have been rearranged to a different position; Advanced tab is now at the bottom of the list of VM tabs.
- It adds the dropdown element to select the Maintenance Strategy label.
- The label is excluded from `Instance Labels` tab
=> VM Maintenance Strategy

pkg/harvester/config/labels-annotations.js, pkg/harvester/models/harvester/persistentvolumeclaim.js
Related Issue https://github.com/harvester/harvester/issues/5905
- We are removing `harvesterhci.io/owned-by` label from UI.
- Attached VM is now calculated by iterating through the VMs volume list -> `vm.spec.template.spec.volumes`
=> Remove `harvesterhci.io/owned-by`

pkg/harvester/models/harvester/node.js
Allow all URL schemas for custom console URLs. This change removes a check that enforces the 'Console' button of a Harvester node to only redirect to URLs starting with `http://` or `https://`. Otherwise it will prepend `http://` to the configured URL. This breaks non-HTTP URL schemas like `vnc://` or `rtsx://`, which are sometimes used to launch custom VNC viewers instead of using the built-in one.
fixes: https://github.com/harvester/harvester/issues/6042
- Is this a multi-tenancy feature/bug? No.
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1? No.
- Are backend engineers aware of UI changes? No backend change associated with this fix.
https://github.com/harvester/harvester/issues/6042
=> UI: allow all URL schemas for custom console URLs

pkg/harvester/list/kubevirt.io.virtualmachine.vue, pkg/harvester/models/kubevirt.io.virtualmachine.js
Related Issue https://github.com/harvester/harvester/issues/6195
- Test Snapshot restores.
- Test Backups restores.
=> Hide restore column when completed

pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue, pkg/harvester/edit/harvesterhci.io.host/HarvesterDisk.vue, pkg/harvester/edit/harvesterhci.io.host/index.vue, pkg/harvester/l10n/en-us.yaml
- Allow user to enable / disable node disk scheduling in node page -> Edit Config -> storage tab.
- View the disk scheduling in node detail page storage tab.
https://github.com/harvester/harvester/issues/5836
This PR should be backport to v1.4 and v1.3
https://github.com/user-attachments/assets/8957120b-e520-4e97-912a-6af53462bf0d
=> Allow user to enable / disable node disk scheduling

pkg/harvester/config/labels-annotations.js, pkg/harvester/detail/network.harvesterhci.io.vlanconfig.vue
Per discussion this [comment](https://github.com/harvester/harvester/issues/5325#issuecomment-2236668074) with team, we decide to filter out witness node from backend annotation when creating network config via `select all nodes`.
Frontend only honors annoation `network.harvesterhci.io/matched-nodes` to show selected nodes in page.
Note. we will have backend PR to filter out witness node in `annotaton.network.harvesterhci.io/matched-nodes`.
Note. this PR needs backport to v1.3.1 and v1.4
https://github.com/harvester/harvester/issues/5325
=> fix: honor annotation matchNodes from network config to show selected nodes in detail page

pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
Fix number validation logic in VLAN ID input mask in the VM network creation/edit dialogue to allow input of any number between 1 and 4094, as intended.
The new logic does away with regex and just checks if the input value is number-like and within the allowed range. For any number-like outside the range, the input is clamped to the closest value within the range.
related-to: SURE-8851
- Is this a multi-tenancy feature/bug? No
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1? No
- Are backend engineers aware of UI changes? No Backend change needed.
Related Issue
https://jira.suse.com/browse/SURE-8851
https://github.com/harvester/harvester/issues/6290
=> fix: vlan id input mask

pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
Fix number validation logic in VLAN ID input mask in the VM network creation/edit dialogue to allow input of any number between 1 and 4094, as intended.
The new logic does away with regex and just checks if the input value is number-like and within the allowed range. For any number-like outside the range, the input is clamped to the closest value within the range.
related-to: https://jira.suse.com/browse/SURE-8851
related-to: https://github.com/harvester/harvester/issues/6290
related-to: https://github.com/harvester/dashboard/pull/1093
=> [Backport v1.2] fix: vlan id input mask

pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
Fix number validation logic in VLAN ID input mask in the VM network creation/edit dialogue to allow input of any number between 1 and 4094, as intended.
The new logic does away with regex and just checks if the input value is number-like and within the allowed range. For any number-like outside the range, the input is clamped to the closest value within the range.
related-to: https://jira.suse.com/browse/SURE-8851
related-to: https://github.com/harvester/harvester/issues/6290
related-to: https://github.com/harvester/dashboard/pull/1093
=> [Backport v1.3] fix: vlan id input mask

pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
Fix number validation logic in VLAN ID input mask in the VM network creation/edit dialogue to allow input of any number between 1 and 4094, as intended.
The new logic does away with regex and just checks if the input value is number-like and within the allowed range. For any number-like outside the range, the input is clamped to the closest value within the range.
related-to: https://jira.suse.com/browse/SURE-8851
related-to: https://github.com/harvester/harvester/issues/6290
related-to: https://github.com/harvester/dashboard/pull/1093
=> [Backport v1.4] fix: vlan id input mask

pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
- fix vlan id should be integer type
- allow user to modify vlan Id with empty value 
- ensure input value should between 1 ~ 4094 
- https://github.com/harvester/harvester/issues/6309
- https://github.com/harvester/harvester/issues/6290
Note. this PR should backport to v1.4 / v1.3 / v1.2
https://github.com/user-attachments/assets/1b8d6728-fb77-4f42-9b25-9f15b9c61baa
=> Fix vlan id should be integer type

pkg/harvester/config/harvester.js, pkg/harvester/config/table-headers.js, pkg/harvester/detail/harvesterhci.io.virtualmachineimage/index.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/mixins/harvester-vm/index.js, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Prior to this, the default size for volumes attached to VMs was 10GiB, regardless of the size of the underlying image.  This is fine if the image is smaller, but if the image is either physically larger (as in the case of a >10GiB ISO), or has a larger virtual size (as can be true with qcow2 images), the result is a corrupt volume.
This PR fixes the problem by checking both the physical size and virtual size of the image, and using whichever is greater as the default size of the volume.  Virtual size should always be >= physical size, but it is still theoretically possible for either value to be zero in case of error, so taking the greater of the two is the safest approach.
There are two exceptions to the above rule:
1) For non-ISO images, if the image is < 10GiB, we still default to a …
=> Take image virtual size into account when creating VMs

pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Related Issue # [[GUI] [FEATURE] Restore vm backup to other harvester cluster](https://github.com/harvester/harvester/issues/6371)
=> Add image restoring status

pkg/harvester/models/harvesterhci.io.upgrade.js, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
this is part of https://github.com/harvester/harvester/issues/5288, after https://github.com/harvester/harvester/pull/5386 merged to master, error message updated upon each retry failure. Before this pr, error message pops up only when upgrad CR imageReady is `False`.
related to https://github.com/harvester/harvester/issues/5288
N/A
Harvester upgrade
N/A
Test upgrade
[Screencast from 2024-03-18 17-17-20.webm](https://github.com/harvester/dashboard/assets/4344302/79ee13aa-8232-4011-bb99-d1ec40f648fa)
Test Image
=> Show error message upon each retry failure

pkg/harvester/l10n/en-us.yaml
Cherry-pick https://github.com/harvester/dashboard/pull/1107 change to master branch.
Note. I will start work on refactor [[ENHANCEMENT] Extract doc links mapping into a file](https://github.com/harvester/harvester/issues/6403) after this PR merged.
Related Issue # N/A
=> Fixed links to documents from old Harvester versions (backport #1107)

pkg/harvester/components/SettingList.vue, pkg/harvester/config/settings.js, pkg/harvester/l10n/en-us.yaml
Related issue: 
- https://github.com/harvester/harvester/issues/5274
- https://github.com/harvester/harvester/issues/5953
Note: this depends on https://github.com/harvester/harvester/pull/6405
Here's an example screenshot showing the setting with its description, along with the error message from Longhorn in the case where hugepages can't be allocated at runtime and a node needs rebooting:
Should add more text explaining what "preview feature" means in this context? Links to external docs? Anything else?
=> feat: Add ability to enable Longhorn V2 Data Engine

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
Move `reserved memory` out from Read More in VM and VM template pages
https://github.com/harvester/harvester/issues/5768 ([comment](https://github.com/harvester/harvester/issues/5768#issuecomment-2252213149))
VM detail and edit page
VM template detail and edit page
=> Move reserved memory out from Read More in VM and VM template detail pages

pkg/harvester/dialog/HarvesterMigrationDialog.vue
Filter out witness node when VM migration
Related Issue # [[BUG] The witness node should not be selected as a migration target](https://github.com/harvester/harvester/issues/5338)
The `harvester-node-1` is witness node. vm is deployed on `harvester-node-0`
=> Filter out witness node from VM migration dropdown

pkg/harvester/pages/c/_cluster/support/index.vue
Starting from Rancher v2.9 , we have [shell/components/templates](https://github.com/rancher/dashboard/tree/v2.9.0/shell/components/templates) defines different page layouts for each page in Rancher.
The router defined in [shell/config/router/router.js](https://github.com/rancher/dashboard/blob/07e1b2edb874777af07dce1cd30eecec1514ed42/shell/config/router/routes.js#L41-L56) missing name in home block. 
------------------------------------------------------------------------------------------------------------------------
To make harvester support page compatible for v2.8.x, v.2.9.0 and v2.9.1, this PR changes harvester support page layout to `default`.
The different is `default layout` has sidebar, while `home layou`t doesn't.
**default layout**
**home layout**
Note. this PR needs backport …
=> Fix harvester support link does not link to support page when embedded Rancher 2.9

pkg/harvester/components/SettingList.vue
Watch settings data to update harvester settings list.
https://github.com/harvester/harvester/issues/4463
harvester backend will auto hide (set to null in API response) below three fields once saved the backup target info. See https://github.com/harvester/harvester/issues/4463#issuecomment-2328016995
- access key id
- secret access key 
- cert 
We just need to refresh the whole settings on UI.
https://github.com/user-attachments/assets/46bcb657-1aae-4693-a713-cd3b6dda0716
=> Fix backup-target setting doesn't set to the latest value

pkg/harvester/components/UpgradeInfo.vue, pkg/harvester/components/settings/storage-network.vue, pkg/harvester/config/doc-links.js, pkg/harvester/edit/harvesterhci.io.host/HarvesterKsmtuned.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/list/harvesterhci.io.host.vue, pkg/harvester/package.json, pkg/harvester/pages/c/_cluster/support/index.vue
- Add tooltip and external link icon if no consoleUrl is set.
- Extract all harvester doc links into a config `doc-links.js` and auto construct the doc link with the harvester version in package.json.
- Discussed conclusion with @jillian-maroket  (https://github.com/harvester/harvester/issues/6403)
Related Issue # 
- https://github.com/harvester/harvester/issues/5679
- https://github.com/harvester/harvester/issues/6403
https://github.com/user-attachments/assets/969855af-ec23-4f3c-912c-59971a925e8f
=> Add console button tooltip and document link when button disabled

pkg/harvester/config/harvester-map.js, pkg/harvester/config/harvester.js, pkg/harvester/l10n/en-us.yaml, shell/assets/translations/en-us.yaml
Correct spelling mistakes and base UI review performed:
- VM = virtual machine
- addon = add-on
- Remove random capitalisation where not applicable 
- Remove double-spaces after a period
- Expand "config" to "configuration"
- Expand "admin" to "administrator" 
- Expand "docs" to "documentation
- Remove the use of the ampersand
- CDROM/cdrom to "CD-ROM"
- Expand "args" to "argument(s)"
[Issue #6407](https://github.com/harvester/harvester/issues/6407)
=> [ui-strings] Consistent language use applied across UI strings

pkg/harvester/config/harvester.js, pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue, pkg/harvester/list/kubevirt.io.virtualmachine.vue, pkg/harvester/store/harvester-store/actions.ts, shell/components/ExplorerProjectsNamespaces.vue, shell/list/namespace.vue
To prevent unknown resource quota schema error. Add check harvester resource quota schema.
[[GUI] [FEATURE] Allow users to set count/size limit on snapshots](https://github.com/harvester/harvester/issues/6054)
Test on 
- https://161.35.28.169.sslip.io/ (without schema) ✅ 
- https://152.42.233.250.sslip.io (with schema)  ✅
=> Check harvester resource quota schema to prevent unknown schema error

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
- Add cancelAction in VM create page to go back image list page.
- Replace `Create a Viurtal Machine` icon
https://github.com/harvester/harvester/issues/6485
[screen-capture.webm](https://github.com/user-attachments/assets/bd2a4ae9-b80d-4041-910c-a15789045511)
=> Add cancelAction in VM create page

pkg/harvester/edit/harvesterhci.io.volume.vue
This is a followup to https://github.com/harvester/dashboard/pull/1104
When creating new volumes on the Volume screen in Harvester, the default size is empty, i.e. it's not pre-filled with anything at all.  If the source is set to "VM image" we can now take the image virtual size and use that as the default size for the volume. Unlike when creating VMs (which always set the volume to a minimum of 10GiB regardless of virtual size, for consistency with earlier harvester versions), on this screen we just use the virtual size as-is.  If the user wants to make it bigger, they can.
Related issue: https://github.com/harvester/harvester/issues/4905
=> Take image virtual size into account when creating Volumes

.github/mergify.yml
For now, any PR merged into `master branch` should backport to `release-harvester-v1.4`, but sometimes we are easily forget to do that.
This PR automates below process 
- automatically open backport PR to release-harvester-v1.4 if any PR merged into master.
- automatically open backport PR to release-harvester-v1.3 if has label `Require backport v1.3` and merged into master.
- ask author to solve conlict
Reference : https://docs.mergify.com/workflow/actions/backport/
=> Add mergify.yml to automatically open backport PR

pkg/harvester/detail/harvesterhci.io.host/HarvesterHostBasic.vue, pkg/harvester/formatters/HarvesterStorageUsed.vue, pkg/harvester/list/harvesterhci.io.dashboard.vue, pkg/harvester/list/harvesterhci.io.host.vue, shell/assets/translations/en-us.yaml, shell/components/HardwareResourceGauge.vue
The displayed storage statistics in the `Dashboard` and `Hosts` page were incorrect. The calculation was incorrect and has been adapted to how it is done in [Longhorn](https://github.com/longhorn/longhorn-ui/blob/ed85b7b76923258ca3f6f95514d9aa18007a5eeb/src/routes/host/HostList.js#L198).
https://github.com/harvester/harvester/issues/6362
- Rename `Reserved` to `Allocated`.
- Adapt the calculation of the values used to populate the gauge components.
- Add properties to `HardwareResourceGauge` to be able to customize the titles.
The most important change was the calculation of the `total` storage which is done based on the formula `((maximum - reserved) * storageOverProvisioningPercentage)) / 100`.
=> Reserved storage size in the dashboard isn't useful

pkg/harvester/components/settings/additional-guest-memory-overhead-ratio.vue, pkg/harvester/config/settings.js, pkg/harvester/l10n/en-us.yaml
Add additional-guest-memory-overhead-ratio setting
https://github.com/harvester/harvester/issues/5768#issuecomment-2321046677
[ratio-setting.webm](https://github.com/user-attachments/assets/1d6636a8-8bac-4d86-a55d-954c01d5b9d4)
=> Add additional-guest-memory-overhead-ratio setting

pkg/harvester/formatters/HarvesterStorageUsed.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/list/harvesterhci.io.dashboard.vue
We changed storage title from "Reserved" to "Allocated" in https://github.com/harvester/dashboard/pull/1153/files.
Testing on Rancher v2.9.1, the allocated translation key is missing. Because current released rancher shell doesn't have that key
The safer way is to use harvester defined translation key
https://github.com/harvester/harvester/issues/6362
Test on Rancher 2.9.1
=> Fix: missing allocated translation key

shell/scripts/test-plugins-build.sh
fix check-plugin job failed : https://github.com/harvester/dashboard/actions/runs/10969497163/job/30462262664?pr=1151
[verdaccio v6.0.0](https://www.npmjs.com/package/verdaccio?activeTab=versions) is released yesterday. But requires node >= 18.
I tried update to node 18 or 20, but causes @achrinza/node-ipc complaining node is too new.
@achrinza/node-ipc needs `v9.2.5` to be able to run on Node 18. See : https://github.com/vuejs/vue-cli/issues/7424#issuecomment-1771133820
=> Pin verdaccio@5.32.2 for check-plugin CI job

pkg/harvester/config/harvester-map.js, pkg/harvester/config/table-headers.js, pkg/harvester/detail/harvesterhci.io.virtualmachineimage/index.vue, pkg/harvester/detail/kubevirt.io.virtualmachine/VirtualMachineTabs/VirtualMachineBasics.vue, pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io.vue, pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/container.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/list/harvesterhci.io.virtualmachineimage.vue, pkg/harvester/list/harvesterhci.io.volume.vue, pkg/harvester/list/kubevirt.io.virtualmachine.vue, pkg/harvester/mixins/harvester-vm/index.js, pkg/harvester/models/harvester/persistentvolumeclaim.js, pkg/harvester/models/harvester/secret.js, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js, pkg/harvester/models/kubevirt.io.virtualmachine.js
- Add Encrypted, Decrypted radio buttons and source image dropdown In image create page,
- In storage class create page, add volume encryption radio button and  secret namespace, secret name select dropdowns
- Show lock icon if image / volume is encrypted.
- Hide "export image" action if volume is encrypted
- Show encryption and secret in image detail page.
https://github.com/harvester/harvester/issues/6493
Create Storage class with Secret
[create_sc.webm](https://github.com/user-attachments/assets/15d1da9d-31c5-4f2d-85a7-baffc7dd8e86)
Encrypted  & decrypt Image …
=> Add volume and image encryption feature

pkg/harvester/mixins/harvester-vm/index.js
When uploading an image via file or URL, the `OS Type` auto-detection is not working for images named like `rhel-9.4-x86_64-kvm.qcow2`.
https://github.com/harvester/harvester/issues/6503
Add the string `rhel` to the matches that are used to identify Red Hat related images.
[Bildschirmaufzeichnung vom 2024-09-23 15-12-54.webm](https://github.com/user-attachments/assets/66031efd-d664-4ee3-ad87-b4af65d9d1bc)
1. Go `Images` and press `Create`.
2. Set the URL to the `rhel-9.4-x86_64-kvm.qcow2` image, for testing purpose this can ge `https://foo.bar/rhel-9.4-x86_64-kvm.qcow2`.
3. Go to the `Labels` tab and check if the label `harvesterhci.io/os-type` has been set to `Red Hat`.
1. Go `Images` and press `Create`.
2. Check the `File` checkbox and press `Upload File`. Select a file …
=> Detect Red Hat linux OS Type like Ubuntu and OpenSUSE

pkg/harvester/detail/harvesterhci.io.virtualmachineimage/index.vue, pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
From previous PR comment : https://github.com/harvester/dashboard/pull/1151#pullrequestreview-2320893761  
Modify 
- show `image_ns/image_displayName` as encrypt / decryt dropdown options
- add Encrypt Image / decrypt Image actions
- show Source Image in image detail and fix source Image in edit view page
https://github.com/harvester/harvester/issues/6493
Add `Encrypt Image` or `Decrypt Image` actions
Show source Image in detail page
Show image namespace + displayName as options
=> Add encrypt image and decrypt image actions

pkg/harvester/l10n/en-us.yaml, shell/creators/app/app.package.json
Fix https://github.com/harvester/dashboard/actions/runs/11025700963/job/30621227120?pr=1168
I tried using `node 20` in creator package like https://github.com/rancher/dashboard/pull/11808/files did.
But `@nuxt/babel-present-app` is not compatible to node 20.....
Pin the `@types/node` to v16 instead.
=> Fix check-plugins CI job

pkg/harvester/config/labels-annotations.js, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVGpuDevices/index.vue, pkg/harvester/models/kubevirt.io.virtualmachine.js
It adds the vGpu devices tracked in VM's annotation to the VM's vGpu list.
Those vGpus are provisioned by Harvester when creating new clusters from Rancher.
Related Harvester Issue https://github.com/harvester/harvester/issues/6638
Blocks https://github.com/rancher/dashboard/pull/11399
- We need to define how to remove the provisioned vGpus. cc @ibrokethecloud
=> Add provisioned vGpus in VM's devices list.

pkg/harvester/models/harvester/persistentvolumeclaim.js
```
Boolean("false") -> true
```
https://github.com/harvester/dashboard/pull/1076#issuecomment-2375850418
https://github.com/harvester/harvester/issues/6493
=> Fix volume isEncrypted logic

pkg/harvester/l10n/en-us.yaml, pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue, pkg/harvester/list/harvesterhci.io.vmsnapshot.vue
Rename 
- Edit VM quota -> Edit Virtual Machine Quota
- Take VM Snapshot -> Take Virtual Machine Snapshot
- Target VM -> Target Virtual Machine
- Source VM -> Source Virtual Machine
https://github.com/harvester/harvester/issues/6407#issuecomment-2401421959
=> Rename some VM shorthands to Virtual Machine

pkg/harvester/models/harvester/persistentvolumeclaim.js, pkg/harvester/models/kubevirt.io.virtualmachine.js
As title ,remove clone action for LVM or LHv2 volume and VM attached with LVM or LHv2 volumes
https://github.com/harvester/harvester/issues/6762
=> Remove clone action for LVM and LHv2 volume

pkg/harvester/models/harvester/persistentvolumeclaim.js
> [!CAUTION]
> Should test again after Harvester bumps LH to v1.7.2-rc1.
Related Issue https://github.com/harvester/harvester/issues/6669
[LH added new message about failed replica](https://github.com/longhorn/longhorn-manager/pull/2918). The new `precheck new replica failed` should be treated as a DEGRADED status.
Extend DEGRADED error list.
=> feat: extend degraded errors

pkg/harvester/mixins/harvester-vm/index.js
Current root image only supports LHv1 volume, accessMode should be RWX.
https://github.com/harvester/harvester/issues/6793
=> Root disk volume accessMode should be RWX

shell/components/ResourceCancelModal.vue
Previous app modal porting missing ResourceCancelModal.vue change.
This PR ports `ResourceCancelModal` change into harvester shell.
ResourceCancelModal.vue in  Rancher/dashboard: https://github.com/rancher/dashboard/blob/aa015eda0474def6c302a7c92796731e5432b9a9/shell/components/ResourceCancelModal.vue#L55-L125
https://github.com/harvester/harvester/issues/6814
Before fix
After fix
=> Port ResourceCancelModal change into harvester shell

pkg/harvester/config/doc-links.js
Based on doc PR https://github.com/harvester/docs/pull/652, add `#remote-console` ancher in doc link.
https://github.com/harvester/harvester/issues/5679
=> update CONSOLE_URL doc link

pkg/harvester/components/HarvesterUpgrade.vue
Change upgrade error banner to error color.
Since this is one line change, I feel it's safe to backport to v1.4 release branch.
https://github.com/harvester/harvester/issues/6847
After fix
=> Change upgrade error banner to red color

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
Align CPU pinning checkbox position in cloud template. This is just simple checkbox position change. 
I think it's fine to backport to release-v1.4.
https://github.com/harvester/harvester/issues/6879
https://github.com/harvester/harvester/issues/6879
Before
After
=> Align CPU pinning checkbox position in cloud template

pkg/harvester/promptRemove/kubevirt.io.virtualmachine.vue, shell/components/PromptRemove.vue
I added `this.close()` in harvester legacy shell in previous AppModal porting PR to solve VM deletion modal can not dismiss issue.
```
#PromptRemove.vue
if (handled === undefined || handled) {
this.close();
return;
}
```
But it's not solve the issue in root cause. 
The root cause is commented in https://github.com/harvester/harvester/issues/6878#issuecomment-2451327542
https://github.com/harvester/harvester/issues/6840
On standalone harvester
https://github.com/user-attachments/assets/b0961fa5-7393-4976-91c8-ca390bd0346f
Rancher 2.9.2 …
=> fix delete VM modal cannot be dismiss

shell/models/steve-schema.ts
`shell/models/steve-schema.ts` was added in https://github.com/harvester/dashboard/pull/1208 which was not existed on Rancher v2.8 shell.
This PR add workaround if condition to avoid fall into below two throw new Error.
https://github.com/harvester/harvester/issues/6953
=> [WORKAROUND] fix create namespace page broken on rancher 2.8.x

pkg/harvester/edit/harvesterhci.io.storage/index.vue, pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v1.vue, pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v2.vue, pkg/harvester/edit/harvesterhci.io.volume.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue, pkg/harvester/models/harvester/persistentvolumeclaim.js, pkg/harvester/models/harvester/storage.k8s.io.storageclass.js, pkg/harvester/models/kubevirt.io.virtualmachine.js
The UI is currently using the Volume -> Storage Class object to get the `provisioner` and the `engine version` (for Longhorn).
The Storage Class can be null, if deleted by the uses.
We want to get those fields from PersistentVolume `spec` when the storageClass is null
- provisioner: `spec.csi.driver`
- dataEngine: `spec.csi.volumeAttributes.dataEngine`
Related Issue https://github.com/harvester/harvester/issues/6927
=> Get provisioner and engine version from Volume

pkg/harvester/models/harvester/storage.k8s.io.storageclass.js
`freenas-iscsi-csi` provisoner is unknown which is not Longhorn v1, Longhornv2 or LVM.
We can show empty string for unknown provisoner 
https://github.com/harvester/harvester/issues/6970
=> fix storage class page broken if get unknown provisioner

pkg/harvester/models/harvester/storage.k8s.io.storageclass.js
Based on https://github.com/harvester/dashboard/pull/1227#issuecomment-2467324125, show provisioner instead of null
https://github.com/harvester/dashboard/pull/1227
=> Show provisioner in provisioner colume instead of empty string

.github/mergify.yml
v1.4.0 release is out. 
Any PR attached with `Require backport v1.4`  label will auto open backport PR via mergify.
=> Add Require backport v1.4 label in mergify.yaml

shell/store/index.js
Fix API token data not refresh in standalone harvester.
Standalone harvester doesn't have websocket connect to `/v3/token`. While rancher dashboard have dispatch [rancher/subscribe](https://github.com/rancher/dashboard/blob/master/shell/store/index.js#L799).
https://github.com/harvester/harvester/issues/6841
Backend PR : https://github.com/harvester/harvester/pull/7076
Note. this PR needs to open in rancher/dashboard to fix the same issue on harvester-ui-extension.
https://github.com/user-attachments/assets/b6c5701f-b255-4434-8a11-7febef33a668
=> fix API token data not refresh issue

pkg/harvester/formatters/HarvesterStorageUsed.vue
Allocated and used in storage column might in different units. (GiB/ TiB)
Separate the allocated / used unit calculation to avoid using the same unit.
https://github.com/harvester/harvester/issues/7081
Before  (the used value is 32 MB / 1.62TiB)
After
=> fix: separate used/allocated units

pkg/harvester/formatters/HarvesterStorageUsed.vue
Allocated and used in storage column might in different units. (GiB/ TiB)
Separate the allocated / used unit calculation to avoid using the same unit.
https://github.com/harvester/harvester/issues/7081
Before  (the used value is 32 MB / 1.62TiB)
After
<hr>This is an automatic backport of pull request #1240 done by [Mergify](https://mergify.com).
=> fix: separate used/allocated units (backport #1240)

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, pkg/harvester/mixins/harvester-vm/index.js
https://github.com/harvester/harvester/issues/6554
Prior to this, the default size for volumes attached to VMs was 10GiB, regardless of the size of the underlying image.  This is silly for ISO images, for which we can determine the size automatically.  The volume size will be set to the size of the ISO image, rounded up to the next whole number of GiB.
This PR also incidentally includes the fix for https://github.com/harvester/harvester/issues/5142 to set the bus type correctly for CD-ROMs.
This PR is based on larger work done for Harvester v1.4 (for details of that see …
=> Automatically set volume size for ISO images

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/DeviceList.vue
fix: keep parent sriov filter result if pcidevices status change
https://github.com/harvester/harvester/issues/6660
Fixed Recording
https://github.com/user-attachments/assets/f394f8f9-3380-45f1-963a-b05376ce6dec
=> fix: keep parent sriov filter result if pcidevices status change

pkg/harvester/components/AppModal.vue, pkg/harvester/dialog/HarvesterSupportBundle.vue, pkg/harvester/dialog/RestartVMDialog.vue
Previous [PR](https://github.com/harvester/dashboard/pull/1163) port AppModal component from Rancher/shell to harvester shell. But the appModal was introduced after Rancher 2.9+ which causes it doesn't exist on Rancher 2.8.
This PR port AppModal component to harvester source code.
https://github.com/harvester/harvester/issues/7147
```
1. Import harvester into Rancher 2.8 or 2.9
2. Pull this PR locally and run `yarn build-pkg harvester && yarn serve-pkgs`
3. Change 
- ui-plugin-index setting to http://127.0.0.1:4500/harvester-1.4.0/harvester-1.4.0.umd.min.js
- ui-source to external
4. …
```
=> fix: port AppModal component to harvester source code

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVGpuDevices/index.vue
Consume `domain?.devices?.gpus` when VM is off, while consume `harvesterhci.io/deviceAllocationDetails` when VM is running 
https://github.com/harvester/harvester/issues/7003
=> fix: vGPU number not correct

.github/workflows/build-and-upload-branch.yaml
ci: disable master branch build
https://github.com/harvester/harvester/issues/7089
=> ci: disable master branch build

pkg/harvester/models/harvester/persistentvolumeclaim.js
fix: isEncrypted() breaks the volume page.
https://github.com/harvester/harvester/issues/7150
kubectl apply  -f fake-pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
name: fake-pv
spec:
accessModes:
- ReadWriteMany
capacity:
storage: 10Gi
claimRef:
apiVersion: v1
kind: PersistentVolumeClaim
name: fake-pvc
namespace: default
volumeMode: Block
local:
path: /tmp/foo
nodeAffinity:
required:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/hostname
operator: In
values:
- fake-node-name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: fake-pvc
spec: …
```
=> fix: isEncrypted breaks volume page

pkg/harvester/components/novnc/NovncConsole.vue, pkg/harvester/l10n/en-us.yaml
`vncConsole.reconnecting.message` label is missing
[[BUG] [UI] Missing vnc reconnecting label #7182](https://github.com/harvester/harvester/issues/7182)
The label is missing from the shell/assets/translations/en-us.yaml in Rancher version 2.9 and lower.
Ref: https://github.com/rancher/dashboard/blob/release-2.9/shell/assets/translations/en-us.yaml#L7757-L7759.
Add translation key to `pkg/harvester/l10n/en-us.yaml` to fix the issue.
Add translation key to `pkg/harvester/l10n/en-us.yaml` to fix the issue.
1. Go to Rancher
2. Go to Virtualization Management -> Harvester cluster -> Virtual …
=> fix: missing vnc reconnecting label

pkg/harvester/detail/harvesterhci.io.host/VirtualMachineInstance.vue
Related Issue https://github.com/harvester/harvester/issues/7082
- VMs are now computed values
- Removing vmi mapping - vmi is already a vm's model property
[Screencast from 2025-01-09 11-50-09.webm](https://github.com/user-attachments/assets/00f4625b-37d2-4cc4-97cf-fce80b9a86ca)
=> Fix vm rows reactivity

pkg/harvester/components/FilterVMSchedule.vue
Port https://github.com/harvester/harvester-ui-extension/pull/85/commits/d72857f374911ebe7faf70679a59abd89ffc9890 to harvester/dashboard.
https://github.com/harvester/harvester/issues/6949
=> disable filter schedule button if all rows do not have sourceSchedule

pkg/harvester/edit/harvesterhci.io.addon/vm-import-controller.vue
fix: bring default `this.value.spec.valuesContext` when customizing vm-import controller
```
valuesContent: |
image:
tag: v0.4.1
fullnameOverride: harvester-vm-import-controller
```
https://github.com/harvester/harvester/issues/7351#issuecomment-2585949989
Will port to harvester-ui-extension once this PR merged.
https://github.com/user-attachments/assets/e3a7ba42-834d-424b-bf1f-058aae58b0cb
=> fix: bring default valuesContext when customizing vm-import-controller addon

shell/components/form/LabeledSelect.vue
Display the corresponding message if no matching options are found.
Related Issue [#7305](https://github.com/harvester/harvester/issues/7305)
Add condition `this.isSearchable` to function `showTagPrompts`
Go to Rancher
Go to Virtualization Management -> Harvester cluster -> Virtual Machines
Click on Console button
- Go to `Logging ->  Cluster Flows`
- Click `Create` button and click second tab `Outputs`
- Click the `Cluster Outputs` options, it should show `Sorry, no matching options`.
- Same behavior to create `Flows`
=> feat: cluster output select dropdown should show meaningful sentence if no options available

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue, pkg/harvester/l10n/en-us.yaml, shell/components/form/KeyValue.vue, shell/components/form/Labels.vue
Allow the user to manage the labels of a Virtual Machine resource via UI. Right now it is only possible to manage instance labels that are synced from the VM to the VMI resource.
Fixes #https://github.com/harvester/harvester/issues/5974
=> Add `Labels` tab to `Virtual Machines` resource page

pkg/harvester/l10n/en-us.yaml, pkg/harvester/pages/c/_cluster/brand/index.vue
The hints on the Branding page at `Advanced > Settings > UI > branding` are using the product name `Rancher` instead of `Harvester`.
Related Issue 
https://github.com/harvester/harvester/issues/6341
After:
=> The hints on the branding page is using the wrong product name

pkg/harvester/components/settings/csi-driver-config.vue
The `backupVolumeSnapshotClassName` should be grayed out directly for third-party storage.
- Do we need to backport this PR change to the [Harvester Dashboard](https://github.com/harvester/dashboard)?
[[BUG][GUI] Should Allow set empty for backupVolumeSnapshotClassName in Setting csi-driver-config #7737
](https://github.com/harvester/harvester/issues/7737#issuecomment-2700003551)
- Navigate to Advanced → Settings → edit `csi-driver-config`
- Click `Add`, and the `Backup Volume Snapshot Class Name field` should be disabled
- Select the appropriate option, save and ensure it saves correctly
N/A
=> fix: allow set empty for backupVolumeSnapshotClassName in Setting csi-driver-config

pkg/harvester/edit/loadbalancer.harvesterhci.io.ippool/Range.vue
- Update the range condition from `AND` to `OR`
[[BUG] IPPool Config should provide same content as YAML #6046](https://github.com/harvester/harvester/issues/6046)
- The `Start IP` field should be displayed in the `range-subnet-start` config
- The `End IP` field should be displayed in the `range-subnet-end` config
=> fix: IPPool Config should provide same content as YAML
